import type { Metadata } from "next";
import { huronsItpraTheory } from "@/content/hurons-itpra-theory-of-expectation";
import { OutcomeHinge } from "../_components/OutcomeHinge";
import { AppraisalTrace } from "../_components/AppraisalTrace";
import { Audio } from "../_components/Audio";
import { Contents } from "../_components/Contents";
import { Evidence, Scope, Sources, ProvenanceRegister, Relations } from "../_components/Apparatus";
import { Note, Rich, SectionLead } from "../_components/Type";
import { Intervention } from "../_components/Pigment";

export const metadata: Metadata = { title: "Huron’s ITPRA Theory of Expectation · B2 prototype" };
const h = huronsItpraTheory.huron!;
const contents = [{ id: "sources-of-expectation", title: "Expectation sources" }, { id: "outcome", title: "The outcome hinge" }, { id: "appraisal", title: "Revisiting the event" }, { id: "evidence", title: "Evidence" }, { id: "scope", title: "Scope" }, { id: "sources", title: "Sources & provenance" }];

export default function ItpraPage() {
  return <main id="b2-main" className="b2-main b2-itpra-page">
    <header className="b2-title-block b2-itpra-title"><p className="b2-eyebrow">Theory · Music psychology · David Huron</p><h1><span className="b2-itpra-name">ITPRA</span><span className="b2-title-subline">A theory of <em>expectation.</em></span></h1><div className="b2-title-aside"><p>One outcome can open<br />more than one question.</p><Intervention tone="vermilion">Expectation is not one feeling.</Intervention></div><p className="b2-intro">Huron’s ITPRA Theory of Expectation distinguishes what we imagine and prepare for, how an outcome is met, and what it comes to mean.</p><Note glyph="●">Five proposed response functions. Their order in the acronym is not a five-stage processing algorithm.</Note></header>
    <Contents items={contents} />
    <section id="sources-of-expectation" className="b2-section"><SectionLead n="01" title="Expectation comes from several places."><p>{h.sourcesOfExpectation.lede}</p></SectionLead><div className="b2-expectation-sources">{h.sourcesOfExpectation.sources.map((item, i) => <article key={item.label}><span className="b2-source-initial" aria-hidden="true">{["S", "V", "D", "C"][i]}</span><div><h3>{item.label.toLowerCase()}</h3><p className="b2-functional-question">{item.question}</p><p>{item.body}</p><span className="b2-small">{item.memory}</span></div></article>)}</div><div className="b2-source-concurrence"><strong>Concurrent, and sometimes in conflict.</strong><p>A familiar deceptive cadence may be veridically expected because the listener knows this piece, while remaining schematically unexpected within a learned style.</p><Note glyph="▲">Canonical abstract teaching example. The four expectation sources are not four stages before Imagination.</Note></div></section>
    <section id="outcome" className="b2-section"><SectionLead n="02" title="An outcome is a hinge, not a queue."><p>{h.timeline.lede}</p></SectionLead><OutcomeHinge windows={h.timeline.windows} /><div className="b2-fixed-event"><span className="b2-eyebrow">One constructed musical event</span><p>{h.surprise.event}</p><Audio events={h.surprise.events} label="Hear the fixed event" /><Note glyph="▲">Four context tones, C4–E4–G4–G4, followed by A♭4. This original example is fixed; it does not test your reinforcement, protective reaction, appraisal or nervous system. All functional questions are available without listening.</Note></div><div className="b2-reading-pair"><div><h3>A prediction and a Prediction Response.</h3><p>{h.prediction.lede}</p><Note glyph="●">Huron’s proposed reinforcement account; a forecast is formed before onset, while its accuracy can be evaluated after onset.</Note></div><div><h3>Preparation has its own meaning.</h3><p>{h.tension.lede}</p><Note glyph="■">Tension Response is kept distinct from harmonic dissonance, generic subjective musical tension and GTTM prolongational tension.</Note></div></div></section>
    <section id="appraisal" className="b2-section"><SectionLead n="03" title="Later understanding can return to the event."><p>{h.appraisal.lede}</p></SectionLead><AppraisalTrace /><div className="b2-continuous-reading"><h3>Different responses need not agree.</h3><p>{h.valence.lede}</p><p>{h.valence.note.replace(/^[●■▲✦? /]+/, "")}</p><Note glyph="?">A possible contrast is not a universal pleasure mechanism. Later surprise-and-pleasure findings do not directly validate separate ITPRA systems or this complete pathway.</Note></div></section>
    <section id="evidence" className="b2-section b2-quiet"><SectionLead n="04" title="A theory, and the evidence beside it."><p>{h.evidence.lede}</p></SectionLead><Evidence items={h.evidence.items.filter((_, i) => [0, 1, 4].includes(i))} /><Note glyph="■">The theoretical book, harmonic-expectancy study and later surprise/pleasure study have different responsibilities. None is displayed as a replication of the others.</Note></section>
    <section id="scope" className="b2-section b2-quiet"><SectionLead n="05" title="The account remains a bounded one."><p>{h.scope.lede}</p></SectionLead><Scope explains={h.scope.explains} stops={h.scope.stops} qualifications={huronsItpraTheory.qualifications!} /><div className="b2-continuous-reading"><h3>Keep the neighbouring concepts distinct.</h3>{huronsItpraTheory.oversimplifications!.filter((_, i) => [1, 4, 6, 9].includes(i)).map(item => <p key={item}><Rich text={item} /></p>)}</div></section>
    <section id="sources" className="b2-section b2-quiet"><SectionLead n="06" title="The source has the final word on its claim."><p>Attribution keeps the proposed architecture distinct from its teaching representation and the empirical work around it.</p></SectionLead><Sources minimum={huronsItpraTheory.minimumReading!} full={huronsItpraTheory.fullSources!} /><ProvenanceRegister items={huronsItpraTheory.provenance} local="This B2 arrangement uses a concurrent outcome composition, one fixed audio event and a local appraisal-retention construction. The earlier response remains legible in every appraisal state. Line shape is schematic; colour carries no evidence class or emotional magnitude. The canonical on-time/delayed construction is not included in this selected prototype." /><Relations items={huronsItpraTheory.relatedTo!} /></section>
  </main>;
}
