import type { TheoryRecord } from "./types";

const tonalContext = [
  { pitch: 60, beats: 0.8 },
  { pitch: 64, beats: 0.8 },
  { pitch: 67, beats: 0.8 },
  { pitch: 69, beats: 0.8 },
];

export const meyersExpectancyTheory: TheoryRecord = {
  id: "meyers-expectancy-theory",
  kind: "theory",
  slug: "meyers-expectancy-theory",
  title: "Meyer’s Expectancy Theory",
  hook: "Where does this want to go — and why can what happens later change what you heard earlier?",
  oneSentence: "Meyer’s expectancy account explains how learned musical relationships can make events feel meaningful, affectively charged, and open to reinterpretation as the music unfolds.",
  discipline: "music-psych",
  statusChip: "historical theoretical account",
  topics: ["musical expectancy", "musical meaning", "music and emotion", "style and learning", "music theory"],
  facts: ["multiple futures", "style is learned", "meaning moves backward", "1956 → later models", "expectancy ≠ all emotion"],
  order: [
    "opening", "embodied", "branches", "style", "outcomes", "delay", "resolution", "meaning",
    "gestalt", "listener", "evidence", "scope", "lineage", "explains", "stops",
    "trail", "oversimplifications", "qualifications", "sources", "related", "provenance",
  ],
  headings: {
    opening: { toc: "Where does this want to go?", title: "Where does this want to go?" },
    embodied: { toc: "Music points forward", title: "Music points forward" },
    branches: { toc: "Several futures", title: "One moment, several futures" },
    style: { toc: "Where expectation comes from", title: "Where did that expectation come from?" },
    outcomes: { toc: "Different outcomes", title: "Same setup, different outcome" },
    delay: { toc: "Why delay feels unfinished", title: "Why delay feels unfinished" },
    resolution: { toc: "Then it resolves", title: "Then it resolves" },
    meaning: { toc: "Meaning rewrites itself", title: "Meaning rewrites itself" },
    gestalt: { toc: "The Gestalt underneath", title: "The Gestalt underneath" },
    listener: { toc: "Style lives in the listener", title: "Style lives in the listener" },
    evidence: { toc: "Does expectancy change experience?", title: "Does expectancy really change experience?" },
    scope: { toc: "Not the whole emotion story", title: "Expectation is not the whole emotion story" },
    lineage: { toc: "What came after Meyer?", title: "What came after Meyer?" },
    explains: { toc: "What Meyer explains", title: "What Meyer explains" },
    stops: { toc: "Where Meyer stops", title: "Where Meyer stops" },
    trail: { toc: "The intellectual trail", title: "The intellectual trail" },
    oversimplifications: { toc: "Don’t conclude", title: "Don’t conclude" },
    qualifications: { toc: "Still open", title: "Still open" },
    sources: { toc: "Sources", title: "Sources" },
    related: { toc: "Related records", title: "Related records" },
    provenance: { toc: "Provenance", title: "Where every claim came from" },
  },

  ideaLede: "Listen for the moment before the next moment. A phrase can feel as if it is leaning somewhere before the continuation arrives — and the continuation can make the earlier phrase sound different in retrospect.",
  originsNote: "This record teaches Meyer as a historical aesthetic-psychological account. Later computational, predictive-processing, and reward approaches are connected as distinct developments, not folded backward into the 1956 theory.",

  meyer: {
    opening: {
      lede: "Start with the listener’s experience, not with a definition. Hear a short musical context, pause at an unresolved point, and audition several futures. None is a universally correct answer.",
      context: tonalContext,
      choices: [
        { label: "strongly implied", body: "This continuation follows the tonal pull established by the setup.", notes: [{ pitch: 71, beats: 0.8 }, { pitch: 72, beats: 1.4 }] },
        { label: "plausible", body: "This continuation remains possible, but it changes the direction of the phrase.", notes: [{ pitch: 70, beats: 0.8 }, { pitch: 69, beats: 1.4 }] },
        { label: "less implied", body: "This continuation interrupts the first pull and leaves more work for later context.", notes: [{ pitch: 65, beats: 0.8 }, { pitch: 62, beats: 1.4 }] },
      ],
      note: "The point is not to score the listener’s prediction. The point is to notice that a present event can make some musical futures feel more available than others.",
    },
    embodied: {
      lede: "Meyer distinguishes <b>embodied meaning</b> from designative meaning. This page focuses on embodied musical meaning: meaning can arise in relationships among musical events and therefore need not depend on external reference. That is not a claim that Meyer denied all referential or extramusical meaning.",
      points: [
        "A note matters partly because of what it makes possible next.",
        "A musical event becomes more determinate through its relationships with other events.",
        "The account concerns musical relations, not the later theory of embodied cognition.",
      ],
      note: "Meyer’s source-grounded distinction is about how meaning is organised in music; “points forward” is the page’s plain-language bridge.",
    },
    branches: {
      lede: "Expectation does not require one exact next note. A listener can hold several possible consequents in play, with different degrees of implication, plausibility, or stability.",
      current: "an unresolved musical gesture",
      items: [
        { label: "strongly implied", body: "The continuation fits the active stylistic and local pull.", colour: "var(--teal)" },
        { label: "plausible", body: "The continuation is available, though it redirects the phrase.", colour: "var(--gold-deep)" },
        { label: "less implied", body: "The continuation is possible but needs later context to become intelligible.", colour: "var(--red)" },
      ],
      note: "Concept Lab synthesis. The branches are qualitative; their position and colour do not encode numerical probability.",
    },
    style: {
      lede: "Where did the sense of direction come from? Meyer treats musical style as a learned system of relationships. Perceptual organisation matters, but what counts as a gap, continuation, or completion depends partly on the musical system the listener has learned.",
      cards: [
        { label: "STYLE", body: "A network of relationships that makes some continuations more probable or intelligible within a musical system.", colour: "var(--teal)" },
        { label: "PAST EXPERIENCE", body: "Listening history supplies habits of response. Expectancy is not detached from memory and learning.", colour: "var(--gold-deep)" },
        { label: "PERCEPTUAL ORGANISATION", body: "Grouping, continuation, completion, and closure help a listener hear events as parts of a pattern.", colour: "var(--red)" },
      ],
      note: "Meyer explicitly uses probability language for style, while this record reserves entropy and formal information measures for later computational work.",
    },
    outcomes: {
      lede: "Keep the setup stable and change the continuation. The comparison is not a contest in emotional intensity; it is a way to hear how fulfilment, delay, and diversion alter the still-open musical situation.",
      context: tonalContext,
      variants: [
        { label: "fulfilled", title: "Fulfilled", body: "The active tendency receives a relatively immediate continuation.", notes: [{ pitch: 71, beats: 0.8 }, { pitch: 72, beats: 1.4 }], colour: "var(--teal)" },
        { label: "delayed", title: "Delayed", body: "The likely continuation is postponed, so the tendency remains active for longer.", notes: [{ pitch: 69, beats: 0.7 }, { pitch: 70, beats: 0.7 }, { pitch: 71, beats: 0.7 }, { pitch: 72, beats: 1.4 }], colour: "var(--gold-deep)" },
        { label: "diverted / deviated", title: "Diverted", body: "The continuation moves elsewhere; later events may clarify whether the diversion was meaningful.", notes: [{ pitch: 70, beats: 0.8 }, { pitch: 68, beats: 0.8 }, { pitch: 65, beats: 1.4 }], colour: "var(--red)" },
      ],
      question: "When did the music still feel unfinished?",
      note: "▲ Constructed audio comparison. It demonstrates a theoretical distinction and does not claim that every listener will report the same experience.",
    },
    delay: {
      lede: "Meyer’s tendency / inhibition logic is temporal. The important question is not simply whether an event was unexpected, but whether an active possibility remains unresolved or obstructed.",
      steps: [
        "An active possibility becomes available within the musical context.",
        "The likely continuation is postponed, redirected, or inhibited.",
        "Uncertainty and continued tendency may sustain tension or suspense.",
        "Later events can fulfil, transform, or clarify what remained open.",
      ],
      note: "Tension is not the same construct as emotion. Delay is not identical to violation, and unexpectedness alone is not a complete explanation.",
    },
    resolution: {
      lede: "Fulfilment matters because a tendency was already active. It is not an automatic pleasure button and not the only desirable musical outcome.",
      note: "A continuation can clarify an active relation, but its affective significance depends on the unfolding structure and the listener’s learned stylistic orientation. This is a faithful explanation, not a universal prediction.",
    },
    meaning: {
      lede: "Meyer’s most distinctive teaching opportunity is temporal and retrospective. Meaning is not merely carried forward; later musical development can change how an earlier event is understood.",
      stages: [
        { label: "TIME 1 · HYPOTHETICAL", question: "What might this event imply?", body: "Before the continuation arrives, the listener entertains possible relationships and futures.", colour: "var(--teal)" },
        { label: "TIME 2 · EVIDENT", question: "What actually followed?", body: "The realised continuation gives the earlier event an immediate, evident relation.", colour: "var(--red)" },
        { label: "TIME 3 · DETERMINATE", question: "What does the larger passage now reveal?", body: "The completed or remembered work can make the earlier event’s function more determinate.", colour: "var(--plum-deep)" },
      ],
      note: "■ Faithful paraphrase of Meyer’s hypothetical, evident, and determinate meanings. The backward arrow is a Concept Lab visual synthesis of retrospective reinterpretation.",
    },
    gestalt: {
      lede: "Meyer uses Gestalt-derived pattern principles as a bridge between perception and expectation. Only three ideas are needed here.",
      cards: [
        { label: "GOOD CONTINUATION", body: "A pattern can make a continuation feel like the direction in which an established form is moving.", colour: "var(--teal)" },
        { label: "COMPLETION", body: "A partial or open pattern can invite the listener to hear what would make it more whole.", colour: "var(--gold-deep)" },
        { label: "CLOSURE", body: "A musical process can reach a point that feels sufficiently settled within its style and context.", colour: "var(--red)" },
      ],
      note: "This is a compact bridge to a future “Gestalt Principles in Music” record, not a second Gestalt theory page.",
    },
    listener: {
      lede: "The opening example is not a universal hearing test. Meyer’s historical point is that style norms and probability relationships are learned and culturally situated.",
      cards: [
        { label: "A learned tonal style", body: "The synthetic opening demonstrates expectancy inside one familiar tonal system.", colour: "var(--teal)" },
        { label: "A different learning history", body: "A listener with different musical exposure may organise the same event differently; the page should not invent a specific cross-cultural result.", colour: "var(--gold-deep)" },
        { label: "A different expectancy structure", body: "What feels strongly implied is conditioned by the style relationships available to the listener.", colour: "var(--red)" },
      ],
      note: "▲ The audio is a constructed tonal teaching example. It is not evidence that Western tonal syntax is universal human musical syntax.",
    },
    evidence: {
      lede: "These four layers support parts of the expectancy picture. None should be used as blanket validation of every arrow in Meyer’s account.",
      items: [
        {
          title: "Meyer (1956)",
          label: "process model",
          citation: "Meyer, L. B. (1956). <i>Emotion and Meaning in Music</i>.",
          design: "Historical theoretical / aesthetic-psychological synthesis.",
          testedLabel: "what it provides",
          tested: "A conceptual account of musical meaning, tendency, expectation, style, pattern organisation, and affect.",
          foundLabel: "what it argues",
          found: "Musical relationships can activate tendencies whose fulfilment, delay, or deviation matters to meaning and affect.",
          notTested: "A modern controlled causal test of the complete account, or a universal mapping from musical event to discrete emotion.",
        },
        {
          title: "Steinbeis, Koelsch & Sloboda (2006)",
          label: "empirical study",
          citation: "The role of harmonic expectancy violations in musical emotions.",
          design: "N = 24: 12 musicians and 12 nonmusicians; six Bach chorales with expected, unexpected, and very unexpected harmonies; subjective ratings, EDA / HR, and EEG.",
          testedLabel: "what it tested",
          tested: "Whether controlled harmonic unexpectedness covaried with tension, emotionality, physiological response, and expectancy-sensitive neural activity.",
          foundLabel: "what it found",
          found: "Greater harmonic unexpectedness was associated with increased subjective tension / emotional impact and EDA, alongside expectancy-sensitive neural responses.",
          notTested: "A discrete emotion label, a universal response, or the complete Meyer architecture.",
        },
        {
          title: "Egermann et al. (2013)",
          label: "empirical study",
          citation: "Probabilistic models of expectation violation predict psychophysiological emotional responses to live concert music.",
          design: "Live flute concert with 50 participants; six solo flute pieces; modelled pitch expectations, continuous unexpectedness and valence / arousal ratings, facial EMG, and peripheral arousal.",
          testedLabel: "what it tested",
          tested: "Whether modelled musical information content and listener-rated unexpectedness related to continuous emotion-related responses in a naturalistic setting.",
          foundLabel: "what it found",
          found: "High-information events, reported unexpectedness, and emotional reactions were related, particularly through arousal and autonomic activation.",
          notTested: "Whether Meyer’s complete mechanism is true, or whether one expectancy profile produces one emotion category.",
          doi: "10.3758/s13415-013-0161-y",
        },
        {
          title: "Gold et al. (2019)",
          label: "empirical study",
          citation: "Predictability and uncertainty in the pleasure of music: A reward for learning?",
          design: "Two behavioural liking studies: Study 1 N = 43; Study 2 N = 27. Information content and entropy were modelled in real precomposed music; liking and familiarity were measured.",
          testedLabel: "what it tested",
          tested: "Relationships among predictability, uncertainty, complexity, familiarity, and liking.",
          foundLabel: "what it found",
          found: "Liking showed quadratic / intermediate-complexity effects, with an interaction between predictability and uncertainty.",
          notTested: "Direct neural reward-system activity, or the claim that more surprise produces more pleasure.",
          doi: "10.1523/JNEUROSCI.0428-19.2019",
        },
      ],
    },
    scope: {
      lede: "Expectancy is an important route from musical organisation into affect, but it is not a complete theory of every way music can evoke emotion.",
      explains: [
        "expectation, musical implication, and structured possibility",
        "style-based learning and the listener’s changing orientation",
        "delay, inhibition, fulfilment, clarification, and tension",
        "intrinsic musical meaning and retrospective reinterpretation",
      ],
      stops: [
        "exact emotion categories and affective differentiation by expectancy alone",
        "episodic memory, emotional contagion, imagery, conditioning, and brainstem reflexes",
        "modern neural prediction-error or reward mechanisms",
        "universal cross-cultural expectations",
      ],
      note: "Juslin and Västfjäll place musical expectancy beside other emotion-induction mechanisms; Margulis shows why expectancy may explain an affective shift without specifying which particular emotion it becomes.",
    },
    lineage: {
      lede: "What came after Meyer is a branching intellectual history, not a sequence of increasingly correct versions.",
      nodes: [
        { label: "MEYER", body: "Meaning, tendency, expectation, affect, style, learning, and pattern organisation.", colour: "var(--teal)" },
        { label: "NARMOUR", body: "A more formal melodic implication / realization account with distinct bottom-up and top-down systems.", colour: "var(--red)" },
        { label: "HURON", body: "ITPRA and multiple expectation-related response systems.", colour: "var(--gold-deep)" },
        { label: "STATISTICAL LEARNING", body: "Learned regularities and probabilistic prediction, including IDyOM.", colour: "var(--teal)" },
        { label: "PREDICTIVE PROCESSING", body: "A later broader cognitive and neuroscientific framework.", colour: "var(--plum-deep)" },
        { label: "MUSICAL REWARD", body: "Later work on predictability, uncertainty, pleasure, learning, and reward.", colour: "var(--red)" },
      ],
      note: "✦ Concept Lab synthesis. Each node retains its own theoretical identity; later vocabulary is not attributed to Meyer.",
    },
    explains: [
      "why musical events can feel related rather than isolated",
      "why music can seem to point forward",
      "why learned style changes what feels implied",
      "why delay and fulfilment can matter to musical meaning and affect",
      "why a later passage can revise the meaning of an earlier event",
    ],
    stops: [
      "every music-induced emotion or exact emotion category",
      "autobiographical memory, contagion, imagery, conditioning, and reflexes",
      "predictive coding, Bayesian updating, precision weighting, or dopamine prediction error",
      "a universal account of all musical cultures and listeners",
      "a direct neural or computational test of the complete 1956 account",
    ],
  },

  trailLede: "A line of inquiry branches from Meyer’s musical meaning and expectation into later melodic models, computational enculturation, broader expectancy psychology, and reward research. The branches remain distinct.",
  origins: [
    { year: "1956", author: "Leonard B. Meyer", work: "Emotion and Meaning in Music · University of Chicago Press", contribution: "The anchor account: musical meaning, expectation, tendency, affect, style, learning, and pattern organisation." },
    { year: "1991", author: "Eugene Narmour", work: "The top-down and bottom-up systems of musical implication · Music Perception", contribution: "A later implication–realization model that formalises distinct sources of melodic implication." },
    { year: "2006", author: "David Huron", work: "Sweet Anticipation · MIT Press", contribution: "A later ITPRA account of multiple response systems around expectation." },
    { year: "2012", author: "Pearce & Wiggins", work: "Auditory expectation · Topics in Cognitive Science", contribution: "Information-dynamics and computational modelling of auditory expectation." },
    { year: "2018", author: "Marcus T. Pearce", work: "Statistical learning and probabilistic prediction in music cognition · Annals of the New York Academy of Sciences", contribution: "A computational account of stylistic enculturation and learned probabilistic prediction." },
    { year: "2019", author: "Gold et al.", work: "Predictability and uncertainty in the pleasure of music · Journal of Neuroscience", contribution: "Later behavioural evidence on predictability, uncertainty, complexity, and liking." },
  ],
  oversimplificationsLede: "Eight shortcuts would make the page easier to say and harder to understand.",
  oversimplifications: [
    "Meyer says <b>surprise causes emotion</b>. Expectancy effects depend on active tendencies, context, delay, meaning, and the listener’s learned style.",
    "Expectation means <b>one correct next note</b>. Several continuations can remain possible.",
    "<b>More surprise means more pleasure</b>. Later evidence shows interactions among predictability, uncertainty, complexity, familiarity, and liking.",
    "<b>Western tonal expectation is universal</b>. The example demonstrates one learned tonal style.",
    "Meyer invented <b>predictive coding</b>. Predictive-processing vocabulary belongs to later cognitive and neuroscientific work.",
    "Narmour and Huron are simply <b>later versions of Meyer</b>. They develop distinct models with different constructs and aims.",
    "Musical meaning is <b>fixed at first hearing</b>. Later development can revise earlier meaning.",
    "Expectancy explains <b>every musical emotion</b>. It is one possible mechanism among several.",
  ],
  qualifications: [
    "The audio examples are constructed tonal teaching examples, not empirical tests or demonstrations of a universal response.",
    "The evidence section supports selected relationships among expectancy, tension, arousal, liking, and meaning; it does not validate every part of Meyer’s 1956 account.",
    "The distinction between affective shift and affective differentiation remains important: expectancy may help explain why experience changes without specifying exactly what emotion is felt.",
    "The relation between Meyer’s conceptual probability language and later formal probability measures should remain explicit throughout the page.",
    "How listeners with different musical learning histories organise the same event remains a live empirical question, not a result to be invented by the page.",
  ],
  minimumReadingLabel: "If you read five things",
  minimumReading: [
    { citation: "Meyer, L. B. (1956). <i>Emotion and Meaning in Music</i>. University of Chicago Press.", contribution: "Primary source for embodied meaning, expectation, tendency, affect, style, learning, and retrospective meaning." },
    { citation: "Huron, D. (2006). <i>Sweet Anticipation: Music and the Psychology of Expectation</i>. MIT Press.", contribution: "Major later theory: ITPRA and multiple expectation-related response systems.", doi: "10.7551/mitpress/6575.001.0001" },
    { citation: "Pearce, M. T., &amp; Wiggins, G. A. (2012). Auditory expectation: The information dynamics of music perception and cognition. <i>Topics in Cognitive Science, 4</i>(4), 625–652.", contribution: "Computational and information-dynamics development of auditory expectation.", doi: "10.1111/j.1756-8765.2012.01214.x" },
    { citation: "Juslin, P. N., &amp; Västfjäll, D. (2008). Emotional responses to music: The need to consider underlying mechanisms. <i>Behavioral and Brain Sciences, 31</i>(5), 559–575.", contribution: "Places expectancy alongside other music-emotion mechanisms.", doi: "10.1017/S0140525X08005293" },
    { citation: "Gold, B. P., Pearce, M. T., Mas-Herrero, E., Dagher, A., &amp; Zatorre, R. J. (2019). Predictability and uncertainty in the pleasure of music: A reward for learning? <i>Journal of Neuroscience, 39</i>(47), 9397–9409.", contribution: "Later behavioural liking evidence on predictability, uncertainty, and intermediate complexity.", doi: "10.1523/JNEUROSCI.0428-19.2019" },
  ],
  fullSources: [
    { citation: "Narmour, E. (1991). The top-down and bottom-up systems of musical implication: Building on Meyer’s theory of emotional syntax. <i>Music Perception, 9</i>(1), 1–26.", contribution: "Later implication–realization development with bottom-up and top-down systems.", doi: "10.2307/40286156" },
    { citation: "Pearce, M. T. (2018). Statistical learning and probabilistic prediction in music cognition: Mechanisms of stylistic enculturation. <i>Annals of the New York Academy of Sciences, 1423</i>(1), 378–395.", contribution: "Learned probabilistic models of musical style and enculturation.", doi: "10.1111/nyas.13654" },
    { citation: "Krumhansl, C. L., &amp; Agres, K. R. (2008). Musical expectancy: The influence of musical structure on emotional response. <i>Behavioral and Brain Sciences, 31</i>(5), 584–585.", contribution: "Concise Open Peer Commentary on Meyer and expectancy; not used as a comprehensive review.", doi: "10.1017/S0140525X08005384" },
    { citation: "Margulis, E. H. (2014). Expectation, musical topics, and the problem of affective differentiation. In <i>The Oxford Handbook of Topic Theory</i>.", contribution: "Expectation may help explain affective change without specifying a particular emotion.", doi: "10.1093/oxfordhb/9780199841578.013.0025" },
    { citation: "Steinbeis, N., Koelsch, S., &amp; Sloboda, J. A. (2006). The role of harmonic expectancy violations in musical emotions. <i>Journal of Cognitive Neuroscience, 18</i>, 1380–1393.", contribution: "Controlled harmonic-expectancy evidence using subjective, physiological, and neural measures." },
    { citation: "Egermann, H., Pearce, M. T., Wiggins, G. A., &amp; McAdams, S. (2013). Probabilistic models of expectation violation predict psychophysiological emotional responses to live concert music. <i>Cognitive, Affective, &amp; Behavioral Neuroscience, 13</i>(3), 533–553.", contribution: "Naturalistic live-concert evidence linking modelled unexpectedness with emotion-related responses.", doi: "10.3758/s13415-013-0161-y" },
  ],
  relatedToLede: "Meyer’s record is adjacent to the existing Music Preference and Person–Music Fit field record. The connection is useful for separating what a listener likes from how a musical event unfolds in experience.",
  relatedTo: [
    { recordId: "music-preference", relation: "adds an unfolding-structure lens to", body: "Music Preference and Person–Music Fit asks about taste, familiarity, listening functions, and situation. Meyer asks how musical events point forward and acquire meaning as they unfold. The records are adjacent, not interchangeable." },
  ],
  provenance: [
    { glyph: "●", colour: "var(--red)", label: "Source-grounded theory and findings", note: "Meyer’s constructs, the later-theory distinctions, and the study design / sample / measure summaries are tied to the cited primary book, books, articles, and empirical reports." },
    { glyph: "■", colour: "var(--teal)", label: "Faithful explanation", note: "Plain-language explanations such as “music points forward” and the hypothetical–evident–determinate timeline paraphrase source-grounded distinctions without claiming to quote the authors." },
    { glyph: "▲", colour: "var(--gold-deep)", label: "Constructed teaching examples", note: "The synthetic tonal phrases, branching continuations, and fulfilled / delayed / diverted comparison are original teaching examples. They are not empirical evidence and do not prescribe a listener’s response." },
    { glyph: "✦", colour: "var(--pen-3)", label: "Concept Lab synthesis", note: "The page sequence, final branching model, retrospective arrow, lineage arrangement, and component-supported teaching path are editorial arrangements made to teach the cited literature." },
    { glyph: "?", colour: "var(--pen-3)", label: "Open or bounded", note: "Cross-cultural generality, exact affective differentiation, and the relation between later computational evidence and the full 1956 account remain qualified rather than resolved." },
  ],
};
