import type { TheoryRecord } from "./types";

export const selfDeterminationTheory: TheoryRecord = {
  id: "self-determination-theory",
  kind: "theory",
  slug: "self-determination-theory",
  title: "Self-Determination Theory",
  hook: "Why can two people do the same work with very different reasons moving them?",
  oneSentence: "Self-Determination Theory explains motivation by asking not only how much energy a person has, but what kind of motivation is moving the action.",
  discipline: "ob",
  topics: ["work motivation", "autonomous motivation", "basic psychological needs", "internalisation", "motivation quality"],
  facts: ["same action, different why", "6 regulation forms", "3 basic needs", "context matters", "macro-theory"],
  statusChip: "macro-theory",
  sdt: {
    opening: {
      cases: [
        { label: "Person A", quote: "I really believe this work matters.", body: "The visible effort may be similar to another person’s, but the reason is personally endorsed. That is a question about motivation quality." },
        { label: "Person B", quote: "If I leave now, my manager will think I’m lazy.", body: "The same late night may be powered by pressure, guilt, or fear of judgement. Effort alone does not reveal the reason." },
      ],
      note: "Constructed workplace examples. They introduce a conceptual contrast; they are not reported cases or evidence of a particular response.",
    },
    motives: [
      { statement: "I’ll get a bonus.", regulation: "External regulation", explanation: "The behaviour is organised around an external contingency: obtaining a reward or avoiding a consequence. It is extrinsic and relatively controlled.", relativeAutonomy: "least autonomous", motivationKind: "extrinsic", family: "controlled", colour: "var(--red)" },
      { statement: "I’d feel guilty if I didn’t.", regulation: "Introjected regulation", explanation: "The pressure has been taken inside, but the person is still acting to avoid guilt, shame, anxiety, or a threatened sense of worth rather than from full endorsement.", relativeAutonomy: "controlled", motivationKind: "extrinsic", family: "controlled", colour: "var(--red)" },
      { statement: "I think this matters.", regulation: "Identified regulation", explanation: "The person accepts the value of the activity and sees it as personally important, even if the activity is not enjoyable in itself.", relativeAutonomy: "more autonomous", motivationKind: "extrinsic", family: "autonomous", colour: "var(--teal)" },
      { statement: "This fits who I am.", regulation: "Integrated regulation", explanation: "The value has been brought into coherence with the person’s wider values and sense of self. The behaviour remains extrinsic because it serves a separable outcome.", relativeAutonomy: "highly autonomous", motivationKind: "extrinsic", family: "autonomous", colour: "var(--teal)" },
      { statement: "I genuinely enjoy doing it.", regulation: "Intrinsic motivation", explanation: "The activity is pursued for its inherent interest, enjoyment, or challenge. This is not simply the final stage of internalising an external demand.", relativeAutonomy: "most autonomous", motivationKind: "intrinsic", family: "autonomous", colour: "var(--gold-deep)" },
      { statement: "I honestly don’t see the point.", regulation: "Amotivation", explanation: "The person lacks intention, valuing, or a reason to act. Amotivation is not just low effort and is not another point on the autonomous–controlled contrast.", relativeAutonomy: "no clear intention", motivationKind: "amotivation", family: "amotivation", colour: "var(--plum-deep)" },
    ],
    regulations: [
      { label: "Amotivation", descriptor: "no intention", body: "No clear reason, value, or intention to act.", kind: "amotivation", colour: "var(--plum-deep)" },
      { label: "External regulation", descriptor: "external pressure", body: "Reward, punishment, demand, or surveillance supplies the reason.", kind: "controlled", colour: "var(--red)" },
      { label: "Introjected regulation", descriptor: "inner pressure", body: "Guilt, approval, ego, or contingent self-worth supply the pressure.", kind: "controlled", colour: "var(--red)" },
      { label: "Identified regulation", descriptor: "personal importance", body: "The person understands and accepts that the activity matters.", kind: "autonomous", colour: "var(--teal)" },
      { label: "Integrated regulation", descriptor: "coherent with self", body: "The value fits with wider values and the person’s sense of self; it remains extrinsic.", kind: "autonomous", colour: "var(--teal)" },
      { label: "Intrinsic motivation", descriptor: "inherent interest", body: "The activity is done for its inherent interest, enjoyment, or challenge.", kind: "intrinsic", colour: "var(--gold-deep)" },
    ],
    internalisation: {
      lede: "The same externally prompted behaviour can acquire different meanings. Internalisation is a possible process, not a guaranteed route through fixed stages.",
      branches: [
        { label: "external", quote: "I have to.", body: "The reason remains outside the self: comply with the demand or obtain the outcome.", colour: "var(--red)" },
        { label: "introjected", quote: "I would feel bad if I didn’t.", body: "The regulation is inside, but not fully owned; pressure is still doing the work.", colour: "var(--red)" },
        { label: "identified", quote: "I believe this matters.", body: "The person has accepted the value as personally important, even without enjoying the task.", colour: "var(--teal)" },
        { label: "integrated", quote: "This fits who I am.", body: "The value is coherent with other values and the self. Integrated regulation is still extrinsic.", colour: "var(--teal)" },
      ],
      note: "A regulation may be internalised at different levels depending on the person and context. Integration does not turn an extrinsic activity into intrinsic motivation.",
    },
    needs: [
      { label: "Autonomy", question: "Does this feel willingly mine?", meaning: "Volition, self-endorsement, and willingness: the action feels authored rather than compelled.", distinction: "job discretion, independence, isolation, or freedom from other people.", colour: "var(--red)" },
      { label: "Competence", question: "Can I be effective here?", meaning: "Effectance and capability experience: the person can meet a meaningful challenge and see how to act effectively.", distinction: "objective ability, credentials, or a performance score alone.", colour: "var(--teal)" },
      { label: "Relatedness", question: "Do I feel genuinely connected here?", meaning: "Belonging, care, and meaningful interpersonal connection: the person feels significant to and respected by others.", distinction: "the number of social contacts, time spent with others, or mere proximity.", colour: "var(--gold-deep)" },
    ],
    autonomyMatrix: {
      cases: [
        { label: "autonomous + interdependent", title: "I choose the team", body: "I freely choose to work closely with my team because our shared goal matters to me.", colour: "var(--teal)" },
        { label: "autonomous + independent", title: "I choose my own route", body: "I work alone because that is the approach I have willingly chosen for this task.", colour: "var(--teal)" },
        { label: "controlled + interdependent", title: "I need their approval", body: "I collaborate mainly because I fear disappointing the group or being judged by it.", colour: "var(--red)" },
        { label: "controlled + relatively independent", title: "I must prove myself", body: "I work alone, but only because I feel intense pressure to prove I can do everything myself.", colour: "var(--red)" },
      ],
      note: "Constructed examples. Autonomy concerns the source of regulation, while independence and interdependence describe a different social dimension.",
    },
    context: {
      contextItems: ["managerial behaviour", "job design", "feedback", "rewards", "participation and choice", "climate and relationships"],
      personItems: ["causality orientations", "aspirations and goals"],
      experiences: [
        { label: "need-supportive conditions", body: "The context may help people experience choice, effectiveness, and connection.", colour: "var(--teal)" },
        { label: "need-thwarting conditions", body: "The context may actively pressure, undermine, exclude, or obstruct those experiences.", colour: "var(--red)" },
      ],
      outcomes: ["need satisfaction / frustration", "motivation quality", "selected work outcomes"],
      note: "The work-context variables are conditions that may shape psychological experience; they are not themselves the three psychological needs.",
    },
    rewards: {
      reward: "£500 bonus",
      cases: [
        { label: "controlling context", quote: "Hit the target or lose the bonus.", meaning: "possible controlling significance", body: "The contingency may make the reward function as pressure, directing behaviour through an external demand. That is a theoretical possibility, not an automatic verdict.", colour: "var(--red)" },
        { label: "informational context", quote: "This bonus recognises the quality of what your team achieved.", meaning: "possible informational / competence-relevant significance", body: "The same nominal reward may communicate recognition of effectiveness when delivered in an autonomy-supportive context. Reframing alone does not guarantee this effect.", colour: "var(--teal)" },
      ],
      note: "Reward effects depend on contingency, salience, meaning, interpersonal delivery, task context, and other conditions. SDT does not teach that rewards are universally bad or harmless.",
    },
    needComparison: {
      pairs: [
        { label: "autonomy", low: "No one really asks for my input.", thwart: "I am deliberately pressured to act against what I endorse.", body: "Low support leaves the experience thin; active pressure adds a distinct thwarting quality.", colour: "var(--red)" },
        { label: "competence", low: "I rarely get useful information about how I am doing.", thwart: "I am repeatedly set up to fail and made to feel incapable.", body: "Missing guidance and active undermining are not necessarily the same experience.", colour: "var(--teal)" },
        { label: "relatedness", low: "I do not feel very connected to anyone here.", thwart: "I am deliberately excluded or treated as if I do not matter.", body: "Few connections and active rejection should not be collapsed into one score.", colour: "var(--gold-deep)" },
      ],
      note: "The satisfaction–frustration distinction is a later refinement that should be taught as related but non-identical experiences, not as one simple bipolar line.",
    },
    workModel: {
      context: ["leadership, job design, feedback, rewards", "participation, choice, climate, relationships"],
      person: ["causality orientations", "aspirations and goals"],
      needs: ["satisfaction", "frustration"],
      motivations: ["autonomous", "controlled", "amotivation"],
      outcomes: ["work attitudes", "behaviour", "performance quality / quantity", "wellness / ill-being"],
      note: "The 2017 workplace model is a general schematic. Particular studies use subsets of it, and the relationships should not be presented as equally causal or equally established.",
    },
    miniTheories: [
      { acronym: "CET", title: "Cognitive Evaluation Theory", question: "How can social-contextual events affect intrinsic motivation?", emphasis: "core", colour: "var(--red)" },
      { acronym: "OIT", title: "Organismic Integration Theory", question: "How do different forms of extrinsic regulation differ in autonomy and internalisation?", emphasis: "core", colour: "var(--teal)" },
      { acronym: "COT", title: "Causality Orientations Theory", question: "How do people differ in their general orientation toward regulating action?", emphasis: "neighbour", colour: "var(--gold-deep)" },
      { acronym: "BPNT", title: "Basic Psychological Needs Theory", question: "What are the needs for autonomy, competence, and relatedness, and how do satisfaction and frustration relate to functioning?", emphasis: "core", colour: "var(--teal)" },
      { acronym: "GCT", title: "Goal Contents Theory", question: "What are people pursuing, and how do intrinsic and extrinsic goal contents relate to wellness?", emphasis: "neighbour", colour: "var(--gold-deep)" },
      { acronym: "RMT", title: "Relationships Motivation Theory", question: "How are relatedness and close relationships developed and maintained?", emphasis: "neighbour", colour: "var(--plum-deep)" },
    ],
    scope: {
      explains: ["motivation quality", "internalisation and regulation", "autonomous versus controlled motivation", "basic psychological needs", "contextual support and thwarting", "the motivational meaning of rewards and feedback", "motivation and well-being at work"],
      stops: ["the exact emotion a person will feel", "the exact behaviour one context will produce", "a guarantee of performance from autonomy support", "a universal effect of rewards", "every organisational outcome", "one score that captures every motive"],
      note: "SDT gives a motivational map. It does not by itself specify every appraisal, emotion, attention process, cultural expression, or causal route under every workplace condition.",
    },
  },
  originsNote: "SDT is best taught here as an evolving macro-theory: intrinsic motivation and internalisation support the regulation architecture; work-motivation research applies it to organisational contexts; later work refines needs, rewards, and the wider mini-theory family.",
  origins: [
    { year: "2000", author: "Ryan &amp; Deci", work: "Self-Determination Theory and the Facilitation of Intrinsic Motivation, Social Development, and Well-Being", contribution: "A foundational account of intrinsic motivation, internalisation, the three basic needs, and social-contextual conditions." },
    { year: "2005", author: "Gagné &amp; Deci", work: "Self-Determination Theory and Work Motivation", contribution: "A work-focused account of autonomous and controlled motivation, regulation types, and internalisation in organisations." },
    { year: "2017", author: "Deci, Olafsen &amp; Ryan", work: "Self-Determination Theory in Work Organizations: The State of a Science", contribution: "A workplace synthesis connecting context, individual differences, needs, motivation quality, performance, and wellness." },
  ],
  trailLede: "The conceptual trail runs from intrinsic motivation research to internalisation, work motivation, and a broader family of connected SDT mini-theories.",
  oversimplificationsLede: "The most dangerous shortcuts turn a theory about motivational meaning into a formula.",
  oversimplifications: [
    "SDT is not <b>three needs → motivation → good outcomes</b>.",
    "Motivation is not only <b>how much effort</b> someone displays.",
    "<b>Extrinsic</b> does not automatically mean controlled.",
    "<b>Integrated regulation</b> remains extrinsic; it is not intrinsic motivation.",
    "Autonomy is <b>volition</b>, not independence, isolation, or individualism.",
    "Job autonomy, competence, and social contact are not interchangeable with psychological need experiences.",
    "Need support, need satisfaction, and active need frustration are related but distinct.",
    "Rewards do not have one universal motivational meaning.",
  ],
  qualifications: [
    "Mixed motives are common; a short statement isolates a teaching contrast rather than classifying a whole person.",
    "The regulation continuum is a relative-autonomy model, not a mandatory developmental staircase.",
    "Workplace evidence often measures subsets of the broader SDT architecture and should not be expanded into a universal causal chain.",
    "Need frustration is not simply low need satisfaction; later BPNT work treats active thwarting as conceptually distinct.",
    "Reward effects depend on functional significance and context; the record does not support a slogan that rewards are always harmful.",
    "Measurement structure, longitudinal ordering, mixed motives, cultural expression, and work-level/person-level interactions remain open areas.",
  ],
  minimumReadingLabel: "If you read five things",
  minimumReading: [
    { citation: "Ryan, R. M., &amp; Deci, E. L. (2000). Self-determination theory and the facilitation of intrinsic motivation, social development, and well-being. <i>American Psychologist, 55</i>(1), 68–78.", contribution: "Foundational distinctions among intrinsic motivation, extrinsic motivation, internalisation, and basic psychological needs.", doi: "10.1037/0003-066X.55.1.68" },
    { citation: "Gagné, M., &amp; Deci, E. L. (2005). Self-determination theory and work motivation. <i>Journal of Organizational Behavior, 26</i>(4), 331–362.", contribution: "Work motivation, regulation types, autonomous versus controlled motivation, and organisational context.", doi: "10.1002/job.322" },
    { citation: "Deci, E. L., Olafsen, A. H., &amp; Ryan, R. M. (2017). Self-determination theory in work organizations: The state of a science. <i>Annual Review of Organizational Psychology and Organizational Behavior, 4</i>, 19–43.", contribution: "The workplace SDT model, needs, motivation quality, leadership, job characteristics, rewards, performance, and wellness.", doi: "10.1146/annurev-orgpsych-032516-113108" },
    { citation: "Vansteenkiste, M., Ryan, R. M., &amp; Soenens, B. (2020). Basic psychological need theory: Advancements, critical themes, and future directions. <i>Motivation and Emotion, 44</i>, 1–31.", contribution: "Later refinement of basic psychological needs, including satisfaction and frustration.", doi: "10.1007/s11031-019-09818-1" },
    { citation: "Ryan, R. M., Duineveld, J. J., Di Domenico, S. I., Ryan, W. S., Steward, B. A., &amp; Bradshaw, E. L. (2022). We know this much is (meta-analytically) true: A meta-review of meta-analytic findings evaluating self-determination theory. <i>Psychological Bulletin, 148</i>(11–12), 813–842.", contribution: "A later evidence synthesis to consult when making broad claims about SDT evidence strength.", doi: "10.1037/bul0000385" },
  ],
  fullSources: [
    { citation: "Ryan, R. M., &amp; Deci, E. L. (2000). Self-determination theory and the facilitation of intrinsic motivation, social development, and well-being. <i>American Psychologist, 55</i>(1), 68–78.", contribution: "Foundational theory and basic needs.", doi: "10.1037/0003-066X.55.1.68" },
    { citation: "Gagné, M., &amp; Deci, E. L. (2005). Self-determination theory and work motivation. <i>Journal of Organizational Behavior, 26</i>(4), 331–362.", contribution: "Work motivation and internalisation.", doi: "10.1002/job.322" },
    { citation: "Deci, E. L., Olafsen, A. H., &amp; Ryan, R. M. (2017). Self-determination theory in work organizations: The state of a science. <i>Annual Review of Organizational Psychology and Organizational Behavior, 4</i>, 19–43.", contribution: "Workplace synthesis.", doi: "10.1146/annurev-orgpsych-032516-113108" },
    { citation: "Vansteenkiste, M., Ryan, R. M., &amp; Soenens, B. (2020). Basic psychological need theory: Advancements, critical themes, and future directions. <i>Motivation and Emotion, 44</i>, 1–31.", contribution: "Satisfaction and frustration refinement.", doi: "10.1007/s11031-019-09818-1" },
    { citation: "Ryan, R. M., Duineveld, J. J., Di Domenico, S. I., Ryan, W. S., Steward, B. A., &amp; Bradshaw, E. L. (2022). We know this much is (meta-analytically) true: A meta-review of meta-analytic findings evaluating self-determination theory. <i>Psychological Bulletin, 148</i>(11–12), 813–842.", contribution: "Later evidence synthesis; used cautiously for evidence-strength framing.", doi: "10.1037/bul0000385" },
  ],
  relatedToLede: "SDT is a motivational lens adjacent to several existing Concept Lab records, but it is not interchangeable with any of them.",
  relatedTo: [
    { recordId: "job-demands-resources", relation: "offers a motivational mechanism adjacent to", body: "Job Demands–Resources organises demands, resources, strain, and motivation. SDT helps ask how a context is experienced through needs and what kind of motivation it supports." },
    { recordId: "person-environment-fit", relation: "provides a different level of explanation from", body: "Person–Environment Fit concerns correspondence between person and environment. SDT concerns psychological need experience and motivation quality; needs–supplies fit is not identical to need satisfaction." },
    { recordId: "workplace-design", relation: "helps interpret how contextual conditions may become", body: "Workplace design supplies features of the setting. SDT provides a motivational lens for asking when those features support or thwart autonomy, competence, or relatedness." },
    { recordId: "affective-events-theory", relation: "provides a different level of explanation from", body: "AET focuses on affective episodes, events, attitudes, behaviour, and time. SDT focuses on motivational quality, needs, and internalisation. Their intersection is a proposed connection, not an equivalence." },
  ],
  provenance: [
    { glyph: "●", colour: "var(--red)", label: "Source-grounded theory", note: "The regulation architecture, internalisation logic, basic needs, reward distinctions, and workplace model are grounded primarily in Ryan & Deci (2000), Gagné & Deci (2005), and Deci, Olafsen & Ryan (2017), with BPNT refinement identified separately." },
    { glyph: "■", colour: "var(--teal)", label: "Faithful explanation", note: "Plain-language explanations preserve the distinctions among motivation amount and quality, intrinsic and extrinsic motivation, autonomous and controlled motivation, need support, satisfaction, and frustration." },
    { glyph: "▲", colour: "var(--red)", label: "Teaching construction", note: "The opening employees, motive statements, autonomy matrix, and reward scenarios are constructed examples. They are not reported cases, measurements, or predictions." },
    { glyph: "✦", colour: "var(--pen-3)", label: "Concept Lab synthesis", note: "The section order, branched workplace map, mini-theory constellation, comparison forms, and links to neighbouring records are editorial teaching arrangements built from the cited literature." },
    { glyph: "?", colour: "var(--pen-3)", label: "Open boundary", note: "Mixed motives, measurement structure, need frustration, reward contexts, longitudinal causal ordering, cultural expression, and person-level/work-level interactions remain under-specified or actively researched." },
  ],
};
