import type { TheoryRecord } from "./types";

export const socialExchangeTheory: TheoryRecord = {
  id: "social-exchange-theory",
  kind: "theory",
  slug: "social-exchange-theory",
  title: "Social Exchange Theory",
  hook: "When one actor does something for another, what makes what happens next an exchange?",
  oneSentence: "Social Exchange Theory explains social action through exchanged resources, rules of response, dependence, and relationships that develop across subsequent exchanges.",
  discipline: "ob",
  topics: ["social exchange", "reciprocity", "interdependence", "power and dependence", "workplace relationships"],
  facts: ["exchange ≠ every interaction", "3 reciprocity meanings", "dependence is relational", "resources carry meaning", "theory family"],
  statusChip: "theory family",
  provenance: [
    { glyph: "●", colour: "var(--red)", label: "Foundational propositions", note: "Homans, Gouldner, Blau, and Emerson supply the foundational exchange, reciprocity, and power–dependence propositions." },
    { glyph: "■", colour: "var(--teal)", label: "Integrative review", note: "Cropanzano and Mitchell organise the contemporary SET conversation around rules, resources, relationships, and exchange forms." },
    { glyph: "▲", colour: "var(--gold-deep)", label: "Later refinements", note: "Lawler, Molm, and Cropanzano and colleagues extend the record toward emotion, exchange structures, and response activity." },
    { glyph: "✦", colour: "var(--plum-deep)", label: "Concept Lab synthesis", note: "The social–economic comparison and teaching maps are labelled syntheses, not official SET taxonomies." },
  ],
  origins: [
    { year: "1958", author: "George C. Homans", work: "Social Behavior as Exchange", contribution: "Places exchange at the centre of social behaviour: actions can be understood through rewards, costs, and responses between actors." },
    { year: "1960", author: "Alvin W. Gouldner", work: "The Norm of Reciprocity", contribution: "Establishes reciprocity as a social norm. Gouldner does not supply the later three-part taxonomy often attached to SET." },
    { year: "1962", author: "Richard M. Emerson", work: "Power-Dependence Relations", contribution: "Makes power relational: dependence on a partner rises with motivational investment and falls as alternative sources become available." },
    { year: "1964", author: "Peter M. Blau", work: "Exchange and Power in Social Life", contribution: "Develops social exchange as a route into attraction, trust, obligation, and power in social life." },
    { year: "2005", author: "Russell Cropanzano & Marie S. Mitchell", work: "Social Exchange Theory: An Interdisciplinary Review", contribution: "Integrates the modern conversation around exchange rules, resources, relationships, and the different traditions called SET." },
    { year: "2017", author: "Russell Cropanzano et al.", work: "The Management of Organizational Behavior", contribution: "Revisits activity and hedonic value, helping prevent positive/negative exchange from being mistaken for a complete response model." },
  ],
  trailLede: "SET is not one sealed diagram. It is a family of exchange traditions that share a concern with interdependence but differ in what they foreground: rewards and costs, norms, resources, power, relationships, emotion, and exchange structure.",
  oversimplificationsLede: "The shortcuts below are attractive because they make exchange look tidy. They are also where a useful framework becomes a false formula.",
  oversimplifications: [
    "A favour is not automatically an exchange: the other actor, resource, rule, and response expectation still need to be specified.",
    "Gouldner (1960) is the foundational norm-of-reciprocity source, not the source of a later three-part reciprocity taxonomy.",
    "Reciprocity can describe an interdependent exchange, a folk belief, or a moral norm; those are related but not interchangeable meanings.",
    "Dependence is not a trait or a score. It is a relation between a valued outcome, a partner, and alternative sources.",
    "Balanced power does not tell you whether mutual dependence is high or low.",
    "Social exchange is not simply non-money exchange, and economic exchange is not simply immoral or impersonal.",
    "A constraint can redirect or reduce a response without reversing the actor's hedonic direction.",
    "Positive and negative value do not by themselves specify whether an actor is active, withholding, or doing something else.",
    "One supportive act does not prove a relationship, and one disappointing act does not prove exploitation.",
    "SET does not predict a single inevitable next move from a resource or a favour.",
  ],
  qualifications: [
    "Different SET traditions use overlapping words for different units of analysis; always state whether the claim concerns an act, exchange, relationship, network, or institution.",
    "Power–dependence language can describe a relation without establishing motive, fairness, trust, or emotion.",
    "Exchange forms and relationship outcomes depend on timing, history, norms, alternatives, and the meanings actors attach to resources.",
    "The social–economic comparison on this page is a Concept Lab teaching synthesis across dimensions, not a canonical seven-dimension taxonomy.",
    "The response and emotion refinements remain theoretically useful without becoming a deterministic prediction rule.",
  ],
  minimumReadingLabel: "If you read seven things",
  minimumReading: [
    { citation: "Homans, G. C. (1958). Social behavior as exchange.", contribution: "A foundational behavioural exchange statement.", doi: "10.1086/222355" },
    { citation: "Gouldner, A. W. (1960). The norm of reciprocity.", contribution: "The foundational statement of reciprocity as a social norm.", doi: "10.2307/2092623" },
    { citation: "Emerson, R. M. (1962). Power-dependence relations.", contribution: "The relational power and dependence model.", doi: "10.2307/2089716" },
    { citation: "Blau, P. M. (1964). Exchange and power in social life.", contribution: "A major social exchange and power treatment." },
    { citation: "Cropanzano, R., & Mitchell, M. S. (2005). Social exchange theory: An interdisciplinary review.", contribution: "The essential integrative review of rules, resources, and relationships.", doi: "10.1177/0149206305279602" },
    { citation: "Lawler, E. J. (2001). An affect theory of social exchange.", contribution: "Connects exchange structure to global feelings and relationship development.", doi: "10.1086/324071" },
    { citation: "Cropanzano, R., Anthony, E. L., Daniels, S. R., & Hall, A. V. (2017). Social exchange theory: A critical review with theoretical remedies.", contribution: "Clarifies activity, hedonic value, and the limits of simple positive/negative exchange stories.", doi: "10.5465/annals.2015.0099" },
  ],
  fullSources: [
    { citation: "Foa, U. G., & Foa, E. B. (1974). Societal structures of the mind: A classificatory theory for the interpretation of persons and actions.", contribution: "Resource theory: love, status, information, money, goods, and services." },
    { citation: "Emerson, R. M. (1976). Social exchange theory.", contribution: "A later overview of exchange networks and power dependence.", doi: "10.1146/annurev.so.02.080176.002003" },
    { citation: "Molm, L. D., Collett, J. L., & Schaefer, D. R. (2007). Building solidarity through generalized exchange.", contribution: "Distinguishes reciprocal, negotiated, and generalized exchange forms.", doi: "10.1086/517900" },
    { citation: "Shore, L. M., Tetrick, L. E., Lynch, P., & Barksdale, K. (2006). Social and economic exchange: Construct development and validation.", contribution: "Develops measures for social and economic exchange in organisational relationships.", doi: "10.1111/j.0021-9029.2006.00046.x" },
    { citation: "Cropanzano, R., & Mitchell, M. S. (2005). Social exchange theory: An interdisciplinary review.", contribution: "Integrative reference for the record's classification decisions.", doi: "10.1177/0149206305279602" },
  ],
  relatedToLede: "SET sits beside records that explain affective consequences, motivation, and the fit between a person and a work setting. The links are neighbouring lenses, not substitute evidence.",
  relatedTo: [
    { recordId: "affective-events-theory", relation: "adds affective timing", body: "AET asks how events become changing affect and attitudes; SET helps specify the exchange and relationship context those events can carry." },
    { recordId: "self-determination-theory", relation: "adds motivational meaning", body: "SDT asks what kind of motivation is moving action; SET asks what is exchanged, expected, and made possible between actors." },
    { recordId: "person-environment-fit", relation: "adds correspondence", body: "Person–Environment Fit asks whether person and setting characteristics correspond; SET asks how interdependence develops within social relations." },
    { recordId: "job-demands-resources", relation: "adds work design context", body: "JD–R maps demands and resources in work; SET can illuminate how resources are provided, reciprocated, and made relational." },
    { recordId: "workplace-design", relation: "adds designed conditions", body: "Workplace Design focuses on designed work conditions; SET follows the exchange meanings and obligations that can develop around them." },
  ],
  set: {
    opening: {
      cases: [
        { label: "Actor A acts", quote: "I covered your shift when you were stuck.", body: "A resource moved between actors. That is a starting point, not yet a complete explanation of what the act means or what happens next." },
        { label: "Actor B responds", quote: "I’ll make sure you are not left carrying the next one alone.", body: "The response may be direct, delayed, indirect, symbolic, withheld, or constrained. SET asks which exchange rule makes the response intelligible." },
        { label: "The relation changes", quote: "Now we know what we can count on from each other.", body: "Repeated exchanges can produce trust, obligation, attraction, solidarity, or a revised dependence relation. A transaction and a relationship are not the same unit." },
      ],
      note: "Constructed workplace examples. They illustrate the problem space; they are not reported cases or evidence of a universal response.",
    },
    reciprocity: [
      { label: "Interdependent exchange", short: "A ↔ B", body: "Each actor’s outcome depends in part on the other’s action. The emphasis is on contingent interdependence: what one does changes what the other can receive or do next." },
      { label: "Folk belief", short: "give ↔ return", body: "A culturally available expectation that benefits, harms, or favours should be answered in kind. It describes how people understand an exchange, not necessarily a moral command." },
      { label: "Moral norm", short: "ought to return", body: "A norm that makes returning benefits feel obligatory. The obligation can be strong even when actors do not negotiate a precise equivalence." },
    ],
    resources: [
      { label: "Love", body: "Care, affection, and concern that signal regard and connection." },
      { label: "Status", body: "Recognition, esteem, standing, and signs that an actor matters." },
      { label: "Information", body: "Advice, knowledge, explanation, access, and uncertainty reduction." },
      { label: "Money", body: "A generalised medium of exchange whose meaning depends on the arrangement." },
      { label: "Goods", body: "Tangible objects, materials, equipment, or other transferable things." },
      { label: "Services", body: "Time, labour, assistance, access, and acts performed for another." },
    ],
    rules: [
      { label: "Direct reciprocity", rule: "A gives to B; B returns to A", body: "The original giver and responder are the same pair. Timing and equivalence can still be open, negotiated, or normatively understood." },
      { label: "Generalised reciprocity", rule: "A gives to B; the system returns later", body: "A benefit can circulate through a group or network without an immediate return from the original recipient." },
      { label: "Negotiated exchange", rule: "A and B agree the terms", body: "The terms of the exchange are jointly arranged. Agreement does not make the relationship permanently economic or eliminate dependence." },
      { label: "No automatic return", rule: "a benefit can be accepted, refused, delayed, or answered differently", body: "The absence of an expected return is itself data about the rule, history, power, or meaning in the relation; it is not a proof of one motive." },
    ],
    dimensions: [
      { label: "Obligation specificity", body: "Is the expected return precise, or is a general sense of owing enough?" },
      { label: "Explicitness", body: "Are terms stated, or are they inferred from norms, history, and context?" },
      { label: "Monitoring", body: "How visible, recorded, or enforceable is the response?" },
      { label: "Timing", body: "Is response immediate, scheduled, open-ended, or deliberately delayed?" },
      { label: "Relational openness", body: "Does the exchange invite a continuing relation or close after the transaction?" },
      { label: "Uncertainty", body: "How much does each actor have to trust the other to respond later?" },
      { label: "Contextual meaning", body: "What does the resource signal here: care, status, compliance, price, access, or something else?" },
    ],
    power: {
      values: ["low value", "moderate value", "high value"],
      alternatives: ["many alternatives", "some alternatives", "few alternatives"],
      note: "Teaching conditions, not a psychometric scale. Dependence rises when a valued outcome is mediated by a partner and alternatives are scarce; power is the relational asymmetry that follows.",
    },
    relationshipStages: [
      { label: "resource moves", body: "A resource, service, signal, or opportunity passes between actors." },
      { label: "meaning is read", body: "The recipient interprets what the act means in this context and history." },
      { label: "response is possible", body: "The actor can return, delay, generalise, negotiate, withhold, or redirect the response." },
      { label: "dependence shifts", body: "Alternatives, investments, and access can change each actor’s leverage." },
      { label: "relationship feedback", body: "The exchange can alter trust, obligation, solidarity, attraction, or the willingness to exchange again." },
    ],
    hedonic: [
      { label: "positive + active", body: "An actor can experience a benefit and engage in a response that sustains or develops the exchange.", colour: "var(--teal)" },
      { label: "positive + withhold", body: "A valued outcome does not force visible activity; the actor may accept a benefit and not respond in the expected way.", colour: "var(--gold-deep)" },
      { label: "negative + active", body: "A costly or harmful exchange can prompt action, repair, protest, exit, or retaliation depending on meaning and constraint.", colour: "var(--red)" },
      { label: "negative + withhold", body: "An actor may reduce participation, pause, avoid, or remain inactive without that response becoming a simple opposite of positive action.", colour: "var(--plum-deep)" },
    ],
    constraints: [
      { desired: "Desired response", constrained: "Actively return the favour", body: "The actor values reciprocating, but resources, role rules, dependence, time, risk, or limited alternatives can make the preferred response unavailable." },
      { desired: "Constrained response", constrained: "Acknowledge, delay, redirect, or protect the relation", body: "The response may preserve trust or avoid escalation without being the direct return the actor wanted to make. A constraint can reduce or redirect activity while the hedonic direction remains positive." },
      { desired: "Negative exchange", constrained: "Repair, protest, exit, or withhold", body: "A negative experience can move the actor toward several responses. Later work treats activity and hedonic value as separable dimensions rather than a single positive/negative line." },
    ],
    chain: [
      { label: "What happened?", body: "Identify the resource, actors, timing, and immediate outcome." },
      { label: "What rule is operating?", body: "Ask whether the exchange is direct, generalised, negotiated, norm-led, or mixed." },
      { label: "Who needs whom?", body: "Locate investments, alternatives, and the current balance of dependence." },
      { label: "What response is possible?", body: "Separate desired response from feasible response under constraints." },
      { label: "What changes next?", body: "Track how the exchange feeds back into relationship, trust, obligation, and subsequent exchange." },
    ],
    audit: [
      { label: "Shortcut claim", claim: "Supervisor support predicts helping; therefore this is SET.", answers: ["What resource moved?", "What actors are interdependent?", "Which rule or obligation makes a response intelligible?", "What alternative explanation or dependence relation is specified?"], verdict: "Incomplete: a relationship or resource is named, but the exchange structure and response rule are not yet shown." },
      { label: "Constructed exchange claim", claim: "A manager gives schedule flexibility; the employee later helps a colleague because support has created an obligation within a continuing relationship.", answers: ["Resource: schedule flexibility and assistance", "Rule: a norm-led, direct or generalised return", "Relation: the employee and work group remain interdependent", "Outcome: helping is possible, not guaranteed; constraints and alternatives remain relevant"], verdict: "More SET-ready: the resource, rule, relation, possible response, and limits are visible. It is still a theoretical reading, not evidence by itself." },
    ],
    family: [
      { label: "behavioural exchange", kind: "root", body: "Rewards, costs, and responses between actors." },
      { label: "norm of reciprocity", kind: "branch", body: "Why a benefit can create an expectation or moral pressure to return." },
      { label: "social resources", kind: "branch", body: "What moves between people: love, status, information, money, goods, and services." },
      { label: "power–dependence", kind: "branch", body: "How alternatives and motivational investments distribute relational power." },
      { label: "exchange structures", kind: "branch", body: "How direct, negotiated, reciprocal, and generalized exchange differ." },
      { label: "affect and relationship", kind: "branch", body: "How exchange can produce feelings and feed back into ties." },
      { label: "integrative remedies", kind: "remedy", body: "Later reviews address ambiguity, overlapping constructs, activity, hedonic value, and the risks of flat prediction." },
      { label: "SET", kind: "synthesis", body: "A family resemblance, not one mandatory causal sequence." },
    ],
    scope: {
      explains: ["why a benefit can carry an obligation", "how resources and rules make an interaction an exchange", "why power depends on alternatives and valued outcomes", "how exchange can feed back into relationships", "why similar acts can carry different meanings in different relations"],
      stops: ["predicting a single response from a favour", "treating dependence as a stable personality trait", "deciding fairness without actors’ meanings and terms", "turning social/economic comparison into a moral binary", "proving a causal exchange process from a correlation alone"],
      note: "SET is a family of lenses for interdependence and exchange. It does not replace theories of motivation, emotion, identity, justice, culture, or institutional power; it often needs them beside it.",
    },
  },
};
