import type { Metadata } from "next";
import Link from "next/link";
import { tonalHierarchy } from "@/content/tonal-hierarchy";
import { huronsItpraTheory } from "@/content/hurons-itpra-theory-of-expectation";
import { ipa } from "@/content/ipa";
import { TonalEncounter } from "../_components/TonalEncounter";
import { AppraisalTrace } from "../_components/AppraisalTrace";
import { OutcomeHinge } from "../_components/OutcomeHinge";
import { Contents } from "../_components/Contents";
import { SectionLead, OperationMeaning, Note } from "../_components/Type";
import { Intervention } from "../_components/Pigment";

export const metadata: Metadata = { title: "Material with meaning · B2 prototype" };
const contents = [{ id: "context", title: "Hold / change" }, { id: "coexistence", title: "Coexist" }, { id: "retention", title: "Retain" }, { id: "attribution", title: "Attribute" }];
export default function MaterialPage() {
  return <main id="b2-main" className="b2-main b2-material-page"><header className="b2-title-block"><p className="b2-eyebrow">Material inquiry · Four operations in real knowledge</p><h1>No mark<br /><em>without a difference.</em></h1><div className="b2-title-aside"><Intervention tone="vermilion">What does the mark do?</Intervention><p>Read the relation.<br />Then inspect the mark.</p></div><p className="b2-intro">A small material vocabulary, tested against actual conceptual work. Type carries the claim. Pigment makes a relationship available to attention.</p></header><Contents items={contents} />
    <section id="context" className="b2-section"><SectionLead n="01" title="Hold an object. Change its relation."><p>Tonal Hierarchy: C4 is physically identical; a preceding context gives it a different role.</p></SectionLead><TonalEncounter contexts={tonalHierarchy.tonal!.sameNote.contexts} compact /><OperationMeaning meaning="The pigment differentiates the selected tonal context around the fixed C4 anchor." not="A change in pitch, a fit score, a probability, or evidence strength." equivalent="C4 is tonic in C major, dominant in F major, a tonic-triad member in A minor and chromatic in D major." /><Link className="b2-read-more" href="/b2-lab/tonal-hierarchy">Read the Tonal Hierarchy prototype ↗</Link></section>
    <section id="coexistence" className="b2-section"><SectionLead n="02" title="Make room for two questions at once."><p>ITPRA: one outcome, parallel post-onset responses. Neither must wait for the other to finish.</p></SectionLead><OutcomeHinge windows={huronsItpraTheory.huron!.timeline.windows} /><OperationMeaning meaning="Prediction and Reaction have separate named regions at the same post-onset reference." not="Successive stages, measured response windows, or five verified biological modules." equivalent="Prediction evaluates the earlier forecast. Reaction concerns an immediate functional response. They can begin together after outcome onset." /></section>
    <section id="retention" className="b2-section"><SectionLead n="03" title="A later reading need not erase the earlier response."><p>ITPRA supplies a specific, local justification for retaining a trace.</p></SectionLead><AppraisalTrace compact /><OperationMeaning meaning="The earlier response stays legible while a possible later appraisal is inspected." not="The earlier response becoming less true, weaker evidence, or an emotional trace recorded from a person." equivalent="Later Appraisal can confirm, revise or reverse an interpretation without erasing earlier Prediction and Reaction." /><Link className="b2-read-more" href="/b2-lab/itpra">Read the ITPRA prototype ↗</Link></section>
    <section id="attribution" className="b2-section b2-quiet"><SectionLead n="04" title="Give the intervention an author."><p>IPA: a paraphrase and an editorial question have different responsibilities.</p></SectionLead><div className="b2-attribution-example"><p className="b2-paraphrase">{ipa.doubleHermeneutic!.quote}</p><Note glyph="■">Compressed paraphrase of Smith (2019), inherited from the canonical method record. Not a quotation.</Note><div className="b2-attribution-margin"><Intervention tone="emerald">Whose interpretation?</Intervention><Note>Concept Lab editorial intervention: inspect how the researcher’s reading remains tied to the participant’s account.</Note></div></div><OperationMeaning meaning="The handwritten question calls attention to responsibility for interpretation. The note explicitly attributes the intervention." not="Handwriting as the voice of a participant, a source quotation, or a new provenance code." equivalent="Smith’s methodological account is paraphrased. Concept Lab adds a question about the researcher’s interpretative responsibility." /><p className="b2-citation">Smith, J. A. (2019). Participants and researchers searching for meaning: Conceptual developments for interpretative phenomenological analysis. <em>Qualitative Research in Psychology, 16</em>(2), 166–181.</p><Link className="b2-read-more" href="/b2-lab/ipa">Read the IPA prototype ↗</Link></section>
    <div className="b2-material-closing"><h2>The marks do not rank the knowledge.</h2><p>● ■ ▲ ✦ ? retain their explicit provenance notes. Colour, hatching and pressure carry no global measure of certainty, correctness, effect size or evidence. A reader can understand every relationship here from its text.</p><p>Partial boundaries and accumulated evidence hatching are not used in this experiment. Retention appears only where the account contains a real relationship to an earlier response.</p></div>
  </main>;
}
