import type { Metadata } from "next";
import Image from "next/image";
import { affectiveEventsTheory as rec } from "../../content/affective-events-theory";
import AETRebuildInteractive, { AETMapSection } from "./_components/AETRebuildInteractive";

export const metadata: Metadata = {
  title: "Affective Events Theory · a day made of events",
  description: rec.oneSentence,
  robots: { index: false, follow: false },
};

function Rich({ html }: { html: string }) { return <span dangerouslySetInnerHTML={{ __html: html }} />; }
function Kicker({ number, children }: { number: string; children: React.ReactNode }) { return <p className="aetr-kicker"><span>{number}</span><span>{children}</span></p>; }
function Heading({ id, children }: { id: string; children: React.ReactNode }) { return <h2 id={id} className="aetr-section-title">{children}</h2>; }

export default function AETRebuildPage() {
  return (
    <div className="aetr-page">
      <div className="aetr-breadcrumb"><a href="/concept-lab">Theories</a><span>/</span><a href="/concept-lab/library">Organisational Behaviour</a><span>/</span><b>Affective Events Theory</b></div>

      <section className="aetr-hero" aria-labelledby="aetr-title">
        <div className="aetr-hero-copy"><Kicker number="01">A DAY MADE OF EVENTS / ORGANISATIONAL BEHAVIOUR</Kicker><h1 id="aetr-title">Two truths<br /><em>at once.</em></h1><div className="aetr-truths" aria-label="The central Affective Events Theory paradox"><p>“I like my job.”</p><p>“I’m furious at 10:43.”</p></div><p className="aetr-hero-lede"><Rich html={rec.ideaLede ?? rec.oneSentence} /></p><p className="aetr-pencil">the job can stay · the moment can turn</p><a className="aetr-enter" href="#aetr-stable"><span aria-hidden="true">↘</span>Enter the workday</a></div>
        <figure className="aetr-hero-art"><div className="aetr-hero-image"><Image src="/aet-rebuild-assets/aet-workday-field.png" alt="A coloured-pencil workplace field with a person at a desk and quiet spaces around the working day." width={2048} height={1152} priority unoptimized /><svg viewBox="0 0 900 520" aria-hidden="true"><path d="M40 380C190 320 296 394 405 337s169-50 258-3 164 37 196-16" className="hero-trace hero-trace-blue" /><path d="M92 105C205 140 302 115 385 171s149 25 236-27 170 1 224 27" className="hero-trace hero-trace-gold" /><circle cx="461" cy="254" r="16" className="hero-puncture" /><circle cx="461" cy="254" r="44" className="hero-ring" /></svg><span className="hero-note hero-note-one">the workday stays<br />recognisable</span><span className="hero-note hero-note-two">an event lands</span><span className="hero-note hero-note-three">time leaves a trace</span></div><figcaption><b>Teaching world.</b> A constructed workplace, not a reported case. The scene gives the reader somewhere to notice change.</figcaption></figure>
      </section>

      <nav className="aetr-contents" aria-label="On this page"><span>read the record</span>{[["aetr-stable", "Job / event"], ["aetr-event-field", "An event"], ["aetr-reaction-field", "Same event"], ["aetr-route-field", "Two clocks"], ["aetr-time-field", "By 4:32"], ["aetr-feeling", "Feeling / evaluation"], ["aetr-map-field", "Map / beneath"], ["aetr-scholarship", "Evidence"], ["aetr-open", "Where it stops"]].map(([id, label], index) => <a href={`#${id}`} key={id}><small>{String(index + 2).padStart(2, "0")}</small>{label}</a>)}</nav>

      <section className="aetr-section aetr-stable-section" id="aetr-stable" aria-labelledby="aetr-stable-title">
        <div className="aetr-section-lede"><Kicker number="02">THE JOB STAYS. THE DAY DOESN’T.</Kicker><Heading id="aetr-stable-title">Feature or event?<br /><em>Start with the difference.</em></Heading><p>Work-environment features are relatively enduring aspects of a setting. Work events are occurrences or changes that become affectively significant within that setting.</p><p className="aetr-pencil">a room is not a moment · a moment interrupts the room</p></div>
        <div className="aetr-feature-event-field"><div className="aetr-stable-column"><span className="aetr-field-label">relatively enduring</span><h3>Work-environment features</h3><p>autonomy · support · participation · overload</p><div className="aetr-stable-lines" aria-hidden="true"><span /><span /><span /><span /></div></div><div className="aetr-turn-column"><span className="aetr-field-label">a change within it</span><h3>Work events</h3><p>criticism · praise · escalation · cancelled meeting</p><div className="aetr-turn-mark" aria-hidden="true">↗</div></div><aside className="aetr-teaching-note"><b>Editorial examples.</b> These scenarios teach the distinction. They are not reported cases or evidence that one event produces one emotion.</aside></div>
        <div className="aetr-classification-list" aria-label="Canonical feature and event examples">{(rec.classification?.items ?? []).slice(0, 6).map((item) => <article key={item.scenario}><span className={item.answer === "event" ? "classification-event" : "classification-feature"}>{item.answer}</span><div><b>{item.scenario}</b><p>{item.explanation}</p></div></article>)}</div>
      </section>

      <AETRebuildInteractive />

      <section className="aetr-section aetr-feeling-section" id="aetr-feeling" aria-labelledby="aetr-feeling-title">
        <div className="aetr-section-lede"><Kicker number="07">DO NOT FLATTEN THE TERMS</Kicker><Heading id="aetr-feeling-title">Feeling is not<br /><em>evaluation.</em></Heading><p>{rec.conceptComparison?.lede}</p><p className="aetr-pencil">brief mark · diffuse field · settled structure</p></div>
        <div className="aetr-material-compare"><article className="material-emotion"><span className="material-mark mark-coral" aria-hidden="true" /> <p className="aetr-field-label">right now</p><h3>Emotion</h3><p>A defined affective episode or reaction. It can arrive quickly and change within a workday.</p></article><article className="material-mood"><span className="material-cloud" aria-hidden="true" /><p className="aetr-field-label">across a stretch</p><h3>Mood</h3><p>A more diffuse affective state. It is related to emotion but should not be treated as the same construct.</p></article><article className="material-attitude"><span className="material-frame" aria-hidden="true" /><p className="aetr-field-label">about the job</p><h3>Job satisfaction</h3><p>An evaluative work attitude. It can reflect affective experience and beliefs, but it is not a mood score.</p></article></div>
        <p className="aetr-caption"><b>■ Faithful explanation.</b> These are teaching geometries for keeping constructs apart, not empirical measurements of size, persistence, or intensity.</p>
      </section>

      <AETMapSection />

      <section className="aetr-section aetr-contribution-section" id="aetr-contribution" aria-labelledby="aetr-contribution-title"><div className="aetr-section-lede"><Kicker number="10">WHAT AET CHANGED</Kicker><Heading id="aetr-contribution-title">The job is not<br /><em>the only unit of attention.</em></Heading></div><div className="aetr-contribution-body"><p className="aetr-big-claim">Events made time visible.</p><p>AET redirected organisational behaviour toward specific work events, within-person fluctuation, temporal affective experience, the distinction between affective reactions and work attitudes, and multiple routes from affect or evaluation toward behaviour.</p><div className="aetr-contribution-notes"><span>episodes</span><span>within-person change</span><span>attitudes ≠ moods</span><span>time as part of the theory</span></div><p className="aetr-caption"><b>● Source-grounded theory.</b> Weiss &amp; Cropanzano (1996), with the authorial clarification in Weiss &amp; Beal (2005).</p></div></section>

      <section className="aetr-scholarship" id="aetr-scholarship" aria-labelledby="aetr-scholarship-title"><div className="aetr-section-lede"><Kicker number="09">QUIET SCHOLARSHIP / WHAT HELD UP?</Kicker><Heading id="aetr-scholarship-title">The map kept<br /><em>moving.</em></Heading><p>{rec.trailLede}</p></div><div className="aetr-scholarship-body"><div className="aetr-trail-list">{rec.origins.slice(0, 6).map((origin, index) => <article key={`${origin.year}-${origin.author}`}><span className="aetr-trail-year">{origin.year}</span><div><h3><Rich html={origin.author} /></h3><p className="aetr-trail-work"><Rich html={origin.work} /></p><p>{origin.contribution}</p></div><span className="aetr-trail-index">0{index + 1}</span></article>)}</div><div className="aetr-later-evidence"><p className="aetr-field-label">later evidence · read with restraint</p><article><b>2017 · Velasco, Navarro &amp; Rueff-Lopes</b><p>Review evidence is strongest around the relationship between events, affect, and attitudes.</p></article><article><b>2024 · Williams et al.</b><p>A meta-analysis of discrete emotions shows that specific emotions do not all relate to job satisfaction in the same way; positive/negative aggregation can hide differences.</p></article><article><b>2026 · Aitken et al.</b><p>A within-person meta-analysis links affect to task performance, OCB, and CWB, while effects are mostly small to modest and explain only a small fraction of performance variance.</p></article><p className="aetr-caption"><b>Evidence boundary.</b> These later summaries are named literature touchpoints supplied for this rebuild; they are not treated as a giant arrow or a universal effect.</p></div></div></section>

      <section className="aetr-section aetr-open-section" id="aetr-open" aria-labelledby="aetr-open-title"><div className="aetr-section-lede"><Kicker number="11">WHERE THE MAP STOPS</Kicker><Heading id="aetr-open-title">A boundary is useful<br /><em>information.</em></Heading><p>{rec.scopeMap?.lede}</p></div><div className="aetr-open-field"><p className="aetr-open-question">What remains under-specified?</p><ul>{["Why does this event produce this specific emotion?", "How exactly are events appraised?", "When does affect become behaviour — and when does it dissipate?", "How do event histories accumulate into broader attitudes?", "How should time be sampled and measured?"].map((item) => <li key={item}>{item}</li>)}</ul><p className="aetr-pencil">? the map stops where the evidence stops</p></div></section>

      <section className="aetr-sources" id="aetr-sources" aria-labelledby="aetr-sources-title"><div className="aetr-section-lede"><Kicker number="12">CLAIMS / SOURCES / PROVENANCE</Kicker><Heading id="aetr-sources-title">Keep the marks<br /><em>attached to the claims.</em></Heading><p>Academic meaning stays live and traceable. The drawings make relationships easier to see; the sources support what can be claimed.</p></div><div className="aetr-source-columns"><ol className="aetr-source-list">{rec.minimumReading.map((source, index) => <li key={source.citation}><span>0{index + 1}</span><div><p><Rich html={source.citation} /></p><small>{source.contribution}</small>{source.doi && <a href={`https://doi.org/${source.doi}`}>doi ↗</a>}</div></li>)}</ol><ul className="aetr-provenance-list">{rec.provenance.map((item) => <li key={item.label}><span style={{ color: item.colour }}>{item.glyph}</span><div><strong>{item.label}</strong><p>{item.note}</p></div></li>)}</ul></div></section>

      <section className="aetr-back"><a href="/concept-lab/library">← Return to the atlas</a><span>Affective Events Theory · complete experience rebuild · isolated for review</span></section>
    </div>
  );
}
