import Image from "next/image";
import { affectiveEventsTheory as rec } from "../../../content/affective-events-theory";
import AETVisualRebuildInteractive from "./AETVisualRebuildInteractive";
import AETIllustratedMacrostructure, { AETRelationshipLedger } from "./AETIllustratedMacrostructure";

function Rich({ html }: { html: string }) { return <span dangerouslySetInnerHTML={{ __html: html }} />; }
function Kicker({ number, children }: { number: string; children: React.ReactNode }) { return <p className="aev-kicker"><span>{number}</span><span>{children}</span></p>; }
function Heading({ id, children }: { id: string; children: React.ReactNode }) { return <h2 id={id} className="aev-section-title">{children}</h2>; }

export default function AETExperience({ variant = "target" }: { variant?: "target" | "canonical" }) {
  return <div className="aev-page">
    <div className="aev-breadcrumb"><a href="/concept-lab">Theories</a><span>/</span><a href="/concept-lab/library">Organisational Behaviour</a><span>/</span><b>Affective Events Theory</b></div>

    <section className="aev-hero" aria-labelledby="aev-title">
      <div className="aev-hero-art" aria-hidden="true"><Image src="/aet-visual-rebuild-assets/aet-opening-workplace.png" alt="" width={2048} height={1152} priority unoptimized /><span className="aev-hero-pencil hero-pencil-one">the workplace remains</span><span className="aev-hero-pencil hero-pencil-two">10:43 · an event lands</span><span className="aev-hero-puncture" /></div>
      <div className="aev-hero-copy"><Kicker number="01">A DAY MADE OF EVENTS / ORGANISATIONAL BEHAVIOUR</Kicker><h1 id="aev-title">Two truths<br /><em>at once.</em></h1><p className="aev-hero-truth"><span>“I like my job.”</span><span>“I’m furious at 10:43.”</span></p><p className="aev-hero-lede"><Rich html={rec.ideaLede ?? rec.oneSentence} /></p><p className="aev-hand">the job can stay · the moment can turn</p><a className="aev-enter" href="#aev-stable"><span aria-hidden="true">↘</span>Enter the workday</a></div>
      <aside className="aev-hero-side"><span>FEATURE</span><b>condition</b><span>EVENT</span><b>occurrence</b><p>One working field.<br />Many affective moments.</p></aside>
    </section>

    <nav className="aev-contents" aria-label="On this page"><span>read the record</span>{[["aev-stable","feature / event"],["aev-reaction","same event"],["aev-clocks","two clocks"],["aev-workday","workday remembers"],["aev-distinction","feeling / evaluation"],["aev-map","map / beneath"],["aev-scholarship","evidence"],["aev-open","where it stops"]].map(([id,label],i)=><a href={`#${id}`} key={id}><small>{String(i+2).padStart(2,"0")}</small>{label}</a>)}</nav>

    <section className="aev-stable" id="aev-stable" aria-labelledby="aev-stable-title">
      <div className="aev-stable-intro"><Kicker number="02">THE JOB STAYS. THE DAY DOESN’T.</Kicker><Heading id="aev-stable-title">A feature is a condition.<br /><em>An event is an occurrence.</em></Heading><p>{rec.classification?.note}</p><p className="aev-hand">structure holds · interruption moves</p></div>
      <div className="aev-stable-field"><div className="aev-stable-image"><Image src="/aet-visual-rebuild-assets/aet-opening-workplace.png" alt="A workplace with a person at a desk and other workers in the surrounding field." width={2048} height={1152} unoptimized /><svg viewBox="0 0 1000 460" aria-hidden="true"><path className="aev-graphite-structure" d="M55 354C210 310 314 330 430 284S643 274 940 220" /><path className="aev-event-stroke" d="M482 70C560 142 515 208 586 252S748 292 920 250" /><circle className="aev-event-puncture" cx="482" cy="70" r="12" /></svg><span className="aev-field-word feature-word">FEATURE / CONDITION</span><span className="aev-field-word event-word">EVENT / OCCURRENCE</span></div><div className="aev-stable-key"><div><span className="aev-key-line" /><p>relatively enduring</p><b>autonomy · support · workload</b></div><div><span className="aev-key-burst" /><p>a change within it</p><b>criticism · praise · escalation</b></div><p className="aev-caption"><b>▲ Teaching construction.</b> The scene is a constructed workplace, not a reported case.</p></div></div>
      <div className="aev-classification-list" aria-label="Canonical feature and event examples">{(rec.classification?.items ?? []).slice(0,4).map(item=><article key={item.scenario}><span className={item.answer === "event" ? "aev-class-event" : "aev-class-feature"}>{item.answer}</span><div><b>{item.scenario}</b><p>{item.explanation}</p></div></article>)}</div>
    </section>

    <AETVisualRebuildInteractive />

    <section className="aev-distinction" id="aev-distinction" aria-labelledby="aev-distinction-title"><div className="aev-distinction-head"><Kicker number="06">DO NOT FLATTEN THE TERMS</Kicker><Heading id="aev-distinction-title">Feeling is not<br /><em>evaluation.</em></Heading><p>{rec.conceptComparison?.lede}</p><p className="aev-hand">brief mark · diffuse field · accumulated reading · settled structure</p></div><div className="aev-distinction-field"><div className="aev-concept-side aev-feeling-side"><p className="aev-side-label">FEELING / AFFECTIVE EXPERIENCE</p><article className="aev-emotion"><span className="aev-material-label">right now</span><span className="aev-material-burst" aria-hidden="true" /><h3>Emotion</h3><p>A defined affective episode or reaction. It can arrive quickly and change within a workday.</p></article><article className="aev-mood"><span className="aev-material-label">across a stretch</span><span className="aev-material-cloud" aria-hidden="true" /><h3>Mood</h3><p>A more diffuse affective state, related to emotion but not the same construct.</p></article><article className="aev-accumulated"><span className="aev-material-label">across episodes</span><span className="aev-material-trace" aria-hidden="true" /><h3>Accumulated affective experience</h3><p>A history of moments that may inform a broader evaluation. The exact integration process remains open.</p></article></div><div className="aev-concept-side aev-evaluation-side"><p className="aev-side-label">EVALUATION / ATTITUDE</p><article className="aev-beliefs"><span className="aev-material-label">what the job means</span><span className="aev-material-notes" aria-hidden="true" /><h3>Beliefs / evaluations</h3><p>What the person thinks the job offers, demands, or means relative to goals, values, and standards.</p></article><article className="aev-attitude"><span className="aev-material-label">about the job</span><span className="aev-material-frame" aria-hidden="true" /><h3>Job satisfaction</h3><p>An evaluative work attitude. It can reflect affective experience and beliefs, but is not a mood score.</p></article></div></div><p className="aev-caption"><b>■ Faithful explanation.</b> Affective episodes and accumulated experience can contribute to evaluation; this is not a mechanical formula for satisfaction.</p></section>

    <section className="aev-map" id="aev-map" aria-labelledby="aev-map-title"><div className="aev-map-copy"><Kicker number="07">THE MACROSTRUCTURE / WHAT LIES BENEATH</Kicker><Heading id="aev-map-title">A map,<br /><em>drawn through a workday.</em></Heading><p>{rec.scopeMap?.lede}</p><p className="aev-hand">the illustration explains the experience</p></div><div><div className="aev-map-stage"><AETIllustratedMacrostructure /></div><AETRelationshipLedger /><p className="aev-caption"><b>● Source-grounded structure.</b> The drawing makes the relationships lived and visible; the ledger keeps the canonical architecture explicit without implying effect magnitude or deterministic causation.</p></div></section>

    <section className="aev-scholarship" id="aev-scholarship" aria-labelledby="aev-scholarship-title"><div className="aev-scholarship-head"><Kicker number="08">QUIET SCHOLARSHIP / WHAT HELD UP?</Kicker><Heading id="aev-scholarship-title">The map kept<br /><em>moving.</em></Heading><p>{rec.trailLede}</p></div><div className="aev-trail">{rec.origins.slice(0,5).map((origin,i)=><article key={`${origin.year}-${origin.author}`}><span>{origin.year}</span><div><h3><Rich html={origin.author} /></h3><p><Rich html={origin.work} /></p><small>{origin.contribution}</small></div><b>0{i+1}</b></article>)}</div><div className="aev-evidence"><p className="aev-label">later evidence · read with restraint</p><p><b>1999 · Weiss, Nicholas &amp; Daus.</b> Diary evidence separates episodic mood, job beliefs, satisfaction and temporal variation.</p><p><b>2006 · Wegge et al.</b> Field evidence tests construct distinctions and selected relationships without establishing the full temporal chain.</p><p><b>2020 · Dalal, Alaybek &amp; Lievens.</b> Later synthesis keeps within-person performance variability visible.</p></div></section>

    <section className="aev-open" id="aev-open" aria-labelledby="aev-open-title"><div><Kicker number="09">WHERE THE MAP STOPS</Kicker><Heading id="aev-open-title">A boundary is useful<br /><em>information.</em></Heading><p>{rec.scopeMap?.lede}</p></div><div className="aev-open-field"><p className="aev-open-question">What remains under-specified?</p><ul>{["Why does this event produce this specific emotion?","How exactly are events appraised?","When does affect become behaviour — and when does it dissipate?","How do event histories accumulate into broader attitudes?","How should time be sampled and measured?"].map(item=><li key={item}>{item}</li>)}</ul><p className="aev-hand">? the map stops where the evidence stops</p></div></section>

    <section className="aev-sources" aria-labelledby="aev-sources-title"><div><Kicker number="10">CLAIMS / SOURCES / PROVENANCE</Kicker><Heading id="aev-sources-title">Keep the marks<br /><em>attached to the claims.</em></Heading><p>Academic meaning stays live and traceable. The drawings make relationships easier to see; the sources support what can be claimed.</p></div><div className="aev-source-grid"><ol>{rec.minimumReading.slice(0,5).map((source,i)=><li key={source.citation}><span>0{i+1}</span><p><Rich html={source.citation} /></p><small>{source.contribution}{source.doi && <> · <a className="aev-source-doi" href={`https://doi.org/${source.doi}`} target="_blank" rel="noreferrer">DOI ↗</a></>}</small></li>)}</ol><ul>{rec.provenance.map(item=><li key={item.label}><span style={{color:item.colour}}>{item.glyph}</span><div><b>{item.label}</b><p>{item.note}</p></div></li>)}</ul></div></section>
    <section className="aev-back"><a href="/concept-lab/library">← Return to the atlas</a><span>{variant === "target" ? "Affective Events Theory · isolated visual rebuild · production untouched" : "Affective Events Theory · Academic Concept Lab theory"}</span></section>
  </div>;
}



