/**
 * Canonical metadata for authored Concept Lab teaching artwork.
 *
 * This describes the visual material and its possible readings. It does not
 * carry scholarly claims. A consuming component still decides whether a
 * particular use is decorative, contextual or explanatory.
 */

export const ART_ASSET_IDS = [
  "home-atlas-head-globe",
  "home-organisation-systems",
  "home-record-forms",
  "home-provenance-sources",
  "home-music-signal-wide",
  "aet-opening-workplace",
  "aet-event-reaction",
  "aet-two-clocks",
  "aet-workday-strip",
  "aet-macrostructure-cinematography",
  "rta-interpretive-field",
  "tuned-out-observer-lens",
  "jdr-working-world",
  "jdr-two-currents",
  "jdr-challenge-hindrance",
  "jdr-resource-interaction",
  "hpa-cascade-loop",
  "ipa-double-hermeneutic",
  "tonal-field",
  "meyer-open-phrase",
  "huron-outcome-hinge",
  "idyom-context-field",
  "sdt-opening-loops",
  "sdt-reason-lens",
  "set-opening-rails",
  "po-opening-rooms",
  "po-four-people",
  "po-room-wash",
  "po-four-targets",
  "wp-opening-sheets",
  "asa-opening-mixture",
  "gttm-opening-structures",
  "narmour-opening-gestures",
  "stat-opening-stream",
  "pp-opening-ghosts",
  "mp-opening-threads",
] as const;

export type ArtAssetId = typeof ART_ASSET_IDS[number];
export type ArtMaterialRole = "scene" | "field" | "fragment-source" | "atmosphere" | "teaching-analogy";
export type ArtAccessibilityRole = "decorative" | "explanatory" | "contextual";
export type ArtEpistemicRole = "teaching" | "editorial" | "atmosphere" | "source-reproduction" | "interface";
export type ArtEvidenceStatus = "not-empirical-evidence" | "source-reproduction";
export type ArtAssetStatus = "active" | "frozen" | "benchmark-support";

export type ArtCrop = {
  id: string;
  bounds: readonly [number, number, number, number];
  conceptualRole: string;
};

export type ArtAsset = {
  id: ArtAssetId;
  src: `/${string}`;
  owner: string;
  dimensions: { width: number; height: number };
  conceptualRole: string;
  materialRole: ArtMaterialRole;
  accessibilityRole: ArtAccessibilityRole;
  baseDescription: string;
  longDescription?: string;
  epistemicRole: ArtEpistemicRole;
  evidenceStatus: ArtEvidenceStatus;
  cropCandidates: readonly ArtCrop[];
  responsiveGuidance: string;
  provenanceNote: string;
  status: ArtAssetStatus;
};

export const ART_ASSETS: readonly ArtAsset[] = [
  {
    id: "home-atlas-head-globe",
    src: "/visual-language/home/home-atlas-head-globe.webp",
    owner: "home",
    dimensions: { width: 1672, height: 941 },
    conceptualRole: "Establishes the atlas as one connected field of ideas, people, evidence and disciplines.",
    materialRole: "scene",
    accessibilityRole: "explanatory",
    baseDescription: "A coloured-pencil field with a human head, brain, globe, music and connected disciplines.",
    epistemicRole: "teaching",
    evidenceStatus: "not-empirical-evidence",
    cropCandidates: [
      { id: "home-opening-field", bounds: [0, 0, 1672, 941], conceptualRole: "The whole atlas opening." },
      { id: "home-music-territory", bounds: [165, 284, 367, 240], conceptualRole: "A music and sound fragment for the discipline field." },
    ],
    responsiveGuidance: "Keep the head and connected field legible at the opening; preserve the white margin around the source on narrow screens.",
    provenanceNote: "Authored Concept Lab teaching artwork. It is a visual orientation, not a map of empirical relationships.",
    status: "benchmark-support",
  },
  {
    id: "home-organisation-systems",
    src: "/visual-language/home/home-organisation-systems.webp",
    owner: "home",
    dimensions: { width: 1536, height: 1024 },
    conceptualRole: "Makes organisational behaviour feel social, layered and relational.",
    materialRole: "fragment-source",
    accessibilityRole: "contextual",
    baseDescription: "People work together around a table while organisational layers and relationships recede behind them.",
    epistemicRole: "teaching",
    evidenceStatus: "not-empirical-evidence",
    cropCandidates: [
      { id: "home-organisation-discipline", bounds: [310, 340, 590, 330], conceptualRole: "The organisational behaviour territory fragment." },
    ],
    responsiveGuidance: "Use the crop as a quiet territory fragment; never let it compete with the discipline heading or live themes.",
    provenanceNote: "Authored teaching material for the Home atlas; it does not depict a reported workplace or study sample.",
    status: "benchmark-support",
  },
  {
    id: "home-record-forms",
    src: "/visual-language/home/home-record-forms.webp",
    owner: "home",
    dimensions: { width: 1672, height: 941 },
    conceptualRole: "Gives Theory, Mechanism, Method and Study distinct material postures.",
    materialRole: "fragment-source",
    accessibilityRole: "contextual",
    baseDescription: "A coloured-pencil sheet of four visual fragments: a lens, a pathway, a magnifying glass and research documents.",
    epistemicRole: "teaching",
    evidenceStatus: "not-empirical-evidence",
    cropCandidates: [
      { id: "home-theory-form", bounds: [65, 245, 390, 315], conceptualRole: "A lens for seeing and framing." },
      { id: "home-mechanism-form", bounds: [480, 270, 365, 300], conceptualRole: "A pathway between things." },
      { id: "home-method-form", bounds: [925, 285, 290, 300], conceptualRole: "A practice for investigating material." },
      { id: "home-study-form", bounds: [1315, 210, 325, 380], conceptualRole: "Documents and charts as an argument from evidence." },
    ],
    responsiveGuidance: "Keep each form fragment subordinate to its live title and explanation; retain semantic asymmetry without collapsing the four forms into cards.",
    provenanceNote: "Authored teaching analogy for the four record kinds; it does not stand in for a source or finding.",
    status: "benchmark-support",
  },
  {
    id: "home-provenance-sources",
    src: "/visual-language/home/home-provenance-sources.webp",
    owner: "home",
    dimensions: { width: 1672, height: 941 },
    conceptualRole: "Connects provenance and scholarship to visible source material.",
    materialRole: "fragment-source",
    accessibilityRole: "contextual",
    baseDescription: "A graphite stack of books labelled publications, research, archives, data and ideas.",
    epistemicRole: "editorial",
    evidenceStatus: "not-empirical-evidence",
    cropCandidates: [
      { id: "home-source-books", bounds: [15, 279, 355, 258], conceptualRole: "A small source stack beside the provenance explanation." },
    ],
    responsiveGuidance: "Keep the books beside the live provenance text and let the text remain the accessible source of the claim.",
    provenanceNote: "Editorial source metaphor; the drawn labels are not citations and must not replace live references.",
    status: "benchmark-support",
  },
  {
    id: "home-music-signal-wide",
    src: "/visual-language/home/home-music-signal-wide.webp",
    owner: "gestalt-principles-in-music",
    dimensions: { width: 800, height: 500 },
    conceptualRole: "Provides a listening field in which grouping, whole/part and competing organisation can be read.",
    materialRole: "field",
    accessibilityRole: "explanatory",
    baseDescription: "A coloured-pencil listening profile with a human face, musical notation and sound events gathering into perceptual groups.",
    epistemicRole: "teaching",
    evidenceStatus: "not-empirical-evidence",
    cropCandidates: [
      { id: "gestalt-listening-field", bounds: [0, 0, 800, 500], conceptualRole: "The shared perceptual field for Gestalt grouping." },
    ],
    responsiveGuidance: "Use the full field for orientation and allow later uses to become quieter or decorative when live labels carry the grouping meaning.",
    provenanceNote: "Authored teaching artwork for Gestalt-specific visual explanation, not a recording or empirical result.",
    status: "benchmark-support",
  },
  {
    id: "aet-opening-workplace",
    src: "/aet-visual-rebuild-assets/aet-opening-workplace.png",
    owner: "affective-events-theory",
    dimensions: { width: 1774, height: 887 },
    conceptualRole: "Establishes one continuous workplace in which conditions and events coexist.",
    materialRole: "scene",
    accessibilityRole: "contextual",
    baseDescription: "A constructed workplace with people, desks, meeting areas and a stable field of working conditions.",
    epistemicRole: "teaching",
    evidenceStatus: "not-empirical-evidence",
    cropCandidates: [{ id: "aet-opening-world", bounds: [0, 0, 1774, 887], conceptualRole: "The stable workplace field." }],
    responsiveGuidance: "Preserve the stable field while allowing mobile crops to foreground the currently discussed relation.",
    provenanceNote: "Authored teaching construction for AET; it is not a reported case or measured workday.",
    status: "frozen",
  },
  {
    id: "aet-event-reaction",
    src: "/aet-visual-rebuild-assets/aet-event-reaction.png",
    owner: "affective-events-theory",
    dimensions: { width: 1774, height: 887 },
    conceptualRole: "Shows one workplace event opening into different affective readings.",
    materialRole: "field",
    accessibilityRole: "explanatory",
    baseDescription: "A shared workplace event branches into two hand-drawn reaction paths.",
    epistemicRole: "teaching",
    evidenceStatus: "not-empirical-evidence",
    cropCandidates: [{ id: "aet-same-event-reaction", bounds: [0, 0, 1774, 887], conceptualRole: "The same event, different reaction field." }],
    responsiveGuidance: "Keep the shared event visible when a reaction route is focused; focus must not imply that the other reading disappeared.",
    provenanceNote: "Authored AET teaching artwork; it illustrates a conceptual contrast rather than reporting reaction data.",
    status: "frozen",
  },
  {
    id: "aet-two-clocks",
    src: "/aet-visual-rebuild-assets/aet-two-clocks.png",
    owner: "affective-events-theory",
    dimensions: { width: 1536, height: 1024 },
    conceptualRole: "Keeps affect-driven and judgement-driven routes parallel rather than placing them on one scale.",
    materialRole: "field",
    accessibilityRole: "explanatory",
    baseDescription: "Two coloured-pencil currents move around a shared centre at different temporal qualities.",
    epistemicRole: "teaching",
    evidenceStatus: "not-empirical-evidence",
    cropCandidates: [{ id: "aet-parallel-currents", bounds: [0, 0, 1536, 1024], conceptualRole: "Parallel affective and judgement-driven routes." }],
    responsiveGuidance: "Retain a readable residual trace of the unfocused current at every width.",
    provenanceNote: "Authored AET teaching artwork; colour and route shape do not encode measured effect size.",
    status: "frozen",
  },
  {
    id: "aet-workday-strip",
    src: "/aet-visual-rebuild-assets/aet-workday-strip.png",
    owner: "affective-events-theory",
    dimensions: { width: 2164, height: 727 },
    conceptualRole: "Makes within-person time and residue visible across one constructed workday.",
    materialRole: "field",
    accessibilityRole: "explanatory",
    baseDescription: "A temporal strip of workplace fragments from coffee and messages to meetings, papers and a late working desk.",
    epistemicRole: "teaching",
    evidenceStatus: "not-empirical-evidence",
    cropCandidates: [{ id: "aet-workday-sequence", bounds: [0, 0, 2164, 727], conceptualRole: "One workday remembered through moments." }],
    responsiveGuidance: "Mobile may re-sequence moments vertically while preserving the order and the persistent workday reference.",
    provenanceNote: "Authored AET teaching artwork; residue is a visual prompt, not a mood score or longitudinal measure.",
    status: "frozen",
  },
  {
    id: "aet-macrostructure-cinematography",
    src: "/aet-visual-rebuild-assets/aet-macrostructure-illustrated-workday-cinematography.png",
    owner: "affective-events-theory",
    dimensions: { width: 1942, height: 809 },
    conceptualRole: "Carries the macrostructure from environment through event, reaction, response, evaluation and later action.",
    materialRole: "scene",
    accessibilityRole: "explanatory",
    baseDescription: "A continuous coloured-pencil and graphite workplace drawing showing one person moving through a stable context, event, reaction, response, evaluation and later action.",
    epistemicRole: "teaching",
    evidenceStatus: "not-empirical-evidence",
    cropCandidates: [
      { id: "aet-macrostructure-field", bounds: [0, 0, 1942, 809], conceptualRole: "The complete AET macrostructure field." },
    ],
    responsiveGuidance: "Desktop may show the continuous field; mobile uses the approved cinematic vertical crop sequence without replacing the source artwork.",
    provenanceNote: "Approved authored AET teaching artwork; labels and theory relationships remain live HTML.",
    status: "frozen",
  },
  {
    id: "rta-interpretive-field",
    src: "/reflexive-ta-target-assets/rta-interpretive-field.png",
    owner: "reflexive-thematic-analysis",
    dimensions: { width: 1774, height: 887 },
    conceptualRole: "Makes the researcher, data, position and context one interpretive field.",
    materialRole: "field",
    accessibilityRole: "contextual",
    baseDescription: "A researcher inside a coloured-pencil interpretive field where data, position and context shape the reading.",
    epistemicRole: "teaching",
    evidenceStatus: "not-empirical-evidence",
    cropCandidates: [{ id: "rta-interpretive-opening", bounds: [0, 0, 1774, 887], conceptualRole: "The opening interpretive field." }],
    responsiveGuidance: "Keep the researcher and surrounding field legible; the live method copy remains the canonical account on narrow screens.",
    provenanceNote: "Authored RTA teaching artwork; it does not reproduce participant data or establish a finding.",
    status: "frozen",
  },
  {
    id: "tuned-out-observer-lens",
    src: "/study-tuned-out-assets/observer-lens.png",
    owner: "tuned-out-or-dialed-in",
    dimensions: { width: 1536, height: 1024 },
    conceptualRole: "Keeps one visible act of music listening in view while making alternative observer readings legible.",
    materialRole: "scene",
    accessibilityRole: "contextual",
    baseDescription: "An editorial pencil reconstruction of an employee listening to music while working, with two coworkers observing the same scene through distinct coral and teal traces.",
    epistemicRole: "teaching",
    evidenceStatus: "not-empirical-evidence",
    cropCandidates: [
      { id: "tuned-out-observer-field", bounds: [0, 0, 1536, 1024], conceptualRole: "The whole observer-interpretation field for the study opening." },
    ],
    responsiveGuidance: "Keep the listener and both observer positions readable; labels and all scholarly interpretation remain live HTML, especially at mobile widths.",
    provenanceNote: "Generated editorial reconstruction for explanation only; it does not depict study participants, data, results or a reproduced source figure.",
    status: "active",
  },
  {
    id: "jdr-working-world",
    src: "/visual-language/theories/jdr/jdr-opening.webp",
    owner: "job-demands-resources",
    dimensions: { width: 1448, height: 1086 },
    conceptualRole: "Establishes one working world in which demands and resources coexist around the same desk.",
    materialRole: "scene",
    accessibilityRole: "contextual",
    baseDescription: "A coloured-pencil workplace with one worker at a desk inside an ochre ring, vermilion demands gathered on one side and teal resources on the other.",
    epistemicRole: "teaching",
    evidenceStatus: "not-empirical-evidence",
    cropCandidates: [
      { id: "jdr-world-whole", bounds: [0, 0, 1448, 1086], conceptualRole: "The whole working world for the opening." },
      { id: "jdr-desk", bounds: [362, 213, 580, 565], conceptualRole: "The central desk, where one condition changes category with who is doing the work." },
    ],
    responsiveGuidance: "Desktop may bleed the field to the page edge; phones use the 880px source full width. The desk crop is reused for the sorting exercise.",
    provenanceNote: "Authored JD–R teaching artwork recovered from the preserved JD–R visual study (archive/concept-lab-local-preservation-2026-09-16). It is a constructed workplace, not a reported case; handwritten words are marginalia and all theory labels stay live HTML.",
    status: "active",
  },
  {
    id: "jdr-two-currents",
    src: "/visual-language/theories/jdr/jdr-processes.webp",
    owner: "job-demands-resources",
    dimensions: { width: 1448, height: 1086 },
    conceptualRole: "Draws the health-impairment and motivational processes as parallel currents from one job.",
    materialRole: "field",
    accessibilityRole: "explanatory",
    baseDescription: "One desk from which a vermilion current runs across the top of the sheet and a teal current across the bottom.",
    epistemicRole: "teaching",
    evidenceStatus: "not-empirical-evidence",
    cropCandidates: [
      { id: "jdr-currents-field", bounds: [0, 0, 1448, 1086], conceptualRole: "Both currents together, as the theory holds them." },
    ],
    responsiveGuidance: "Phones pan the drawing sideways inside a labelled, focusable strip rather than shrinking it.",
    provenanceNote: "Authored JD–R teaching artwork recovered from the preserved JD–R visual study (archive/concept-lab-local-preservation-2026-09-16). It is a constructed workplace, not a reported case; handwritten words are marginalia and all theory labels stay live HTML.",
    status: "active",
  },
  {
    id: "jdr-challenge-hindrance",
    src: "/visual-language/theories/jdr/jdr-challenge-hindrance.webp",
    owner: "job-demands-resources",
    dimensions: { width: 1448, height: 1086 },
    conceptualRole: "Shows the same sustained effort returning differently as a challenge or a hindrance demand.",
    materialRole: "field",
    accessibilityRole: "explanatory",
    baseDescription: "One worker's effort splitting into an upper teal route toward learning and open space and a lower vermilion route through interruptions, paperwork and a barrier.",
    epistemicRole: "teaching",
    evidenceStatus: "not-empirical-evidence",
    cropCandidates: [
      { id: "jdr-fork-field", bounds: [0, 0, 1448, 1086], conceptualRole: "The fork of one effort into two returns." },
    ],
    responsiveGuidance: "Phones pan the drawing sideways; the classification exercise and definitions remain live HTML below.",
    provenanceNote: "Authored JD–R teaching artwork recovered from the preserved JD–R visual study (archive/concept-lab-local-preservation-2026-09-16). It is a constructed workplace, not a reported case; handwritten words are marginalia and all theory labels stay live HTML.",
    status: "active",
  },
  {
    id: "jdr-resource-interaction",
    src: "/visual-language/theories/jdr/jdr-interaction.webp",
    owner: "job-demands-resources",
    dimensions: { width: 1448, height: 1086 },
    conceptualRole: "Keeps the demand constant while resources change the relationships leaving the desk (buffering and boosting).",
    materialRole: "field",
    accessibilityRole: "explanatory",
    baseDescription: "Demands converge on a worker at a desk from the left; on the right, routes pass a colleague offering support and a worker with room to grow.",
    epistemicRole: "teaching",
    evidenceStatus: "not-empirical-evidence",
    cropCandidates: [
      { id: "jdr-junction-field", bounds: [0, 0, 1448, 1086], conceptualRole: "The junction where resources change the connection." },
    ],
    responsiveGuidance: "Phones pan the drawing; the two route weights are code-drawn overlays whose widths are not magnitudes.",
    provenanceNote: "Authored JD–R teaching artwork recovered from the preserved JD–R visual study (archive/concept-lab-local-preservation-2026-09-16). It is a constructed workplace, not a reported case; handwritten words are marginalia and all theory labels stay live HTML.",
    status: "active",
  },
  {
    id: "hpa-cascade-loop",
    src: "/visual-language/mechanisms/hpa/hpa-cascade-art-directed.webp",
    owner: "hpa-axis",
    dimensions: { width: 900, height: 1500 },
    conceptualRole: "Draws the cascade as a descent from an appraising brain through three glands to body and brain, with negative feedback climbing the side.",
    materialRole: "field",
    accessibilityRole: "contextual",
    baseDescription: "A vertical coloured-pencil field: an abstract blue-violet appraisal area, three distinct pigment stages connected by coloured currents, a fan of downstream pathways, and a graphite feedback route rising on the right.",
    epistemicRole: "teaching",
    evidenceStatus: "not-empirical-evidence",
    cropCandidates: [
      { id: "hpa-cascade-whole", bounds: [0, 0, 900, 1500], conceptualRole: "The complete descent and its loop, used as a sticky figure while the reader walks the steps." },
    ],
    responsiveGuidance: "Desktop keeps the drawing in view beside the steps; phones place it once above the steps, using the 600px source.",
    provenanceNote: "AI-assisted artwork art-directed for this record. A teaching construction: it depicts no data, measured concentrations, literal anatomy or source figure, and every label is live HTML. Position means sequence only, not anatomical scale.",
    status: "active",
  },
  {
    id: "ipa-double-hermeneutic",
    src: "/visual-language/methods/ipa/ipa-double-hermeneutic.webp",
    owner: "interpretative-phenomenological-analysis",
    dimensions: { width: 1400, height: 1008 },
    conceptualRole: "Draws the double hermeneutic: the researcher's loop reaches the experience only through the participant's own loop of sense-making.",
    materialRole: "field",
    accessibilityRole: "contextual",
    baseDescription: "A warm hatched mass of experience circled by a returning teal line, inside a larger, broken ochre loop with small reading ticks and illegible margin scribbles.",
    epistemicRole: "teaching",
    evidenceStatus: "not-empirical-evidence",
    cropCandidates: [
      { id: "ipa-field-whole", bounds: [0, 0, 1400, 1008], conceptualRole: "The nested loops for the opening." },
    ],
    responsiveGuidance: "Live script labels name the three layers; on phones the researcher label wraps to stay inside the field.",
    provenanceNote: "Drawn for this record with the Lab's offline coloured-pencil renderer (scripts/art). A teaching construction: it depicts no data, measurement or source figure, and every label is live HTML. The scribbles are marks of reading, not text.",
    status: "active",
  },
  {
    id: "tonal-field",
    src: "/visual-language/theories/tonal/tonal-field-art-directed.webp",
    owner: "tonal-hierarchy",
    dimensions: { width: 1000, height: 1000 },
    conceptualRole: "Provides one tonal field in which distance from home carries tonal function while each pitch class keeps its own spoke.",
    materialRole: "field",
    accessibilityRole: "decorative",
    baseDescription: "A tonal field with a central vermilion pigment mass, interrupted teal and ochre relational orbits, pale graphite construction sweeps, and twelve faint pitch-class spokes.",
    epistemicRole: "teaching",
    evidenceStatus: "not-empirical-evidence",
    cropCandidates: [
      { id: "tonal-field-whole", bounds: [0, 0, 1000, 1000], conceptualRole: "The whole field, re-read in every chapter by moving live tone markers." },
    ],
    responsiveGuidance: "The field scales as a square; tone markers are live buttons or labels placed by code, so the drawing never carries a label.",
    provenanceNote: "AI-assisted artwork art-directed for this record. A teaching construction, not data, measurement or a source figure; all labels remain live HTML. The orbits are a qualitative metaphor for relative tonal centrality and fit, not a rating profile; no profile value is shown.",
    status: "active",
  },
  {
    id: "meyer-open-phrase",
    src: "/music-expectation/meyer-open-phrase.webp",
    owner: "meyers-expectancy-theory",
    dimensions: { width: 1536, height: 1024 },
    conceptualRole: "One unresolved musical gesture opens into three qualitative continuations; a later trace returns to the hinge.",
    materialRole: "field",
    accessibilityRole: "explanatory",
    baseDescription: "A drawn musical gesture pauses at an open hinge, then continues along three differently shaped paths; a faint graphite trace returns toward the hinge.",
    longDescription: "The three paths are a teaching illustration of alternative musical futures. Their position, pigment and stroke do not encode numerical probability, emotional intensity or a universal listener response. The backward graphite trace suggests the record’s account of retrospective interpretation.",
    epistemicRole: "teaching",
    evidenceStatus: "not-empirical-evidence",
    cropCandidates: [{ id: "meyer-hinge-and-futures", bounds: [0, 0, 1536, 1024], conceptualRole: "The suspended phrase, its qualitative continuations and retrospective trace." }],
    responsiveGuidance: "Keep the hinge and all three continuations visible on desktop; on mobile preserve the hinge and selected route without shrinking the live labels.",
    provenanceNote: "Generated and art-directed Concept Lab teaching illustration. It is not a score, empirical stimulus, probability plot or reported listener response.",
    status: "active",
  },
  {
    id: "huron-outcome-hinge",
    src: "/music-expectation/huron-outcome-hinge.webp",
    owner: "hurons-itpra-theory",
    dimensions: { width: 1916, height: 821 },
    conceptualRole: "Unequal response traces approach and extend beyond one outcome hinge, with two post-onset traces beginning in parallel.",
    materialRole: "field",
    accessibilityRole: "explanatory",
    baseDescription: "A wide pencil-and-pigment field gathers toward a central outcome mark and opens into distinct traces on the other side.",
    longDescription: "The image is a teaching illustration of unequal, potentially overlapping response windows around an anticipated outcome. It does not show measured durations, neural activity, physiological amplitude or a universal sequence.",
    epistemicRole: "teaching",
    evidenceStatus: "not-empirical-evidence",
    cropCandidates: [{ id: "huron-before-and-after", bounds: [0, 0, 1916, 821], conceptualRole: "The full before/after field and outcome hinge." }],
    responsiveGuidance: "Use the wide field as a two-sided composition at desktop; at mobile retain the outcome hinge and reflow each live response label alongside its local time relation.",
    provenanceNote: "Generated and art-directed Concept Lab teaching illustration. It is not Huron’s source diagram, a physiological trace or timing data.",
    status: "active",
  },
  {
    id: "idyom-context-field",
    src: "/music-expectation/idyom-context-field.webp",
    owner: "idyom-information-dynamics-of-music",
    dimensions: { width: 1536, height: 1024 },
    conceptualRole: "Layered long-term and local musical histories meet a set of possible next events without encoding their probabilities.",
    materialRole: "field",
    accessibilityRole: "explanatory",
    baseDescription: "Faint layered musical contours overlap a shorter, more strongly drawn phrase, beside several separate possible-event marks; one event is circled as a sample.",
    longDescription: "The layers are a qualitative illustration of learned and local musical context. The possible-event marks are not a probability distribution, IDyOM output, human expectation measure or neural mechanism. Any numerical distribution is shown separately in live text and the model interaction.",
    epistemicRole: "teaching",
    evidenceStatus: "not-empirical-evidence",
    cropCandidates: [{ id: "idyom-context-and-sample", bounds: [0, 0, 1536, 1024], conceptualRole: "The overlapping contexts and separate possible-event marks." }],
    responsiveGuidance: "Keep the context layers and distinct sample-event area legible; on mobile place live context labels adjacent to the corresponding area and avoid reducing the numerical model interaction to an image.",
    provenanceNote: "Generated and art-directed Concept Lab teaching illustration. It does not show a documented IDyOM run or encode probability, entropy or surprise.",
    status: "active",
  },
  {
    id: "sdt-opening-loops",
    src: "/visual-language/theories/sdt/sdt-hero.webp",
    owner: "self-determination-theory",
    dimensions: { width: 1600, height: 580 },
    conceptualRole: "Shows the same action line passing unchanged through two loops that stand for two people's sense of self, with the reason drawn differently around each.",
    materialRole: "scene",
    accessibilityRole: "explanatory",
    baseDescription: "A graphite line runs across the sheet through two loops. In the first, a settled teal swirl with warm marks sits inside the loop and yellow strokes open outward through its wall. Around the second, converging red strands press in from outside and gather in a collar along the inner wall.",
    longDescription: "The drawing is a teaching illustration of one distinction: the same visible action can be moved by a reason the person holds or by pressure they have not made their own. Position and pigment show the kind of reason, never an amount of motivation or effort. It is not a picture of any study, sample or measurement.",
    epistemicRole: "teaching",
    evidenceStatus: "not-empirical-evidence",
    cropCandidates: [
      { id: "sdt-loops-whole", bounds: [0, 0, 1600, 580], conceptualRole: "The whole panorama for the opening: one action, two selves." },
    ],
    responsiveGuidance: "Desktop bleeds the panorama to the page edge under the title. Below 760px the same drawing is turned so the action runs downward and the two selves stack; the two constructed cases follow as live text.",
    provenanceNote: "Drawn for this record with the Lab's offline coloured-pencil renderer (scripts/art, scene sdt-hero). A teaching construction: it depicts no data, measurement or source figure, and every label is live HTML.",
    status: "active",
  },
  {
    id: "sdt-reason-lens",
    src: "/visual-language/theories/sdt/sdt-lens-wall.webp",
    owner: "self-determination-theory",
    dimensions: { width: 800, height: 800 },
    conceptualRole: "Provides one loop and one action line in which a reason can sit outside the loop, at its wall, inside it, share its stroke, or arise from the activity itself.",
    materialRole: "field",
    accessibilityRole: "explanatory",
    baseDescription: "A loose graphite loop crossed by a horizontal action line, with four faint open rings marking places a reason can sit. Separate pigment layers - an outside pressure bundle, an inner collar, wall-crossing teal strands, an outward golden glow and two reason masses - are placed over it by the page.",
    longDescription: "The layers are drawn separately (sdt-lens-push, -collar, -through, -glow, -stone-red and -stone-teal) so that the page can move one reason across the loop and change its character rather than swap pictures. Places are not steps: nothing here says a reason must travel from outside to inside. The drawing shows kind of reason, not amount of motivation.",
    epistemicRole: "teaching",
    evidenceStatus: "not-empirical-evidence",
    cropCandidates: [
      { id: "sdt-lens-whole", bounds: [0, 0, 800, 800], conceptualRole: "The whole loop, read six ways by moving one reason." },
    ],
    responsiveGuidance: "The square lens is pinned above the statements on narrow screens so the drawing stays in view while a reason is chosen; the six readings are also listed in full as live text.",
    provenanceNote: "Drawn for this record with the Lab's offline coloured-pencil renderer (scripts/art, scenes sdt-lens-*). A teaching construction: not data, a measurement or a source figure.",
    status: "active",
  },
  {
    id: "set-opening-rails",
    src: "/visual-language/theories/set/set-hero.webp",
    owner: "social-exchange-theory",
    dimensions: { width: 1600, height: 476 },
    conceptualRole: "Draws one exchange as a strand between two actors' own lines, a later and looser answer, and then the woven history that many exchanges leave.",
    materialRole: "scene",
    accessibilityRole: "explanatory",
    baseDescription: "Two horizontal graphite lines, actor A's above and actor B's below, each with a ringed dot at its left end. A single teal strand carrying a small ochre token runs from A's line to B's; a later, thinner ochre strand runs back, broken by three dots; then many teal, coral, ochre and blue strands cross between the lines in a dense woven band.",
    longDescription: "The drawing is a teaching illustration of the difference between a transaction and a relationship: one strand is an episode, and the accumulation of many is a history. Density shows accumulation, never how warm, strong or fair a relationship is. It is not a picture of any study, sample or measurement.",
    epistemicRole: "teaching",
    evidenceStatus: "not-empirical-evidence",
    cropCandidates: [
      { id: "set-rails-whole", bounds: [0, 0, 1600, 476], conceptualRole: "The whole panorama: transaction, answer, and accumulated history." },
    ],
    responsiveGuidance: "Desktop bleeds the panorama to the page edge under the title, with the three constructed moments set in columns beneath their strands. Below 760px the drawing is turned so time runs down the page and actor A stays on the left; the moments follow as live text.",
    provenanceNote: "Drawn for this record with the Lab's offline coloured-pencil renderer (scripts/art, scene set-hero). A teaching construction: it depicts no data, measurement or source figure, and every label is live HTML. The later diagrams on the page are code-drawn on the same two lines.",
    status: "active",
  },
  {
    id: "po-opening-rooms",
    src: "/visual-language/theories/po/po-hero.webp",
    owner: "person-organisation-fit",
    dimensions: { width: 1600, height: 560 },
    conceptualRole: "Draws one room at three moments of a made-up sorting toy — mixed, after one round, after three — so that a place is seen taking on the look of the people in it.",
    materialRole: "scene",
    accessibilityRole: "explanatory",
    baseDescription: "One cut-away room drawn three times, left to right, each with a pennant and a doorway in its base. In the first, twelve people of four kinds stand mixed in two rows above a mixed crowd. In the second, ring people outnumber the rest, three stand at the door and two faint outlines mark people who left. In the third, everyone in the room carries the same mark, the wall is washed in one colour, and the street holds only faint outlines.",
    longDescription: "The four kinds are told apart by a mark on the chest (ring, bar, cross, chevron), by how the shoulders are hatched and by hue, so that no reading depends on colour alone. They are stand-ins for 'someone who holds different things important', not personality types. The drawing is a teaching illustration of the toy on the page; it depicts no organisation, sample or finding, and the wash on the wall carries a proportion in a made-up room, not a measurement.",
    epistemicRole: "teaching",
    evidenceStatus: "not-empirical-evidence",
    cropCandidates: [
      { id: "po-rooms-whole", bounds: [0, 0, 1600, 560], conceptualRole: "The whole panorama: before, after one round, after three." },
    ],
    responsiveGuidance: "Desktop bleeds the panorama to the page edge under the title, with three captions set under their rooms. Below 760px the drawing is recomposed rather than turned — the first and last rooms stacked with time running down — so that the people stay upright; the middle moment is left to the toy.",
    provenanceNote: "Drawn for this record with the Lab's offline coloured-pencil renderer (scripts/art, scenes po-hero and po-hero-stack). A teaching construction of a made-up toy: not data, a sample or a source figure, and every label is live HTML.",
    status: "active",
  },
  {
    id: "po-four-people",
    src: "/visual-language/theories/po/po-people.webp",
    owner: "person-organisation-fit",
    dimensions: { width: 960, height: 528 },
    conceptualRole: "Supplies the four stand-in people, solid and as outlines, that the room toy and the page's other figures place on their floors.",
    materialRole: "fragment-source",
    accessibilityRole: "decorative",
    baseDescription: "A sheet of eight pencil busts on two rows. Row one: four people with a ring, a bar, a cross and a chevron on the chest, hatched teal, vermilion, ochre and violet. Row two: the same four as faint outlines.",
    epistemicRole: "teaching",
    evidenceStatus: "not-empirical-evidence",
    cropCandidates: [
      { id: "po-ring", bounds: [0, 0, 240, 264], conceptualRole: "The ring person." },
      { id: "po-bar", bounds: [240, 0, 240, 264], conceptualRole: "The bar person." },
      { id: "po-cross", bounds: [480, 0, 240, 264], conceptualRole: "The cross person." },
      { id: "po-chevron", bounds: [720, 0, 240, 264], conceptualRole: "The chevron person." },
    ],
    responsiveGuidance: "Cut into cells by the page and placed with CSS; always paired with words, and hidden from assistive technology because the words carry the meaning.",
    provenanceNote: "Drawn for this record with the Lab's offline coloured-pencil renderer (scripts/art, scene po-people). The four marks stand in for 'something a person holds important' in a teaching toy; they are not personality types and nothing in the record says organisations sort on them.",
    status: "active",
  },
  {
    id: "po-room-wash",
    src: "/visual-language/theories/po/po-wash.webp",
    owner: "person-organisation-fit",
    dimensions: { width: 940, height: 430 },
    conceptualRole: "Lets the wall of the toy's room take the colour of the people inside it, by laying one flat pencil wash per mark at a strength that follows how many of that mark are present.",
    materialRole: "atmosphere",
    accessibilityRole: "decorative",
    baseDescription: "Four flat washes of long pencil strokes on a sheet of four cells: teal, vermilion, ochre and violet.",
    epistemicRole: "teaching",
    evidenceStatus: "not-empirical-evidence",
    cropCandidates: [
      { id: "po-wash-ring", bounds: [0, 0, 470, 215], conceptualRole: "Teal: the ring mark." },
      { id: "po-wash-bar", bounds: [470, 0, 470, 215], conceptualRole: "Vermilion: the bar mark." },
      { id: "po-wash-cross", bounds: [0, 215, 470, 215], conceptualRole: "Ochre: the cross mark." },
      { id: "po-wash-chevron", bounds: [470, 215, 470, 215], conceptualRole: "Violet: the chevron mark." },
    ],
    responsiveGuidance: "Laid over the room's interior at an opacity that follows the room's mix; decorative, since the tally and reading beside the figure say the same thing in words.",
    provenanceNote: "Drawn for this record with the Lab's offline coloured-pencil renderer (scripts/art, scene po-wash). The strength of a wash is a proportion in a made-up room, not a measurement.",
    status: "active",
  },
  {
    id: "po-four-targets",
    src: "/visual-language/theories/po/po-targets.webp",
    owner: "person-organisation-fit",
    dimensions: { width: 1000, height: 425 },
    conceptualRole: "Gives each of the four targets of fit — organisation, job, group, vocation — its own small drawing, so that one person can be seen compared with four different things.",
    materialRole: "fragment-source",
    accessibilityRole: "decorative",
    baseDescription: "A sheet of eight small pencil pictograms on two rows: a building with a pennant, a desk with the sheet that describes a role, three people at a table, and a road running past buildings to the horizon. Row one is graphite and grey; row two is the same four with teal in the hatching.",
    epistemicRole: "teaching",
    evidenceStatus: "not-empirical-evidence",
    cropCandidates: [
      { id: "po-target-organisation", bounds: [0, 0, 250, 212], conceptualRole: "The organisation." },
      { id: "po-target-job", bounds: [250, 0, 250, 212], conceptualRole: "The job." },
      { id: "po-target-group", bounds: [500, 0, 250, 212], conceptualRole: "The group." },
      { id: "po-target-vocation", bounds: [750, 0, 250, 212], conceptualRole: "The vocation." },
    ],
    responsiveGuidance: "Cut into cells by the page and always labelled with the target's name and its letters (P–O, P–J, P–G, P–V); hidden from assistive technology.",
    provenanceNote: "Drawn for this record with the Lab's offline coloured-pencil renderer (scripts/art, scene po-targets). Pictograms for a taxonomy of targets, not portraits of any workplace.",
    status: "active",
  },
  {
    id: "wp-opening-sheets",
    src: "/visual-language/theories/wp/wp-hero.webp",
    owner: "workplace-design",
    dimensions: { width: 1600, height: 560 },
    conceptualRole: "Draws one office plan on five sheets of tracing paper — the room, the people, the sound, the sight lines, the light and warmth — so that the environment is seen as several conditions of one room, each readable alone or through the others.",
    materialRole: "scene",
    accessibilityRole: "explanatory",
    baseDescription: "One office plan drawn five times on sheets of tracing paper laid one over another and offset left to right. The first sheet holds the walls, three windows, a door with its swing and twelve desks with monitors; the second twelve people as heads and shoulders; the third vermilion rings round four talkers; the fourth violet lines between neighbouring seats; the fifth yellow rays at the windows, a warm band and a cool patch by the door.",
    longDescription: "The sheets are a teaching device for the claim that the physical environment is not one variable: each condition of the room is drawn on its own sheet and none moves because another does. The drawing depicts no real office, and no ring, line or wash on it is a measurement.",
    epistemicRole: "teaching",
    evidenceStatus: "not-empirical-evidence",
    cropCandidates: [
      { id: "wp-sheets-whole", bounds: [0, 0, 1600, 560], conceptualRole: "The whole deck of five sheets." },
      { id: "wp-sheet-room", bounds: [0, 60, 620, 480], conceptualRole: "The first sheet: the room itself." },
    ],
    responsiveGuidance: "Desktop bleeds the deck to the page edge under the title, with five captions set under the sheets. Below 760px the deck is recomposed rather than turned — the same five sheets laid down the page so that each stays large enough to read — and the captions become a list beneath.",
    provenanceNote: "Drawn for this record with the Lab's offline coloured-pencil renderer (scripts/art, scenes wp-hero and wp-hero-stack). A teaching construction: not data, a survey or a source figure, and every label is live HTML. The live figures on the page are code-drawn on the same plan.",
    status: "active",
  },
  {
    id: "asa-opening-mixture",
    src: "/visual-language/theories/asa/asa-hero.webp",
    owner: "auditory-scene-analysis",
    dimensions: { width: 1600, height: 560 },
    conceptualRole: "Draws the problem the framework names in one left-to-right picture: several sources sounding at once, the single mixture that reaches the ear, and the streams a listener hears made of it.",
    materialRole: "scene",
    accessibilityRole: "explanatory",
    baseDescription: "Four coloured lines at the left, each moving in its own way — a smooth wave, a quicker wave, a square wave, a line with sharp spikes — converge into one dark line ringed with all four colours, which opens with question marks into three separate rows of short dashes.",
    longDescription: "The four lines are sources, the dark line is their sum, and the rows of dashes are streams: contours a listener draws over tone events, which may or may not correspond to the sources. It is a teaching drawing of the perceptual problem, not a signal, a spectrogram or a result.",
    epistemicRole: "teaching",
    evidenceStatus: "not-empirical-evidence",
    cropCandidates: [
      { id: "asa-world-to-ear", bounds: [0, 0, 940, 560], conceptualRole: "The sources and their sum." },
      { id: "asa-ear-to-streams", bounds: [660, 0, 940, 560], conceptualRole: "The mixture and the streams heard from it." },
    ],
    responsiveGuidance: "Desktop bleeds the panorama to the page edge under the title, with three captions under the world, the ear and the streams. Below 760px it is recomposed in two rows — the world and the ear, then the ear and the streams, overlapping at the mixture — rather than turned, so that the waves keep their shape.",
    provenanceNote: "Drawn for this record with the Lab's offline coloured-pencil renderer (scripts/art, scene asa-hero). A teaching construction: not data, a signal or a source figure, and every label is live HTML. The plane on the rest of the page is code-drawn.",
    status: "active",
  },
  {
    id: "gttm-opening-structures",
    src: "/visual-language/theories/gttm/gttm-hero.webp",
    owner: "generative-theory-of-tonal-music",
    dimensions: { width: 1600, height: 620 },
    conceptualRole: "Draws the record's constructed sixteen-note phrase once, as pencilled noteheads, with four separate structural descriptions around it — grouping, time-span heads, tonal regions and progression, and meter — so that one surface is seen to support several related descriptions that answer different questions.",
    materialRole: "scene",
    accessibilityRole: "explanatory",
    baseDescription: "Sixteen noteheads in a row rising and falling in C major. Above them: nested teal brackets grouping the notes in fours, eights and sixteen; a red tree whose heads are ringed at events 1, 5, 9 and 16, with a dashed alternative at 13; and plum bars marking the regions I, IV, V and I with arcs for the progression between their heads. Below them: rows of gold dots, stacked higher on the events that begin bars and the phrase.",
    longDescription: "The phrase, its groups, its heads and its regions are the record's constructed teaching analysis. The drawing shows that the four descriptions are separate — each is drawn in its own place and its own way — and it is not a source analysis or a claim about how any listener parses a phrase.",
    epistemicRole: "teaching",
    evidenceStatus: "not-empirical-evidence",
    cropCandidates: [
      { id: "gttm-events-1-8", bounds: [0, 0, 820, 620], conceptualRole: "The first half of the phrase with all four structures." },
      { id: "gttm-events-9-16", bounds: [780, 0, 820, 620], conceptualRole: "The second half of the phrase with all four structures." },
    ],
    responsiveGuidance: "Desktop bleeds the drawing to the page edge under the title, with four captions naming the four structures. Below 760px it is recomposed in two rows — events 1–8, then 9–16, each with all four structures — rather than shrunk, so the noteheads and marks stay legible.",
    provenanceNote: "Drawn for this record with the Lab's offline coloured-pencil renderer (scripts/art, scene gttm-hero). A teaching construction of the record's own analysis: not a source analysis, and every label is live HTML. The figures on the page are code-drawn on the same phrase.",
    status: "active",
  },
  {
    id: "narmour-opening-gestures",
    src: "/visual-language/theories/narmour/narmour-hero.webp",
    owner: "narmours-implication-realization-theory",
    dimensions: { width: 1600, height: 620 },
    conceptualRole: "Draws the record's two constructed intervals — a small step up, C4 to D4, and a large leap up, C4 to G4 — as two heard tones with the place for a third left empty, and pencils round that empty place the four tendencies the record says such an interval tends to invite: which way, how big a step compared with the first, whether the tone stays near, and whether it comes back to the first tone.",
    materialRole: "scene",
    accessibilityRole: "explanatory",
    baseDescription: "Two melodic gestures on a pitch and time field, side by side. On the left, two tones a small step apart, C4 then D4, joined by a heavy graphite line; round the empty place where a third tone has not yet arrived, a teal arrow continues upward, a gold brace as long as the first step stands to the right, a red dotted ring with a pencilled question mark marks the neighbourhood, and a red dashed level with an arrow comes back toward the first tone. On the right, a large leap, C4 then G4: the teal arrow turns back down, the gold brace is much shorter, the red ring and question mark sit high, and a long red arrow falls toward the level of the first tone. Three faint dashed candidate tones wait at the third position in each gesture, with a plum wash behind both.",
    longDescription: "The intervals, the candidate third tones and the tendencies are the record's constructed teaching material. The marks are qualitative: an arrow says which way, a brace says how much compared with the first interval, a ring says how near, a dashed level says where the first tone was. None of them aims at a pitch, and the drawing is not a measurement of any listener's expectation.",
    epistemicRole: "teaching",
    evidenceStatus: "not-empirical-evidence",
    cropCandidates: [
      { id: "narmour-small-step", bounds: [30, 60, 780, 520], conceptualRole: "The small step and what it tends to invite." },
      { id: "narmour-large-leap", bounds: [820, 60, 780, 520], conceptualRole: "The large leap and what it tends to invite." },
    ],
    responsiveGuidance: "Desktop bleeds the drawing to the page edge under the title, with four captions naming the four kinds of tendency. Below 760px it is recomposed as two stacked panels — the small step, then the large leap — each at full width, rather than shrunk, so the arrows, braces and rings stay legible.",
    provenanceNote: "Drawn for this record with the Lab's offline coloured-pencil renderer (scripts/art, scene narmour-hero). A teaching construction of the record's own stimuli: not a source figure, and every label is live HTML. The figures on the page are code-drawn on the same field.",
    status: "active",
  },
  {
    id: "stat-opening-stream",
    src: "/visual-language/theories/stat/stat-hero.webp",
    owner: "statistical-learning-of-music",
    dimensions: { width: 1600, height: 620 },
    conceptualRole: "Draws the record's constructed stream of thirty-six tones as one unbroken line of beads at their own pitches, with the three groups of three that keep recurring in it drawn as thick coloured thread between thin graphite links, and a tally stroke kept under the stream each time a group goes by — so that a structure the sound never marks is seen to be there to be counted.",
    materialRole: "scene",
    accessibilityRole: "explanatory",
    baseDescription: "One long, unbroken stream of thirty-six pencilled beads, each at its own pitch, so the line leaps up and down. Between groups the thread is a thin graphite line; inside each group of three beads it is thick and coloured — teal, red or ochre — so three recurring groups stand out of the stream, returning in a different order each time with no gap between them. Under the stream, one tally stroke in the matching colour marks each time a group goes by. A faint plum wash lies behind it all.",
    longDescription: "The stream, its three groups and their order are the record's constructed teaching material. The colours and the tally are drawn over the stream: in the sound the groups are not marked by any pause, accent, loudness, timbre or articulation. The drawing shows information a learner could count, not that anyone has learned it.",
    epistemicRole: "teaching",
    evidenceStatus: "not-empirical-evidence",
    cropCandidates: [
      { id: "stat-tones-1-18", bounds: [20, 110, 800, 470], conceptualRole: "The first half of the stream: eighteen tones, six groups." },
      { id: "stat-tones-19-36", bounds: [780, 110, 800, 470], conceptualRole: "The second half of the stream: eighteen tones, six groups." },
    ],
    responsiveGuidance: "Desktop bleeds the drawing to the page edge under the title, with four captions naming the stream, the thick thread, the tally and the wash. Below 760px it is recomposed as two lines of eighteen tones, each at full width, rather than shrunk, so the beads and the coloured threads stay legible.",
    provenanceNote: "Drawn for this record with the Lab's offline coloured-pencil renderer (scripts/art, scene stat-hero). A teaching construction of the record's own stream: not a published stimulus, and every label is live HTML. The figures on the page are code-drawn on the same stream.",
    status: "active",
  },
  {
    id: "pp-opening-ghosts",
    src: "/visual-language/theories/pp/pp-hero.webp",
    owner: "predictive-processing-in-music",
    dimensions: { width: 1600, height: 620 },
    conceptualRole: "Draws the framework's central relation as one picture: a plum cloud for a generative model, teal dashed arrows running down to a row of dashed ghost notes for what the model expects, a row of solid notes for what actually arrives, red hatching and a hollow ring for the two places the two disagree — one note late, one note missing — and red arrows back up to the model that are thick from the mismatch that counts for more and thinner from the one that counts for less.",
    materialRole: "scene",
    accessibilityRole: "explanatory",
    baseDescription: "A plum cloud at the top, a row of ten dashed teal ghost notes beneath it with a dashed teal arrow running down to each, and a row of ten solid pencilled notes below them. Nine of the ten heard notes sit under their ghosts, but the fourth arrives late — a red hatched wedge joins it to its ghost, with a short red bracket beneath — and the seventh does not arrive, leaving a dashed empty slot ringed in red under its ghost. Two red arrows run back up to the cloud: a thick one from the late note and a thinner one from the missing note.",
    longDescription: "The late note and the missing note are constructed to show the relation between an expectation and what arrives; they are not a measurement of any listener or any neural signal. The thickness of the returning arrows says only that a mismatch can count for more or for less, which is what the framework means by precision.",
    epistemicRole: "teaching",
    evidenceStatus: "not-empirical-evidence",
    cropCandidates: [
      { id: "pp-notes-1-5", bounds: [20, 20, 800, 560], conceptualRole: "The first five notes, including the late one and the thick mismatch arrow." },
      { id: "pp-notes-6-10", bounds: [780, 20, 800, 560], conceptualRole: "The last five notes, including the missing one and the thinner mismatch arrow." },
    ],
    responsiveGuidance: "Desktop bleeds the drawing to the page edge under the title, with four captions naming the model, the ghost, the sound and the residual. Below 760px it is recomposed as two stacked panels — the first five notes, then the last five — each at full width, rather than shrunk, so the arrows and the notes stay legible.",
    provenanceNote: "Drawn for this record with the Lab's offline coloured-pencil renderer (scripts/art, scene pp-hero). A teaching construction of the record's central relation: not a source figure, and every label is live HTML. The figures on the page are code-drawn on the same idea.",
    status: "active",
  },
  {
    id: "mp-opening-threads",
    src: "/visual-language/theories/mp/mp-hero.webp",
    owner: "music-preference",
    dimensions: { width: 1600, height: 620 },
    conceptualRole: "Draws what a structure of taste means as one picture: five graphite lines like a stave for five qualities of sound; some forty thin coloured threads, each a listener's preferences and no two alike, wandering across them; five places where many threads bunch and lean onto one line together, each marked by a soft wash; and one thick dark thread, yours, wandering through the same field on its own path.",
    materialRole: "scene",
    accessibilityRole: "explanatory",
    baseDescription: "Five straight graphite lines run across the page like a stave. Across them wander some forty thin coloured threads — teal, violet, ochre, coral, sky blue, green, magenta and indigo — each one different. At five places the threads bunch together and lean onto one of the lines, and a soft coloured wash gathers there: teal on the middle line at the left, lilac on the top line, yellow on the bottom line, coral on the second line and blue on the fourth, at the right. One thick dark thread starts from a small ring at the left edge and wanders through the same field on its own path, rising and falling without joining any crowd for long.",
    longDescription: "The threads are constructed to show what 'a structure of taste' means — many different preferences, gathering — and are not data. The five lines are drawn as a stave only as a picture of five separate qualities of sound; they are not ordered, and no line stands for a genre.",
    epistemicRole: "teaching",
    evidenceStatus: "not-empirical-evidence",
    cropCandidates: [
      { id: "mp-first-half", bounds: [20, 20, 800, 580], conceptualRole: "The first two gatherings and the start of the dark thread." },
      { id: "mp-second-half", bounds: [780, 20, 800, 580], conceptualRole: "The last three gatherings and the end of the dark thread." },
    ],
    responsiveGuidance: "Desktop bleeds the drawing to the page edge under the title, with four captions naming the lines, the threads, the places they gather and the dark thread. Below 760px it is recomposed as two stacked panels — the first half of the stave, then the second — each at full width, rather than shrunk, so the threads and the gatherings stay legible.",
    provenanceNote: "Drawn for this record with the Lab's offline coloured-pencil renderer (scripts/art, scene mp-hero). A teaching construction: not a source figure, and every label is live HTML. The figures on the page are code-drawn on the same idea.",
    status: "active",
  },
] as const;

export function getArtAsset(id: ArtAssetId): ArtAsset {
  const asset = ART_ASSETS.find((candidate) => candidate.id === id);
  if (!asset) throw new Error(`Unknown art asset: ${id}`);
  return asset;
}

/** Resolve a documented crop without creating a second editable geometry source. */
export function getArtCrop(assetId: ArtAssetId, cropId: string): ArtCrop["bounds"] {
  const asset = getArtAsset(assetId);
  const crop = asset.cropCandidates.find((candidate) => candidate.id === cropId);
  if (!crop) throw new Error(`Unknown art crop: ${assetId}/${cropId}`);
  return crop.bounds;
}
