import type { ArtAssetId } from "./art-manifest";

/**
 * SAME HAND · DIFFERENT MIND
 *
 * Mature experiences share the hand: type system, white canvas, material
 * vocabulary, provenance language, accessibility contract, quiet scholarship
 * and editorial discipline. They do not share a mind: hero geometry, section
 * geometry, visual metaphor, interaction form, art placement, page rhythm and
 * mobile narrative sequence remain specific to the knowledge.
 */

/** candidate = designed and verified, awaiting human review; not yet a benchmark. */
export type ExperienceStatus = "benchmark" | "frozen" | "candidate";
export type ExperienceOwner =
  | { kind: "surface"; id: "home" | "about" }
  | { kind: "record"; id: "gestalt-principles-in-music" | "reflexive-thematic-analysis" | "affective-events-theory" | "job-demands-resources" | "hpa-axis" | "ipa" | "tonal-hierarchy" | "meyers-expectancy-theory" | "hurons-itpra-theory" | "idyom-information-dynamics-of-music" | "self-determination-theory" | "social-exchange-theory" | "person-organisation-fit" | "workplace-design" | "auditory-scene-analysis" | "generative-theory-of-tonal-music" | "narmours-implication-realization-theory" | "statistical-learning-of-music" | "predictive-processing-in-music" | "music-preference" };

export type ExperienceManifestEntry = {
  experienceId: "home" | "about" | "gestalt" | "rta" | "aet" | "jdr" | "hpa" | "ipa" | "tonal" | "meyer" | "huron" | "idyom" | "sdt" | "set" | "po" | "wp" | "asa" | "gttm" | "narmour" | "stat" | "pp" | "mp";
  owner: ExperienceOwner;
  route: string;
  /** Historical provenance only; retired routes are not runtime destinations. */
  historicalBenchmarkRoute?: string;
  status: ExperienceStatus;
  knowledgeIdentity: string;
  pageThesis: string;
  primaryGeometry: string;
  persistentObject?: string;
  primaryVerb: string;
  primaryInteraction: string;
  whatChanges: readonly string[];
  whatStaysConstant: readonly string[];
  artIntensity: string;
  artAssetIds: readonly ArtAssetId[];
  handwritingRole: string;
  annotationRole: string;
  mobileStrategy: string;
  quietEnding: string;
  doNotFlattenInto: readonly string[];
};

export const EXPERIENCE_MANIFEST: readonly ExperienceManifestEntry[] = [
  {
    experienceId: "home",
    owner: { kind: "surface", id: "home" },
    route: "/concept-lab",
    status: "benchmark",
    knowledgeIdentity: "Site-level knowledge atlas.",
    pageThesis: "Ideas, evidence, methods and people become navigable without losing their kind or trail.",
    primaryGeometry: "An expansive orientation field that opens into disciplines, record kinds, selected entry points and provenance.",
    primaryVerb: "orient → explore",
    primaryInteraction: "Choose a discipline, record kind or starting record and enter the live atlas.",
    whatChanges: ["entry field", "record kind", "next useful place to explore"],
    whatStaysConstant: ["white canvas", "traceable record identity", "shared editorial shell"],
    artIntensity: "Immersive opening with selective territory and record-form fragments.",
    artAssetIds: ["home-atlas-head-globe", "home-organisation-systems", "home-record-forms", "home-provenance-sources"],
    handwritingRole: "Short marginal observations that make relations and curiosity visible.",
    annotationRole: "Orient the reader toward connections without turning the atlas art into a map of empirical evidence.",
    mobileStrategy: "Reflow the opening field and let the live headings and links remain primary as fragments quieten.",
    quietEnding: "Provenance and a restrained footer close the atlas after exploration.",
    doNotFlattenInto: ["a marketing hero with feature cards", "a generic academic dashboard", "a single fixed landing-page template"],
  },
  {
    experienceId: "about",
    owner: { kind: "surface", id: "about" },
    route: "/concept-lab/about",
    status: "benchmark",
    knowledgeIdentity: "Epistemic transparency: show how we know.",
    pageThesis: "Nothing loses its trail; visual explanation remains bounded by evidence and uncertainty remains designed space.",
    primaryGeometry: "Distinct editorial geometries for classification, source-to-record transformation, provenance, explanatory boundaries, uncertainty and orientation.",
    primaryVerb: "trace → distinguish",
    primaryInteraction: "Read forward through the explanation and backward through the evidence; use semantic navigation and skip links.",
    whatChanges: ["kind of knowledge object", "stage in the source-to-record trail", "provenance boundary"],
    whatStaysConstant: ["live HTML scholarship", "source responsibility", "white research-desk canvas"],
    artIntensity: "Quiet fragments, paper/source traces and restrained graphite marks; no major authored raster artwork.",
    artAssetIds: [],
    handwritingRole: "Marginal inquiry and qualification, never canonical content.",
    annotationRole: "Explain kinds of knowing and where a visual explanation stops.",
    mobileStrategy: "Recompose fragments around readable live stages rather than shrinking a desktop field.",
    quietEnding: "Unresolved questions and reader orientation leave the page open without adding interaction for its own sake.",
    doNotFlattenInto: ["developer documentation", "a provenance icon legend without explanation", "a static workflow poster"],
  },
  {
    experienceId: "gestalt",
    owner: { kind: "record", id: "gestalt-principles-in-music" },
    route: "/concept-lab/theory/gestalt-principles-in-music",
    status: "benchmark",
    knowledgeIdentity: "Music Psychology: grouping, whole/part and relational perception.",
    pageThesis: "The part changes with the whole; perceptual organisation emerges from relations rather than isolated features.",
    primaryGeometry: "A perceptual field that moves from whole/part comparison through grouping behaviour and an interactive listening experiment into quieter scholarship.",
    persistentObject: "The same musical material and relational field.",
    primaryVerb: "group → reinterpret",
    primaryInteraction: "Compare organisation, inspect grouping principles and move the same cue structure through the live experiment.",
    whatChanges: ["perceptual role", "grouping cue", "boundary or competing organisation"],
    whatStaysConstant: ["same event/material", "live principle labels", "whole-part relation"],
    artIntensity: "Territory-level listening field with restrained procedural overlays and quiet evidence.",
    artAssetIds: ["home-music-signal-wide"],
    handwritingRole: "Questions and perceptual observations at the field margins.",
    annotationRole: "Name grouping behaviour without making six principles read as a feature-card grid.",
    mobileStrategy: "Preserve the shared field while re-sequencing comparison, grouping and experiment vertically.",
    quietEnding: "History, evidence, limits, sources and provenance slow the page into scholarship.",
    doNotFlattenInto: ["six feature cards", "a universal theory-page template", "a decorative music poster"],
  },
  {
    experienceId: "rta",
    owner: { kind: "record", id: "reflexive-thematic-analysis" },
    route: "/concept-lab/method/reflexive-thematic-analysis",
    historicalBenchmarkRoute: "/reflexive-ta-target",
    status: "frozen",
    knowledgeIdentity: "Reflexive / revisable knowledge.",
    pageThesis: "ANALYSIS LEAVES TRACES. The page remembers the analysis.",
    primaryGeometry: "Positioned interpretation → theme as organising meaning → revisable worktable → researcher/reflexivity → theme construction → divergence → methodological stance and critique → proof sheet → sources/provenance.",
    persistentObject: "The material being revisited as codes, themes, interpretations and analytic decisions change.",
    primaryVerb: "revisit → interpret → revise",
    primaryInteraction: "Move through a recursive analytic journey whose marks retain earlier readings and methodological choices.",
    whatChanges: ["code and theme relations", "interpretive emphasis", "researcher position and reading"],
    whatStaysConstant: ["same data material", "reflexive responsibility", "live method language"],
    artIntensity: "Rich authored opening and worktable fields that resolve into quiet methodological scholarship.",
    artAssetIds: ["rta-interpretive-field"],
    handwritingRole: "Researcher voice, caution, revision and interpretive marginalia.",
    annotationRole: "Leave visible traces of analytic movement without turning handwriting into the method's canonical copy.",
    mobileStrategy: "Re-sequence the analytic argument while preserving recursive return, readable stages and source boundaries.",
    quietEnding: "Quality, sources, provenance and further reading provide scholarly resolution without pretending analysis is final.",
    doNotFlattenInto: ["a linear pipeline", "a generic method template", "a theme bucket or decorative worktable"],
  },
  {
    experienceId: "aet",
    owner: { kind: "record", id: "affective-events-theory" },
    route: "/concept-lab/theory/affective-events-theory",
    historicalBenchmarkRoute: "/aet-visual-rebuild",
    status: "frozen",
    knowledgeIdentity: "Temporal / event-driven knowledge.",
    pageThesis: "THE PAGE REMEMBERS WHAT HAPPENED.",
    primaryGeometry: "One person · one workday · many moments: stable environment, event, reaction, residue, later evaluation and action.",
    persistentObject: "One constructed working world that remains recognisable as attention moves through time and relation.",
    primaryVerb: "notice → locate → interpret → remember",
    primaryInteraction: "READ THE MAP → READ UNDER IT, with event, route, timing and underlying processes remaining in the same field.",
    whatChanges: ["event focus", "affective reaction", "behavioural route", "temporal reading"],
    whatStaysConstant: ["same workplace", "canonical relationship ledger", "the distinction between illustration and evidence"],
    artIntensity: "Cinematographic authored workplace fields with live labels and a quieter scholarly lower half.",
    artAssetIds: ["aet-opening-workplace", "aet-event-reaction", "aet-two-clocks", "aet-workday-strip", "aet-macrostructure-cinematography"],
    handwritingRole: "Selective event, residue and contextual notes attached to the lived field.",
    annotationRole: "Anchor work event, affective reaction, contextual dispositions, evaluation and later action without rasterising theory labels.",
    mobileStrategy: "Environment → event → reaction → affect-driven response → evaluation → deliberate action; preserve the stable map beneath the reading.",
    quietEnding: "Relationship ledger, evidence, boundaries, sources and provenance move the page from experience into scholarship.",
    doNotFlattenInto: ["a generic causal flowchart", "a universal storyboard", "a single outcome scale", "a purely decorative workplace illustration"],
  },
  {
    experienceId: "jdr",
    owner: { kind: "record", id: "job-demands-resources" },
    route: "/concept-lab/theory/job-demands-resources",
    status: "candidate",
    knowledgeIdentity: "Organisational Behaviour: functional categories and parallel processes.",
    pageThesis: "ONE JOB · TWO CURRENTS. Conditions are sorted by what they do, and each category sets off its own process.",
    primaryGeometry: "One authored working world read five ways: a field of conditions, one desk where a condition changes category, two parallel currents, a fork of one effort, and a junction where resources change the relationship — then a model that widens across dated sources.",
    persistentObject: "The same drawn workplace and the same desk.",
    primaryVerb: "sort → follow → compare",
    primaryInteraction: "Change who is doing the work, follow either current, place a demand on its route, turn the resource dial, step through the dated sources.",
    whatChanges: ["category of one condition", "focused process", "demand route", "route weight under resources", "state of the model by year"],
    whatStaysConstant: ["same workplace", "both processes present", "the demand held high", "canonical definitions and sources"],
    artIntensity: "Rich authored fields for the opening and three interactions; quiet typographic scholarship from the limits onward.",
    artAssetIds: ["jdr-working-world", "jdr-two-currents", "jdr-challenge-hindrance", "jdr-resource-interaction"],
    handwritingRole: "Short margin notes that name misreadings (not one dial; the type decides the advice).",
    annotationRole: "Keep marginalia in the artwork illustrative; all theory labels stay live HTML.",
    mobileStrategy: "Drawings become thumb-pannable strips in labelled, focusable containers; the sorting desk moves above both category columns.",
    quietEnding: "Cautions, qualifications, the dated trail, sources and provenance.",
    doNotFlattenInto: ["a burnout-versus-engagement dial", "a two-column pros and cons card", "a generic causal flowchart"],
  },
  {
    experienceId: "hpa",
    owner: { kind: "record", id: "hpa-axis" },
    route: "/concept-lab/mechanism/hpa-axis",
    status: "candidate",
    knowledgeIdentity: "Psychobiology: a regulated neuroendocrine pathway.",
    pageThesis: "A LOOP, NOT A LINE. Through what — not why.",
    primaryGeometry: "An acronym opening that steps down like the cascade; a sticky drawn descent walked step by step with its feedback loop; SAM and HPA as different timescales; one schematic day carrying the rhythms and the windows each measure looks through.",
    persistentObject: "The same cascade drawing, then the same schematic day.",
    primaryVerb: "descend → return → measure",
    primaryInteraction: "Scroll down the steps while the drawing lights each link; choose a timescale; choose a measure and see the time window it looks through.",
    whatChanges: ["lit link of the pathway", "timescale read on the day", "measurement window"],
    whatStaysConstant: ["whole pathway visible", "same day curve", "no concentration values"],
    artIntensity: "One richly layered authored pencil field carries the descent; code lights the selected link, then typography and measure windows take over.",
    artAssetIds: ["hpa-cascade-loop"],
    handwritingRole: "A few margin notes: through what — not why; carry this one.",
    annotationRole: "Keep schematic status explicit next to every drawn pathway and curve.",
    mobileStrategy: "The cascade appears once above the steps; step pips mark position; day strips pan sideways; the seven measures stack as a readable table.",
    quietEnding: "Chronic ≠ high, contradicted shortcuts, the dated trail, sources and provenance.",
    doNotFlattenInto: ["an anatomy illustration", "a three-box flowchart", "a stress score"],
  },
  {
    experienceId: "ipa",
    owner: { kind: "record", id: "ipa" },
    route: "/concept-lab/method/interpretative-phenomenological-analysis",
    status: "candidate",
    knowledgeIdentity: "Qualitative method: interpretative, idiographic practice.",
    pageThesis: "ONE PERSON AT A TIME · A READING OF A READING.",
    primaryGeometry: "Nested loops of the double hermeneutic; three commitments that can be lifted out; a line read three ways; a question sieve; a stack of case sheets that enforces idiography; a slow four-column pass over one constructed extract.",
    persistentObject: "The case — first one participant's sheet, then the stack of cases.",
    primaryVerb: "judge → read closely → distil",
    primaryInteraction: "Lift a commitment, move the researcher's loop, judge questions, step the procedure (and try the forbidden shortcut), foreground a column and find features in the extract, audit a draft.",
    whatChanges: ["distance between the two readings", "procedure stage", "foregrounded analytic column", "marked language feature"],
    whatStaysConstant: ["the participant's words", "all procedure steps readable", "constructed material labelled as not data"],
    artIntensity: "One procedural pencil field for the opening; the rest is typographic worktable and quiet method scholarship.",
    artAssetIds: ["ipa-double-hermeneutic"],
    handwritingRole: "The researcher's voice: verdicts on readings, scope of the current step.",
    annotationRole: "Mark the difference between paraphrase, interpretation and theory without claiming any reading is final.",
    mobileStrategy: "The case sheets stay pinned while the procedure list scrolls; the four columns become labelled rows with the chosen column foregrounded.",
    quietEnding: "Misuses, what IPA does not claim, core reading and provenance.",
    doNotFlattenInto: ["a generic coding pipeline", "the RTA worktable", "a list of steps without the case"],
  },
  {
    experienceId: "tonal",
    owner: { kind: "record", id: "tonal-hierarchy" },
    route: "/concept-lab/theory/tonal-hierarchy",
    status: "candidate",
    knowledgeIdentity: "Music Psychology: context-dependent tonal function.",
    pageThesis: "HOME IS A RELATION. Each pitch keeps its identity; the context decides its distance from home.",
    primaryGeometry: "One tonal field — twelve spokes and orbits of relative fit — that opens with no context, organises when given one, and is re-read as the teaching profile, as a held C4 across four contexts, beside a probe lab, key neighbourhoods and moving home.",
    persistentObject: "The same tonal field and the same twelve pitch classes.",
    primaryVerb: "listen → locate → re-read",
    primaryInteraction: "Hear context and probes, give the tones a context, rate probes on a keyboard, change the context before the same C4, step through key-space and dynamic stages.",
    whatChanges: ["distance of each tone from home", "context before the held probe", "key-space level", "balance between tonal regions"],
    whatStaysConstant: ["each pitch class's spoke", "the physical C4 probe", "no empirical profile values"],
    artIntensity: "One interrupted pigment field is revisited throughout; live tone markers and context changes carry every label and state.",
    artAssetIds: ["tonal-field"],
    handwritingRole: "Short readings of role (tonic / scale degree 1; the same C4).",
    annotationRole: "Name roles and boundaries without implying liking, probability or neural geometry.",
    mobileStrategy: "The field stays square; the context choice sits above the field it changes; comparison tables and lists carry the static reading path.",
    quietEnding: "Profile ≠ process, the evidence ledger, scope boundary, lineage, cautions, the trail and provenance.",
    doNotFlattenInto: ["a bar chart of note heights", "a card per concept", "a universal Western default"],
  },
  {
    experienceId: "meyer",
    owner: { kind: "record", id: "meyers-expectancy-theory" },
    route: "/concept-lab/theory/meyers-expectancy-theory",
    status: "candidate",
    knowledgeIdentity: "Historical aesthetic-psychological account of musical expectation and meaning.",
    pageThesis: "A phrase can leave several futures open; later context can change what an earlier event means.",
    primaryGeometry: "One unresolved phrase reaches a hinge, opens into several qualitative continuations, and leaves a faint retrospective trace.",
    persistentObject: "The same musical setup as its continuation and later context change.",
    primaryVerb: "listen → imagine → re-hear",
    primaryInteraction: "Choose a qualitative continuation, hear the constructed phrase, then compare fulfilment, delay and diversion while the same setup remains present.",
    whatChanges: ["selected continuation", "delay or diversion", "later interpretation of an earlier event"],
    whatStaysConstant: ["same initial context", "multiple futures remain possible", "no numerical probability or universal response"],
    artIntensity: "One spacious branching phrase field with a quiet, drawn-backward trace; the scholarly argument is typeset around it.",
    artAssetIds: ["meyer-open-phrase"],
    handwritingRole: "A short marginal question at the open phrase; not a quotation from Meyer.",
    annotationRole: "Name alternative futures and retrospective reading without assigning probability or affective magnitude.",
    mobileStrategy: "Keep the hinge and selected continuation in view; stack the audio choice beside its live explanation and preserve a static path through the meaning states.",
    quietEnding: "Historical scope, later theories, evidence boundaries, sources and provenance.",
    doNotFlattenInto: ["one correct next note", "a probability tree", "a pleasure meter"],
  },
  {
    experienceId: "huron",
    owner: { kind: "record", id: "hurons-itpra-theory" },
    route: "/concept-lab/theory/hurons-itpra-theory-of-expectation",
    status: "candidate",
    knowledgeIdentity: "Integrative theory of functionally distinct response systems around anticipated outcomes.",
    pageThesis: "Expectation is not one feeling and ITPRA is not a five-step conveyor.",
    primaryGeometry: "Unequal response windows approach, meet and extend beyond one outcome hinge; two post-onset functions remain parallel and appraisal can recur.",
    persistentObject: "The same anticipated musical outcome across timing and response-system readings.",
    primaryVerb: "wait → meet → appraise",
    primaryInteraction: "Keep the outcome constant while changing its constructed timing; select a response function and inspect its role in the shared temporal field.",
    whatChanges: ["constructed onset timing", "focused response function", "explanatory reading of the same outcome"],
    whatStaysConstant: ["same outcome", "all five response systems remain conceptually present", "no measured timeline or physiology"],
    artIntensity: "One wide, materially varied outcome field; live response labels and timing controls sit at the hinge, then scholarship becomes quiet.",
    artAssetIds: ["huron-outcome-hinge"],
    handwritingRole: "Brief prompts attached to anticipation, onset and later appraisal.",
    annotationRole: "Locate response functions in relation to the hinge without presenting exact timing or physiological amplitude.",
    mobileStrategy: "Reflow before, hinge and after as labelled reading bands; keep Prediction and Reaction visibly parallel after onset.",
    quietEnding: "Construct status, evidence boundary, system independence, sources and provenance.",
    doNotFlattenInto: ["five equal steps", "a neural trace", "a universal pleasure mechanism"],
  },
  {
    experienceId: "idyom",
    owner: { kind: "record", id: "idyom-information-dynamics-of-music" },
    route: "/concept-lab/theory/idyom-information-dynamics-of-music",
    status: "candidate",
    knowledgeIdentity: "Computational cognitive model of learned musical expectation.",
    pageThesis: "A model distributes expectation over possible events; distributional uncertainty differs from the information of one realised event.",
    primaryGeometry: "Long-term regularities and local musical context overlap as a model field; a separate live distribution reveals possible next events and calculated measures.",
    persistentObject: "One constructed event across two model distributions and different context windows.",
    primaryVerb: "learn → distribute → compare",
    primaryInteraction: "Change the model-context reading, inspect the same realised event inside different distributions, and compare entropy with information content.",
    whatChanges: ["modelled local context", "distribution spread", "which measure is foregrounded"],
    whatStaysConstant: ["selected realised event", "constructed data remain teaching material", "the model is not a proven brain mechanism"],
    artIntensity: "A layered context field introduces the model; the calculated distribution remains separate, legible and live.",
    artAssetIds: ["idyom-context-field"],
    handwritingRole: "Short model-reading prompts; no hand-written equations or unlabelled metrics.",
    annotationRole: "Keep long-term context, local context, candidate events, probability, entropy and information content distinct.",
    mobileStrategy: "Recompose context layers above a full-width live distribution; keep measures and the teaching-construction note adjacent to the values.",
    quietEnding: "Model fit versus mechanism, representation and corpus boundaries, sources and provenance.",
    doNotFlattenInto: ["a brain illustration", "a static surprise score", "a generic prediction loop"],
  },
  {
    experienceId: "sdt",
    owner: { kind: "record", id: "self-determination-theory" },
    route: "/concept-lab/theory/self-determination-theory",
    status: "candidate",
    knowledgeIdentity: "Organisational Behaviour: the kind of motivation behind an action, and how a reason stands in relation to the self.",
    pageThesis: "WHOSE REASON IS IT? The same action can be moved by a reason that presses from outside, one taken in but not owned, or one the person holds.",
    primaryGeometry: "One graphite action line crosses a loop standing for a person's sense of self. A reason is read by where it sits relative to the loop, then by two different cuts through one row of regulations, before needs, context, rewards and the mini-theory family enter.",
    persistentObject: "The same action line and the same loop, with the reason moving and changing character.",
    primaryVerb: "place → cut → own",
    primaryInteraction: "Hear a reason and watch it move across the loop; choose a regulation to see the two braces that hold it; change reason and arrangement separately on the autonomy/independence map; read the same context as need-supportive or need-thwarting; switch a reward's context.",
    whatChanges: ["where the reason sits relative to the loop", "which brace groups hold a regulation", "quadrant of the autonomy / independence map", "reading of the same context or reward"],
    whatStaysConstant: ["the same action line", "the same person and the same work", "all six regulations present as places, not steps", "canonical definitions, qualifications and sources"],
    artIntensity: "Rich authored opening and lens layers; quiet typographic passages; code-drawn marks for needs, context, refinements and the family; a scholarly coda.",
    artAssetIds: ["sdt-opening-loops", "sdt-reason-lens"],
    handwritingRole: "Short margin readings of where a reason sits — never canonical definitions.",
    annotationRole: "Keep every drawing qualitative: position and pigment show the kind of reason, not an amount of motivation or effort.",
    mobileStrategy: "The opening drawing turns so the action runs down and the two selves stack; the lens figure stays pinned above the statements; the two cuts become a vertical ledger with a brace on each side; controls sit before the autonomy map; the context map stacks by stage.",
    quietEnding: "Scope and limits, cautions, open questions, the trail, sources and provenance.",
    doNotFlattenInto: ["a motivation dial", "a three-needs formula", "a staircase from external to intrinsic", "a rewards-are-bad slogan"],
  },
  {
    experienceId: "set",
    owner: { kind: "record", id: "social-exchange-theory" },
    route: "/concept-lab/theory/social-exchange-theory",
    status: "candidate",
    knowledgeIdentity: "Organisational Behaviour: interdependence over time — what makes what happens next an exchange.",
    pageThesis: "WHAT MAKES WHAT HAPPENS NEXT AN EXCHANGE? One strand is a transaction; the history many exchanges weave is a relationship, and it changes how the next exchange is read.",
    primaryGeometry: "Two rails, one per actor, with the strands that pass between them. Later figures re-read the same two lines: a third rail for the wider group, spare routes for alternatives, colour for the sign of an exchange and path for what is done about it.",
    persistentObject: "The same two actor lines and the same helping act.",
    primaryVerb: "pass → answer → accumulate",
    primaryInteraction: "Specify what makes a favour an exchange; read one word three ways; change the exchange rule and watch only the return redraw; place an exchange on seven social/economic questions; set value and alternatives for each actor; step through one exchange as a turn of a spiral; vary sign, action and constraint separately.",
    whatChanges: ["which requirements are specified", "the meaning of reciprocity", "the route of the return", "each actor's value and alternatives", "sign, activity and constraint of a response"],
    whatStaysConstant: ["the same two actor lines", "the same helping act", "canonical definitions, qualifications and sources", "the distinction between illustration and evidence"],
    artIntensity: "One rich authored opening; code-drawn diagrams on the same two lines for every later figure; quiet typographic passages; a scholarly coda.",
    artAssetIds: ["set-opening-rails"],
    handwritingRole: "Short margin notes on the drawing — never canonical definitions.",
    annotationRole: "Keep every drawing qualitative: density shows accumulated history, thickness shows the value of what runs through another person; nothing is measured.",
    mobileStrategy: "The opening is turned so time runs down the page; each figure is pinned above its controls; the spiral and family map drop their in-figure labels and lean on the full lists beneath.",
    quietEnding: "Scope and limits, cautions, open questions, the dated trail, sources and provenance.",
    doNotFlattenInto: ["a single diagram of SET", "a money / non-money binary", "a dependence score", "a positive / negative response line"],
  },
  {
    experienceId: "po",
    owner: { kind: "record", id: "person-organisation-fit" },
    route: "/concept-lab/theory/person-organisation-fit",
    status: "candidate",
    knowledgeIdentity: "Organisational Behaviour: compatibility between a person and one particular organisation — and the sorting that makes an organisation out of its people.",
    pageThesis: "THE PEOPLE MAKE THE PLACE. Fit is a relation between a person and one particular place; the process that produces good fit also produces sameness, and what a study calls fit depends on which relation it measured.",
    primaryGeometry: "A person, a place with a door, and the room the door opens on. Later figures re-read the same pair: two pieces that sit alike or fit together, one survey item split into three, and one person compared with four different places.",
    persistentObject: "The same stand-in person and the same room, with the same four marks.",
    primaryVerb: "attract → select → lose",
    primaryInteraction: "Step a made-up room through Attraction, Selection and Attrition three times and watch its wall take the colour of its people; move two pieces between alike and fitting together; split one survey item into value congruence, needs–supplies and demands–abilities; compare the same person with four different targets.",
    whatChanges: ["who is in the room and who has left", "whether two pieces sit alike or fit together", "which of three perceptions one item is read as", "what the same person is compared with"],
    whatStaysConstant: ["the same stand-in person and room", "the same four marks", "canonical definitions, qualifications and sources", "the distinction between a teaching toy and evidence"],
    artIntensity: "One rich authored opening and authored sprites for every later figure; code-drawn pieces on the same drawn hand; quiet typographic passages; a scholarly coda.",
    artAssetIds: ["po-opening-rooms", "po-four-people", "po-room-wash", "po-four-targets"],
    handwritingRole: "Short margin notes and figure labels — never canonical definitions.",
    annotationRole: "Keep every drawing qualitative: the marks stand in for something held important, the wash carries a proportion in a made-up room, and no figure is a measurement or a finding.",
    mobileStrategy: "The opening is recomposed rather than turned — first and last rooms stacked so the people stay upright; the room and the two pieces are pinned above their controls; the four targets sit in a row of labelled pictograms above the full list.",
    quietEnding: "Cautions, open questions, the dated trail, sources and provenance.",
    doNotFlattenInto: ["a definition of fit as similarity", "a claim that organisations converge that fast or that far", "a warning against fit", "a single score of fit"],
  },
  {
    experienceId: "wp",
    owner: { kind: "record", id: "workplace-design" },
    route: "/concept-lab/theory/workplace-design",
    status: "candidate",
    knowledgeIdentity: "Organisational Behaviour: the built environment of work — and the name it shares with a different literature.",
    pageThesis: "THE ROOM IS A WORK CONDITION. Two literatures answer to this name and only one is about the room; that room is several conditions that do not move together, a poorly supportive one makes the same work cost more, and opening the plan trades privacy for contact without a guarantee that the trade balances.",
    primaryGeometry: "One office plan seen from above, re-read across the page: a wall between two literatures, six conditions of the room with two set apart, one workstation walked through a four-step mechanism, and partitions that come down.",
    persistentObject: "The same office plan: twelve desks, three windows, one door.",
    primaryVerb: "separate → layer → cost → open",
    primaryInteraction: "Read the room through one of six conditions and set noise and crowding apart from each other; walk one worker's room from supporting the task to affecting performance and wellbeing, one step at a time; take the partitions down from enclosed to mixed to fully open and watch contact and privacy change weight.",
    whatChanges: ["which condition of the room is in focus", "noise and crowding, set independently", "how far the mechanism has run", "how enclosed the plan is"],
    whatStaysConstant: ["the same office plan", "canonical definitions, qualifications and sources", "the distinction between physical design and job design", "the distinction between direction of relationship and magnitude"],
    artIntensity: "One rich authored opening — five sheets of tracing paper — and code-drawn figures on the same plan for everything after; quiet typographic passages; a scholarly coda.",
    artAssetIds: ["wp-opening-sheets"],
    handwritingRole: "Short margin notes and figure labels — never canonical definitions.",
    annotationRole: "Keep every drawing qualitative: marks carry direction, weights are weights and not quantities, and the record gives no room settings for any dimension.",
    mobileStrategy: "The opening deck is recomposed down the page rather than turned; each plan is pinned above its controls; the six conditions and the three layouts stay listed in full beneath the drawings.",
    quietEnding: "Cautions, open questions, the dated trail, sources and provenance.",
    doNotFlattenInto: ["a verdict on open-plan offices", "an office-comfort score", "a merger of physical design and job design", "a single 'workplace environment' variable"],
  },
  {
    experienceId: "asa",
    owner: { kind: "record", id: "auditory-scene-analysis" },
    route: "/concept-lab/theory/auditory-scene-analysis",
    status: "candidate",
    knowledgeIdentity: "Music Psychology: perception and organisation — how a single mixture of sound becomes streams and fused sounds.",
    pageThesis: "ONE MIXTURE, SEVERAL STREAMS. The ear receives a sum; the listener hears organised sound. What is heard depends on the connections drawn over the same tone events — across time, at one moment — and on cues that can pull a tone either way. A stream is not a source.",
    primaryGeometry: "One plane, time across and pitch up, with a dash for every tone. Every later figure changes the connections drawn over it: a line across time, a brace at one moment, a cue pulling one tone toward a stream.",
    persistentObject: "The same plane and the same tone events.",
    primaryVerb: "mix → group → fuse",
    primaryInteraction: "Hear one repeating pattern at three settings and draw it as one stream or two; toggle sources in the air and see one sum; colour the same tones by source or by stream; ask the sequential or the simultaneous question of the same chords; set four cues and watch one tone go; hear a component enter late; step through old-plus-new; hear a compound line as one melody or two strands.",
    whatChanges: ["frequency separation and rate", "which organisation is drawn over the tones", "which sources are sounding", "which way each cue pulls", "when a component enters", "which step of old-plus-new"],
    whatStaysConstant: ["the same plane", "the record's own synthetic audio presets", "canonical definitions, qualifications and sources", "the distinction between a stream and a source"],
    artIntensity: "One rich authored opening — the world, the ear, the streams — and code-drawn figures on one plane for everything after; quiet typographic passages; a scholarly coda with the evidence ledger.",
    artAssetIds: ["asa-opening-mixture"],
    handwritingRole: "Short margin notes and axis words — never canonical definitions.",
    annotationRole: "Keep every drawing qualitative and synthetic: contours are organisations a listener might make, not detections; cues pull as a metaphor, not an algorithm; no percept is a test answer.",
    mobileStrategy: "The opening is recomposed in two rows rather than turned; each figure is pinned above its controls; every setting and every percept stays listed in full beneath the drawing.",
    quietEnding: "Evidence ledger, scope, lineage, cautions, open questions, the dated trail, sources and provenance.",
    doNotFlattenInto: ["stream segregation as the whole of ASA", "one stream equals one source", "a frequency threshold", "predictive coding", "AI source separation"],
  },
  {
    experienceId: "gttm",
    owner: { kind: "record", id: "generative-theory-of-tonal-music" },
    route: "/concept-lab/theory/generative-theory-of-tonal-music",
    status: "candidate",
    knowledgeIdentity: "Music Psychology: musical structure and grammar — a formal, listener-oriented account of how a tonal surface can be assigned several related hierarchical descriptions.",
    pageThesis: "ONE SURFACE, FOUR QUESTIONS. The same sixteen notes support grouping, meter, time-span heads and tonal relations; the descriptions are related, not the same, and reduction changes the level of description rather than deleting notes.",
    primaryGeometry: "One sixteen-note phrase drawn as pencilled noteheads, with brackets above for grouping, dots below for meter, stems and rings for heads, and arcs for prolongation. The sound never changes; only what is drawn around the notes does.",
    persistentObject: "The same sixteen-note phrase, with its own numbering, timing and sound.",
    primaryVerb: "ask → describe → reduce",
    primaryInteraction: "Choose one of four questions and hear the same phrase; separate grouping from meter; step a time-span reduction from spans to heads to the alternative it leaves open; hear four levels of the same phrase with the set-aside notes still drawn; read the four descriptions as a pipeline and as an interacting architecture.",
    whatChanges: ["which question is asked of the phrase", "which structure is drawn", "which events a reduction keeps in play", "how the four descriptions are related"],
    whatStaysConstant: ["the same sixteen-note phrase and its sound", "the record's own events, timing and synthesis", "canonical definitions, qualifications and sources", "the distinction between a constructed analysis and a claim about listeners"],
    artIntensity: "One rich authored opening — the four structures around one phrase — and code-drawn figures on the same phrase for everything after; quiet typographic passages; a scholarly coda with the evidence ledger.",
    artAssetIds: ["gttm-opening-structures"],
    handwritingRole: "Short margin notes and figure labels — never canonical definitions.",
    annotationRole: "Keep every drawing a constructed teaching analysis: heads are one proposed selection with an alternative left open, reduced playbacks are sonifications, tension is a tonal relation and not a feeling.",
    mobileStrategy: "The opening is recomposed as two rows rather than shrunk; each figure is pinned above its controls; every reduction level, every step and every description stays listed in full beneath the drawing; trees fold into indented lists.",
    quietEnding: "Evidence ledger, scope, lineage, cautions, open questions, the dated trail, sources and provenance.",
    doNotFlattenInto: ["a listening algorithm run in a fixed order", "a pipeline of four causes", "reduction as deletion", "tonal tension as emotion", "one correct parse"],
  },
  {
    experienceId: "narmour",
    owner: { kind: "record", id: "narmours-implication-realization-theory" },
    route: "/concept-lab/theory/narmours-implication-realization-theory",
    status: "candidate",
    knowledgeIdentity: "Music Psychology: expectation and prediction — a formal cognitive model in which local melodic intervals generate several tendencies that a following interval may realise, partially realise or deny.",
    pageThesis: "THE PATH AND ITS LEAN. Two tones have been heard and a third has not. One interval seems to ask for several things at once — which way, how big a step, whether to stay near, whether to come back — and a tone that arrives realises some and denies others. A denial is not an error and a realisation is not a score.",
    primaryGeometry: "One pitch × time field with three tones in it: two heard, one still to come. The first interval is drawn, the leans it seems to have are pencilled round the empty place, three continuations wait beside it with a row of four verdicts each, and the chosen one joins the path.",
    persistentObject: "The two heard tones and the interval between them, on a field whose pitch guides and three moments in time never move.",
    primaryVerb: "hear → lean → realise or deny",
    primaryInteraction: "Choose the fixed first interval and a continuation, and hear it; step from two tones to what they imply to a third that answers; slide the size of the first interval across the record's small / neither / large convention; hold a physical movement and change the interval that came first to see the same movement fulfil or deny; hear every continuation from a verdict sheet; let two sources of expectation converge or conflict; step the loop that makes the last interval the next starting point; focus one of three layers of the tradition.",
    whatChanges: ["which third tone arrives", "which first interval it follows", "the size of the first interval", "which verdicts a continuation earns", "how the two sources of expectation meet"],
    whatStaysConstant: ["the first two tones and the interval between them", "the record's own constructed stimuli, timing and synthesis", "canonical definitions, thresholds stated as conventions, qualifications and sources", "the distinction between a tendency and a law"],
    artIntensity: "One rich authored opening — two gestures with their leans — and code-drawn figures on the same field for everything after; typographic passages for the tradition and the evidence; a scholarly coda.",
    artAssetIds: ["narmour-opening-gestures"],
    handwritingRole: "Short figure labels and margin notes — never canonical definitions.",
    annotationRole: "Keep every mark a qualitative tendency: an arrow says which way and a brace says how much compared with the first interval, but none aims at a pitch; keep the small / large thresholds as a tested convention rather than a biological switch.",
    mobileStrategy: "The opening is recomposed as two stacked panels rather than shrunk; each field is pinned above its controls; every continuation, every relation and every verdict stays listed in full beneath the drawing; the verdict tables fold into one card per continuation.",
    quietEnding: "Evidence as a ladder of five questions, scope, the dated trail, cautions, open questions, sources and provenance.",
    doNotFlattenInto: ["five laws on a dashboard", "a correct-note quiz", "one exact next-note prediction", "a two-factor model attributed to Narmour", "an innate melodic grammar"],
  },
  {
    experienceId: "stat",
    owner: { kind: "record", id: "statistical-learning-of-music" },
    route: "/concept-lab/theory/statistical-learning-of-music",
    status: "candidate",
    knowledgeIdentity: "Music Psychology: expectation and prediction — a multi-contributor research framework and mechanism family for how exposure to distributional and sequential regularities can shape musical organisation, segmentation, familiarity and probabilistic expectation.",
    pageThesis: "A STREAM, AND WHAT A TALLY OF IT WOULD SHOW. Every tone in the constructed stream is exactly as common as every other, yet what follows a tone is not the same for every tone; and the structure the sound never marks can be watched emerging in the counts as the exposure grows. The counter is a teaching representation, not a claim that listeners tally.",
    primaryGeometry: "One unbroken stream of thirty-six tones drawn as beads at their own pitches in three rows, with the thread between beads thick where the next tone was probable and hair-thin where it was not, bars beneath saying the same in numbers, and a nine-by-nine ledger of what followed what.",
    persistentObject: "The same thirty-six-tone stream, its pitch mapping, its timing and its sound.",
    primaryVerb: "expose → count → notice",
    primaryInteraction: "Pick a tone and a next tone in the ledger and compare how common the second is overall with how likely it is after the first; switch what is counted on the ribbon (sound, how common, what follows, where the bars dip); slide how much of the stream has been heard, or play it and watch the tally grow; switch between two exposure histories that agree on every total and differ after X; focus the short-term or long-term clock; separate learning from prediction; describe the same stream as pairwise probabilities, as chunks, or as both; follow the five-step loop.",
    whatChanges: ["what is counted", "how much of the stream has been heard", "which exposure history is in play", "which clock is in focus", "how the boundaries are described"],
    whatStaysConstant: ["the same thirty-six-tone stream and its sound", "the record's own constructed exposure histories, timing and synthesis", "the record's counts, to the digit", "the distinction between information a learner could use and a claim that anyone learned it"],
    artIntensity: "One rich authored opening — the stream with its hidden groups made visible — and code-drawn figures on the same stream for everything after; typographic passages for the framework's limits; a scholarly coda with the evidence ledger.",
    artAssetIds: ["stat-opening-stream"],
    handwritingRole: "Short figure labels and margin notes — never canonical definitions.",
    annotationRole: "Keep the tally a teaching representation, keep the cut rule a way of reading the bars, and keep the mechanism, the representational format and the causal story of enculturation open.",
    mobileStrategy: "The opening is recomposed as two lines of eighteen tones rather than shrunk; each figure's controls come before it; the ledger, the counts and the two histories stay listed in full beneath the drawing; the two-column boundary folds into a single column.",
    quietEnding: "Evidence ledger, the dated trail, cautions, open questions, neighbouring lenses, sources and provenance.",
    doNotFlattenInto: ["conscious arithmetic", "learning equals liking", "a proof that the visitor learned the stream", "one settled mechanism", "a lab exposure as a miniature culture"],
  },
  {
    experienceId: "pp",
    owner: { kind: "record", id: "predictive-processing-in-music" },
    route: "/concept-lab/theory/predictive-processing-in-music",
    status: "candidate",
    knowledgeIdentity: "Music Psychology: expectation and prediction — a broad predictive framework for music perception as an ongoing interaction among generative models, sensory input, prediction errors, precision, learning and possible action.",
    pageThesis: "THE GHOST AND THE SOUND. A model expects, and a ghost of what it expects is laid over what actually arrives; what is left between them is information, and how much it counts is the precision it is given. The same 120 ms displacement lies more than three standard deviations away in a narrow expectation and barely one in a broad one, and an expected note that never comes is a mismatch with silence.",
    primaryGeometry: "A dashed ghost of what is expected laid over a solid row of what arrives, with the residual drawn as a red trace between them; a ladder of levels with predictions running down and errors running up; and a Gaussian expectation envelope on a time axis with the same displaced onset marked on it.",
    persistentObject: "The expected moment (0 ms) and the same displaced target (+120 ms), on an axis and in an envelope that always keeps the record's two constructed contexts drawn.",
    primaryVerb: "expect → compare → weigh",
    primaryInteraction: "Send predictions down, errors up or both on the ladder; hold the expected note present or omit it and see what is left at the expected onset; slide the width of the expectation across the record's two constructed contexts and read how many standard deviations the same displacement spans; choose between updating the model and changing the input; follow the seven parts of the circuit.",
    whatChanges: ["which way the message travels", "whether the expected note is present", "the width of the expectation", "whether the model is updated or the input is changed", "which part of the circuit is in focus"],
    whatStaysConstant: ["the same +120 ms displacement and the same target event", "the record's own constructed contexts and omission example", "canonical definitions, qualifications and sources", "the distinction between a teaching hierarchy and a cortical map"],
    artIntensity: "One rich authored opening — the model, its ghosts, what arrives and what is left — and code-drawn figures on the same idea for everything after; typographic passages for the framework's boundaries; a scholarly coda with the evidence ledger.",
    artAssetIds: ["pp-opening-ghosts"],
    handwritingRole: "Short figure labels and margin notes — never canonical definitions.",
    annotationRole: "Keep every drawing a constructed teaching illustration: the envelopes are not brain distributions and predict no neural magnitude, the ladder's levels are a teaching hierarchy, and prediction error is information, not failure or feeling.",
    mobileStrategy: "The opening is recomposed as two stacked panels rather than shrunk; each figure is pinned above its controls; the two constructed contexts, the omission states and every part of the circuit stay listed in full beneath the drawing; the two-column boundary folds into a single column.",
    quietEnding: "Evidence ledger, the critical boundaries, scope, cautions, open questions, neighbouring lenses, sources and provenance.",
    doNotFlattenInto: ["a next-note guessing theory", "generative AI", "prediction error as failure or surprise", "precision as confidence or entropy", "a settled cortical wiring diagram"],
  },
  {
    experienceId: "mp",
    owner: { kind: "record", id: "music-preference" },
    route: "/concept-lab/theory/music-preference",
    status: "candidate",
    knowledgeIdentity: "Music Psychology: a research field, not a single theory — how musical preferences are structured, why people differ, what shapes them, what music is for, and what happens when people choose their own music at work.",
    pageThesis: "A FIELD, NOT A THEORY. Taste feels like yours alone, yet it falls into a shape: preferences cluster. The page follows the strands the record follows — two ways of measuring that shape, five things that shape a preference, what music is for, how a taste gets built, what happens when the listening is done at work — and only at the end offers its own frame, Person–Music Fit, marked as ours and not as any author's.",
    primaryGeometry: "A crowd of individual threads over five lines, gathering in places; a map of seven works in two literatures over sixteen years; five qualities of sound each drawn as a trace of its own character; and five strands twisting into one rope.",
    persistentObject: "The five MUSIC qualities, always listed in full beside the trace being shown; the same music at the right of the question about who likes it or what it is for; the seven works of the record's trail.",
    primaryVerb: "measure → shape → use",
    primaryInteraction: "Choose a work on the map of the field; choose one of the five qualities of sound and hear a short synthesised sketch of it; switch between genre names and musical excerpts and see four blocks become five; pull one of five strands through the rope; flip the question from who likes this music to what it is for; walk the road of development to the line where the cited account stops; switch between music the organisation supplies and music the employee chooses; set the person's side and the situation's side apart or together.",
    whatChanges: ["which work on the map is in focus", "which quality of sound is drawn and heard", "what the structure was built from, and how many factors result", "which strand is drawn over the others", "which question is asked of the music", "which stop on the road", "who chooses the music at work", "which side of a fit is on the table"],
    whatStaysConstant: ["the record's seven works and their order", "the five MUSIC dimensions, paraphrased as qualities of sound and never as genre lists", "the two models and what each was built from", "canonical definitions, qualifications and sources", "that Person–Music Fit is this page's frame and not an established theory"],
    artIntensity: "One rich authored opening — a crowd of individual tastes and the shape they make — and code-drawn figures on the same idea for everything after; typographic passages for the field's questions; a scholarly coda with the trail, cautions, open questions and sources.",
    artAssetIds: ["mp-opening-threads"],
    handwritingRole: "Short figure labels and margin notes — never canonical definitions.",
    annotationRole: "Keep every drawing a constructed teaching illustration: the threads are not data, the sound traces and sketches are not the study's excerpts and not genres, and Person–Music Fit is marked ✦ wherever it appears.",
    mobileStrategy: "The opening is recomposed as two stacked panels rather than shrunk; each figure is pinned above its controls; numbered choices drop their drawn hint while keeping it in their accessible name; every quality, model, lever, stop and side stays listed in full beneath the drawing.",
    quietEnding: "The trail in order, cautions, open questions, sources and provenance.",
    doNotFlattenInto: ["a single theory of musical preference", "a list of genres", "genre labels and responses to music as one measurement", "liking music as music being good for a task", "Person–Music Fit as an established named theory", "adult taste as fixed"],
  },
];

export function getExperience(experienceId: ExperienceManifestEntry["experienceId"]): ExperienceManifestEntry {
  const experience = EXPERIENCE_MANIFEST.find((candidate) => candidate.experienceId === experienceId);
  if (!experience) throw new Error(`Unknown experience manifest entry: ${experienceId}`);
  return experience;
}
