/**
 * The browser harness deliberately keeps a small, named route set rather than
 * guessing visual coverage from implementation details.  The representative
 * set is a stable smoke surface; full-site adds every currently registered
 * record route without turning route discovery into a visual assumption.
 */

export const VIEWPORTS = [
  { id: "desktop-1440", label: "1440", width: 1440, height: 900, tier: "desktop" },
  { id: "desktop-1024", label: "1024", width: 1024, height: 800, tier: "desktop" },
  { id: "tablet-768", label: "768", width: 768, height: 1024, tier: "desktop" },
  { id: "mobile-390", label: "390", width: 390, height: 844, tier: "mobile" },
  { id: "mobile-360", label: "360", width: 360, height: 800, tier: "mobile" },
];

const probe = (id, kind, selector, accessibleTarget, expectedChange, options = {}) => ({
  id,
  kind,
  selector,
  accessibleTarget,
  expectedChange,
  keyboardMethod: options.keyboardMethod ?? "Enter",
  stableSelector: options.stableSelector,
  expectedHrefPrefix: options.expectedHrefPrefix,
  reducedMotion: options.reducedMotion ?? false,
  optional: options.optional ?? false,
});

export const CONCEPTUAL_PROBES = {
  aetMap: probe(
    "aet-map-toggle",
    "toggle",
    '.aev-map-toggle button[aria-pressed]:nth-child(2)',
    "Read under it",
    "aria-pressed changes to true and the same macrostructure remains visible",
    { stableSelector: ".aev-interactive-macro-map", reducedMotion: true },
  ),
  gestaltListening: probe(
    "gestalt-grouping-mode",
    "toggle",
    '.studio-switcher[role="group"] button:nth-child(2)',
    "Cue conflict comparison",
    "aria-pressed changes to true and the grouping comparison mode changes",
    { stableSelector: ".studio-visual", reducedMotion: true },
  ),
  rtaPhase: probe(
    "rta-phase-tab",
    "toggle",
    '#rta-phases [role="tab"]:nth-child(2)',
    "second recursive analysis phase",
    "aria-selected changes to true and the analysis panel changes",
    { stableSelector: "#rta-analysis-panel" },
  ),
  tunedOutAttribution: probe(
    "tuned-out-attribution-reading",
    "toggle",
    '#model [data-attribution-control="leisure"]',
    "Leisure attribution",
    "aria-pressed changes while both the shared event and alternative reading remain present",
    { stableSelector: "#model [data-model-reading]", reducedMotion: true },
  ),
  tunedOutStudy: probe(
    "tuned-out-study-selection",
    "toggle",
    '#studies [data-study-control="1"]',
    "Study 2",
    "the selected study and its evidence sheet change without removing the study sequence",
    { stableSelector: "#studies [data-study-panel]", reducedMotion: true },
  ),
  tunedOutClaim: probe(
    "tuned-out-claim-evidence",
    "toggle",
    '#claims [data-claim-control="1"]',
    "second claim and its evidence status",
    "the evidence register changes to the selected claim and documented status",
    { stableSelector: "#claims [data-claim-panel]", reducedMotion: true },
  ),
  jdrSortByFunction: probe(
    "jdr-sort-by-function",
    "toggle",
    '#sorting [role="group"] button:nth-child(2)',
    "An expert",
    "aria-pressed changes and close supervision moves to the demand side while the same desk crop stays in view",
    { stableSelector: "#sorting figure", reducedMotion: true },
  ),
  hpaRhythm: probe(
    "hpa-rhythm-timescale",
    "toggle",
    '#rhythm [role="group"] button:nth-child(3)',
    "Ultradian pulses",
    "aria-pressed changes and the same schematic day is re-read as pulses without removing the daily curve",
    { stableSelector: "#rhythm svg", reducedMotion: true },
  ),
  ipaCommitment: probe(
    "ipa-lift-commitment",
    "toggle",
    '#what-it-meant [role="group"] button:nth-child(3)',
    "Idiography",
    "aria-pressed changes and the lifted commitment stays drawn as a residual trace beside the other two",
    { stableSelector: "#what-it-meant figure svg", reducedMotion: true },
  ),
  tonalSameNote: probe(
    "tonal-same-note-context",
    "toggle",
    '#same-note [role="group"] button:nth-child(4)',
    "D major context",
    "aria-pressed changes and the held C4 moves to a new distance in the same tonal field",
    { stableSelector: "#same-note [role=\"img\"]", reducedMotion: true },
  ),
  sdtReasonLens: probe(
    "sdt-reason-lens",
    "toggle",
    '#reason [role="group"] button:has-text("This fits who I am")',
    "This fits who I am.",
    "aria-pressed changes and the reason is re-read as integrated while the same action line stays in the loop",
    { stableSelector: "#reason [data-place]", reducedMotion: true },
  ),
  sdtCutRow: probe(
    "sdt-cut-row",
    "toggle",
    '#row button:has-text("Intrinsic motivation")',
    "Intrinsic motivation",
    "aria-pressed changes and the two braces that hold the regulation light while the whole row stays on the page",
    { stableSelector: "#row ol", reducedMotion: true },
  ),
  setRules: probe(
    "set-exchange-rule",
    "toggle",
    '#rules button:has-text("Generalised reciprocity")',
    "Generalised reciprocity",
    "aria-pressed changes and only the return is redrawn, through the wider group, while the same helping act stays in place",
    { stableSelector: "#rules [data-rule]", reducedMotion: true },
  ),
  setResponse: probe(
    "set-response-activity",
    "toggle",
    '#response button:has-text("Holds back")',
    "Holds back",
    "aria-pressed changes and the strand's path shortens while its colour, the sign of the exchange, stays",
    { stableSelector: "#response [data-value]", reducedMotion: true },
  ),
  poRoom: probe(
    "po-sorting-stage",
    "toggle",
    '#asa [role="group"] button:has-text("Attraction")',
    "Attraction",
    "aria-pressed changes and the candidates who apply move to the door while the same room, door and street stay in place",
    { stableSelector: "#asa [data-room]", reducedMotion: true },
  ),
  poFits: probe(
    "po-fit-geometry",
    "toggle",
    '#two [role="group"] button:has-text("Complementary fit")',
    "Complementary fit",
    "aria-pressed changes and the two pieces close into each other while both pieces and both definitions stay on the page",
    { stableSelector: "#two [data-fit]", reducedMotion: true },
  ),
  wpMixer: probe(
    "wp-room-condition",
    "toggle",
    '#elements [role="group"] button:has-text("Noise and acoustics")',
    "Noise and acoustics",
    "aria-pressed changes and the noise sheet comes forward while the same plan, its desks and its people stay in place",
    { stableSelector: "#elements [data-focus]", reducedMotion: true },
  ),
  wpStress: probe(
    "wp-stress-step",
    "toggle",
    '#mechanism [role="group"] button:has-text("More effort needed for the same work")',
    "More effort needed for the same work",
    "aria-pressed changes and the extra effort appears while the work and its length stay the same",
    { stableSelector: "#mechanism [data-level]", reducedMotion: true },
  ),
  wpEnclosure: probe(
    "wp-enclosure",
    "toggle",
    '#tradeoff [role="group"] button:has-text("fully open")',
    "fully open",
    "aria-pressed changes and the partitions come down while the same plan and the same people stay in place",
    { stableSelector: "#tradeoff [data-state]", reducedMotion: true },
  ),
  asaSplitter: probe(
    "asa-stream-splitter",
    "toggle",
    '#listen [role="group"] button:has-text("Far + fast")',
    "Far + fast",
    "aria-pressed changes and the same tone events move to a new frequency separation and rate while the plane, the contours and the audio control stay in place",
    { stableSelector: "#listen [data-preset]", reducedMotion: true },
  ),
  asaQuestion: probe(
    "asa-two-questions",
    "toggle",
    '#grouping [role="group"] button:has-text("At one moment")',
    "At one moment",
    "aria-pressed changes and the braces come forward while the same nine tones and the lines across time stay drawn, fainter",
    { stableSelector: "#grouping [data-q]", reducedMotion: true },
  ),
  gttmLens: probe(
    "gttm-lens",
    "toggle",
    '#phrase [role="group"] button:has-text("Meter")',
    "Meter",
    "aria-pressed changes and the metrical dots come forward while the same sixteen notes, their audio and the other structures' controls stay in place",
    { stableSelector: "#phrase [data-lens]", reducedMotion: true },
  ),
  gttmReduction: probe(
    "gttm-reduction",
    "toggle",
    '#reduction [role="group"] button:has-text("Structural skeleton")',
    "Structural skeleton",
    "aria-pressed changes and three events stay in play while the other thirteen remain drawn, faint, on the same phrase",
    { stableSelector: "#reduction [data-level]", reducedMotion: true },
  ),
  narmourFork: probe(
    "narmour-fork",
    "toggle",
    '#question [role="group"][aria-label="Choose the fixed implicative interval"] button:has-text("Large")',
    "Large · C4 → G4",
    "aria-pressed changes and the three large-interval continuations replace the small ones while the first tone, the pitch guides and the third-tone field stay in place",
    { stableSelector: "#question [data-family]", reducedMotion: true },
  ),
  narmourStep: probe(
    "narmour-step",
    "toggle",
    '#implication [role="group"] button:has-text("What they imply")',
    "What they imply",
    "aria-pressed changes and the four leans come forward round the empty third place while the same two tones and the interval between them stay drawn",
    { stableSelector: "#implication [data-step]", reducedMotion: true },
  ),
  narmourMovement: probe(
    "narmour-movement",
    "toggle",
    '#verdicts [role="group"] button:has-text("up → down")',
    "up → down",
    "aria-pressed changes and both fields redraw the same physical movement, each with the verdict its own first interval gives it, while the two-by-two table stays listed",
    { stableSelector: "#verdicts [data-movement]", reducedMotion: true },
  ),
  statLens: probe(
    "stat-lens",
    "toggle",
    '#stream [role="group"][aria-label="What to count"] button:has-text("What follows")',
    "What follows",
    "aria-pressed changes and the thread thickens where the next tone was probable while the same thirty-six beads, their pitches and the audio stay in place",
    { stableSelector: "#stream [data-lens]", reducedMotion: true },
  ),
  statWorld: probe(
    "stat-world",
    "toggle",
    '#histories [role="group"][aria-label="Choose an exposure world"] button:has-text("WORLD B")',
    "WORLD B",
    "aria-pressed changes and the bands from X reroute while the matched totals for Y and Z stay the same and both histories stay listed in the table",
    { stableSelector: "#histories [data-world]", reducedMotion: true },
  ),
  statClock: probe(
    "stat-clock",
    "toggle",
    '#clocks [role="group"][aria-label="Which clock?"] button:has-text("Long-term")',
    "Long-term",
    "aria-pressed changes and the long-term clock comes forward while the short-term clock stays drawn, fainter",
    { stableSelector: "#clocks [data-focus]", reducedMotion: true },
  ),
  ppLadder: probe(
    "pp-ladder",
    "toggle",
    '#model [role="group"][aria-label="Which way does it travel?"] button:has-text("Errors up")',
    "Errors up",
    "aria-pressed changes and the arrows running up come forward while the three levels and the arrows running down stay drawn, fainter",
    { stableSelector: "#model [data-flow]", reducedMotion: true },
  ),
  ppOmission: probe(
    "pp-omission",
    "toggle",
    '#error [role="group"][aria-label="Choose whether the expected target is present"] button:has-text("Expected event omitted")',
    "Expected event omitted",
    "aria-pressed changes and a hollow mismatch stands where the expected note was while the four preceding beats and the dashed ghost stay in place",
    { stableSelector: "#error [data-present]", reducedMotion: true },
  ),
  ppPrecision: probe(
    "pp-precision",
    "toggle",
    '#precision [role="group"][aria-label="Choose a rhythmic context to inspect"] button:has-text("CONTEXT B")',
    "CONTEXT B · OPEN",
    "aria-pressed changes and the envelope widens while the same +120 ms target, the expected onset and both constructed contexts stay drawn",
    { stableSelector: "#precision [data-on]", reducedMotion: true },
  ),
  mpQualities: probe(
    "mp-qualities",
    "toggle",
    '#shape [role="group"][aria-label="The five MUSIC dimensions"] button:has-text("Intense")',
    "I Intense",
    "aria-pressed changes and the drawn trace becomes tall and jagged while all five qualities stay listed beside it",
    { stableSelector: "#shape [data-quality]", reducedMotion: true },
  ),
  mpInstrument: probe(
    "mp-instrument",
    "toggle",
    '#models [role="group"][aria-label="How the structure was measured"] button:has-text("Play the music")',
    "Play the music",
    "aria-pressed changes and four blocks become five while both models stay listed in full",
    { stableSelector: "#models [data-mode]", reducedMotion: true },
  ),
  mpFit: probe(
    "mp-fit",
    "toggle",
    '#fit [role="group"][aria-label="Which side to show"] button:has-text("The person")',
    "The person’s side",
    "aria-pressed changes and the situation's piece is set aside while both sides stay listed in full",
    { stableSelector: "#fit [data-side]", reducedMotion: true },
  ),
  neighbourhoodRelation: probe(
    "knowledge-neighbourhood-relation",
    "link",
    ".knowledge-neighbourhood-list .knowledge-neighbour-record a",
    "first related record link",
    "link is keyboard reachable and resolves to an intended record",
    { expectedHrefPrefix: "/concept-lab/", optional: true },
  ),
  neighbourhoodFallback: probe(
    "knowledge-neighbourhood-fallback",
    "link",
    ".knowledge-neighbourhood-fallback a",
    "broader field fallback link",
    "fallback link is keyboard reachable and resolves to Library",
    { expectedHrefPrefix: "/concept-lab/library", optional: true },
  ),
  save: probe(
    "save-restore",
    "save",
    "button.savebtn",
    "Save for later",
    "aria-pressed changes and remains true after reload",
  ),
};

const surface = (id, route, reason, interaction = "none", probes = []) => ({ id, route, reason, interaction, probes });
const record = (id, kind, slug, reason, interaction = "none", probes = []) => ({
  id,
  route: `/concept-lab/${kind}/${slug}`,
  reason,
  interaction,
  probes,
});

export const REPRESENTATIVE_ROUTES = [
  surface("home", "/concept-lab", "Site-level atlas orientation and entry points."),
  surface("library", "/concept-lab/library", "Library discovery surface; neighbourhood probes run on a representative record page.", "none"),
  surface("saved", "/concept-lab/saved", "Personal working pile with empty and saved states."),
  surface("about", "/concept-lab/about", "Epistemic transparency, provenance and skip-link behaviour."),
  record("jdr", "theory", "job-demands-resources", "Redesigned theory: one authored working world read as categories, currents, demand types and interactions.", "jdr", [CONCEPTUAL_PROBES.jdrSortByFunction, CONCEPTUAL_PROBES.save]),
  record("pe-fit", "theory", "person-environment-fit", "Generic theory route, correspondence interaction and save/restore.", "save", [CONCEPTUAL_PROBES.save, CONCEPTUAL_PROBES.neighbourhoodRelation, CONCEPTUAL_PROBES.neighbourhoodFallback]),
  record("aet", "theory", "affective-events-theory", "Frozen temporal/event-driven benchmark.", "aet", [CONCEPTUAL_PROBES.aetMap]),
  record("gestalt", "theory", "gestalt-principles-in-music", "Music benchmark with perceptual/listening interaction.", "gestalt", [CONCEPTUAL_PROBES.gestaltListening]),
  record("specialized-music", "theory", "tonal-hierarchy", "Redesigned music theory: one tonal field re-read across contexts, with probe-tone lab and key space.", "tonal", [CONCEPTUAL_PROBES.tonalSameNote, CONCEPTUAL_PROBES.save]),
  record("rta", "method", "reflexive-thematic-analysis", "Frozen reflexive method benchmark.", "rta", [CONCEPTUAL_PROBES.rtaPhase]),
  record("ipa", "method", "interpretative-phenomenological-analysis", "Redesigned method practice: double hermeneutic, case-by-case procedure and the four-column close pass.", "ipa", [CONCEPTUAL_PROBES.ipaCommitment, CONCEPTUAL_PROBES.save]),
  record("hpa-axis", "mechanism", "hpa-axis", "Redesigned mechanism: sticky cascade descent, feedback loop, rhythms and windows of measurement.", "hpa", [CONCEPTUAL_PROBES.hpaRhythm, CONCEPTUAL_PROBES.save]),
  record("tuned-out", "study", "tuned-out-or-dialed-in", "Study route with interactive observer readings, three-study evidence dossier, and provenance.", "tuned-out-study", [CONCEPTUAL_PROBES.tunedOutAttribution, CONCEPTUAL_PROBES.tunedOutStudy, CONCEPTUAL_PROBES.tunedOutClaim, CONCEPTUAL_PROBES.save]),
  record("sdt", "theory", "self-determination-theory", "Redesigned theory: one action line and one loop for the self, a reason moved across it, two cuts through one row of regulations, needs, context and refinements.", "sdt", [CONCEPTUAL_PROBES.sdtReasonLens, CONCEPTUAL_PROBES.sdtCutRow, CONCEPTUAL_PROBES.save]),
  record("set", "theory", "social-exchange-theory", "Redesigned theory: two actor lines and the strands between them, read as an exchange, a rule, a dependence and a history.", "set", [CONCEPTUAL_PROBES.setRules, CONCEPTUAL_PROBES.setResponse, CONCEPTUAL_PROBES.save]),
  record("po", "theory", "person-organisation-fit", "Redesigned theory: one room at three moments, run as an Attraction–Selection–Attrition toy, then two pieces that sit alike or fit together, one survey item split into three, and one person compared with four targets.", "po", [CONCEPTUAL_PROBES.poRoom, CONCEPTUAL_PROBES.poFits, CONCEPTUAL_PROBES.save]),
  record("wp", "theory", "workplace-design", "Redesigned theory: a wall between two literatures, then one office plan read as six conditions, a four-step workspace-stress mechanism and a set of partitions that come down.", "wp", [CONCEPTUAL_PROBES.wpMixer, CONCEPTUAL_PROBES.wpStress, CONCEPTUAL_PROBES.wpEnclosure, CONCEPTUAL_PROBES.save]),
  record("asa", "theory", "auditory-scene-analysis", "Redesigned music theory: one plane of tone events, read as streams, sources, two grouping questions, cues that pull, fusion and old-plus-new, with the record's own audio presets.", "asa", [CONCEPTUAL_PROBES.asaSplitter, CONCEPTUAL_PROBES.asaQuestion, CONCEPTUAL_PROBES.save]),
  record("gttm", "theory", "generative-theory-of-tonal-music", "Redesigned music theory: one sixteen-note phrase asked four questions, then grouping and meter, time-span heads with their alternative, reduction as a change of level, and an interacting architecture.", "gttm", [CONCEPTUAL_PROBES.gttmLens, CONCEPTUAL_PROBES.gttmReduction, CONCEPTUAL_PROBES.save]),
  record("narmour", "theory", "narmours-implication-realization-theory", "Redesigned music theory: two tones heard and a third still to come, what the first interval seems to ask for, a dial across the record's small / large convention, the same movement earning different verdicts, two sources of expectation, a loop, and a ladder of evidence.", "narmour", [CONCEPTUAL_PROBES.narmourFork, CONCEPTUAL_PROBES.narmourStep, CONCEPTUAL_PROBES.narmourMovement, CONCEPTUAL_PROBES.save]),
  record("stat", "theory", "statistical-learning-of-music", "Redesigned music theory: one constructed stream of thirty-six tones, a nine-by-nine ledger of what followed what, a ribbon that shows the structure emerging as the exposure grows, two exposure histories with the same totals, two clocks, and the learning/prediction and mechanism boundaries.", "stat", [CONCEPTUAL_PROBES.statLens, CONCEPTUAL_PROBES.statWorld, CONCEPTUAL_PROBES.statClock, CONCEPTUAL_PROBES.save]),
  record("pp", "theory", "predictive-processing-in-music", "Redesigned music theory: a model and its ghosts laid over what arrives, a ladder of predictions and errors, an expected note that is present or absent, the same displacement against a narrow and a broad expectation, and the whole as a circuit.", "pp", [CONCEPTUAL_PROBES.ppLadder, CONCEPTUAL_PROBES.ppOmission, CONCEPTUAL_PROBES.ppPrecision, CONCEPTUAL_PROBES.save]),
  record("mp", "theory", "music-preference", "Redesigned music theory: a field, not a theory — a crowd of tastes and the shape they make, a map of seven works in two literatures, five qualities of sound drawn and heard, two ways of measuring, five strands twisted into one rope, what music is for, a road of development, the room at work, and Person–Music Fit as this page's own frame.", "mp", [CONCEPTUAL_PROBES.mpQualities, CONCEPTUAL_PROBES.mpInstrument, CONCEPTUAL_PROBES.mpFit, CONCEPTUAL_PROBES.save]),
];

export const FULL_SITE_ROUTES = [
  ...REPRESENTATIVE_ROUTES,
  record("meyer-expectancy", "theory", "meyers-expectancy-theory", "Registered theory route."),
  record("huron", "theory", "hurons-itpra-theory-of-expectation", "Registered music theory route."),
  record("idyom", "theory", "idyom-information-dynamics-of-music", "Registered music theory route."),
];

export const REQUIRED_REPRESENTATIVE_IDS = [
  "home",
  "library",
  "saved",
  "about",
  "jdr",
  "pe-fit",
  "aet",
  "gestalt",
  "specialized-music",
  "rta",
  "ipa",
  "hpa-axis",
  "tuned-out",
  "sdt",
  "set",
  "po",
  "wp",
  "asa",
  "gttm",
  "narmour",
  "stat",
  "pp",
  "mp",
];

export function routesForMode(mode) {
  if (mode === "representative") return REPRESENTATIVE_ROUTES;
  if (mode === "full-site") return FULL_SITE_ROUTES;
  throw new Error(`Unknown verification mode: ${mode}`);
}
