import type { Metadata } from "next";
import { ipa } from "@/content/ipa";
import { Contents } from "../_components/Contents";
import { Sources, ProvenanceRegister, IpaNeighbour } from "../_components/Apparatus";
import { Note, Rich, SectionLead } from "../_components/Type";
import { Pigment, Intervention } from "../_components/Pigment";

export const metadata: Metadata = { title: "Interpretative Phenomenological Analysis · B2 prototype" };
const contents = [{ id: "commitments", title: "Three commitments" }, { id: "one-case", title: "One case at a time" }, { id: "across-cases", title: "Across cases" }, { id: "question", title: "Question & method" }, { id: "quality", title: "Quality & limits" }, { id: "sources", title: "Sources & provenance" }];

export default function IpaPage() {
  return <main id="b2-main" className="b2-main b2-ipa-page">
    <header className="b2-title-block b2-ipa-title"><p className="b2-eyebrow">Method · Qualitative inquiry</p><h1>Interpretative<br /><em>Phenomenological</em><br />Analysis</h1><div className="b2-title-aside"><Intervention tone="emerald">Stay with this person.</Intervention><p>Interpretation begins<br />in the particular.</p></div><p className="b2-intro">{ipa.oneSentence}</p></header>
    <Contents items={contents} />
    <section id="commitments" className="b2-section"><SectionLead n="01" title="Making sense of someone’s sense-making."><p>The participant’s experience and the researcher’s interpretation are held in a relationship of responsibility.</p></SectionLead>
      <div className="b2-hermeneutic"><div><span className="b2-eyebrow">The participant</span><p>Making sense<br /><em>of an experience.</em></p></div><span className="b2-hermeneutic-relation" aria-hidden="true"><Pigment tone="emerald" seed={72} /></span><div><span className="b2-eyebrow">The researcher</span><p>Making sense<br /><em>of that sense-making.</em></p></div></div>
      <Note glyph="■">Compressed paraphrase of the double hermeneutic, following the canonical account of Smith (2019). These are not participant quotations.</Note>
      <div className="b2-commitments">{ipa.commitments!.map(item => <article key={item.title}><h3>{item.title}</h3><p>{item.body}</p></article>)}</div><div className="b2-continuous-reading"><p><Rich text={ipa.doubleHermeneutic!.body} /></p></div>
    </section>
    <section id="one-case" className="b2-section"><SectionLead n="02" title="Before a shared theme, one particular account."><p>The sequence is recursive within a case. The next participant begins afresh; they are not a test of the previous account.</p></SectionLead>
      <div className="b2-case-practice"><aside className="b2-case-anchor"><span className="b2-eyebrow">The unit of attention</span><span className="b2-one">one</span><span className="b2-case-word">case</span><Pigment tone="emerald" seed={44} className="b2-case-pigment" /><p>Keep returning to this participant’s words.</p><Intervention tone="emerald">particularity first</Intervention></aside><ol className="b2-case-sequence">{ipa.procedure!.slice(0, 5).map((step, i) => <li key={step.n} id={i === 0 ? "close-reading" : undefined}><span>{step.n}</span><div><h3>{step.title}</h3><p><Rich text={step.body} /></p></div></li>)}</ol><div className="b2-case-return"><a href="#close-reading">↶ Return to the account</a><p>Read a statement against the language that supports it. The written account must make that route inspectable.</p></div></div>
      <div className="b2-close-pass"><div><span className="b2-eyebrow">In the close reading</span><h3>Attend to what is said.<br /><em>And how it is said.</em></h3><p>No participant transcript is simulated in this prototype. These are methodological questions for working with a real account.</p></div><dl>{ipa.craft!.map(item => <div key={item.title}><dt>{item.title}</dt><dd>{item.asks}</dd></div>)}</dl></div>
      <p className="b2-small">Attend to {ipa.attendTo!.join(", ")}.</p><Note glyph="■">Contemporary procedural guidance restated from the canonical method record. Interpretation stays demonstrably connected to the participant’s account.</Note>
      <div className="b2-next-case"><span className="b2-eyebrow">Then, the next participant</span><h3>{ipa.procedure![5].title}</h3><p>{ipa.procedure![5].body}</p><a href="#close-reading">Begin again at close reading ↶</a><Note glyph="●">{ipa.cardinalRule}</Note></div>
    </section>
    <section id="across-cases" className="b2-section"><SectionLead n="03" title="Find a relation. Keep the difference."><p>Only after the case-level work do the accounts meet. Convergence must not make divergence disappear.</p></SectionLead><div className="b2-case-connections"><article><span className="b2-eyebrow">A relation across cases</span><h3>Convergence</h3><p>Look for shared experiential concerns after working through each participant’s account.</p><Pigment tone="ochre" seed={17} /></article><article><span className="b2-eyebrow">Particularity remains</span><h3>Divergence</h3><p>Keep the different meanings, tensions and individual accounts visible within the interpretation.</p><Pigment tone="violet" seed={20} /></article></div><Note>Editorial explanation of the canonical convergence/divergence requirement. Neither pigment density nor visual overlap represents agreement, prevalence or evidential strength.</Note><div className="b2-continuous-reading"><h3>{ipa.procedure![7].title}</h3><p>{ipa.procedure![7].body}</p><p>A Group Experiential Theme is developed after case-level work. Each Personal Experiential Theme remains attached to the particular participant whose account supports it.</p></div><div className="b2-terminology"><h3>Terms that preserve the analytic level</h3><dl>{ipa.terminology!.map(item => <div key={item.now}><dt>{item.now}</dt><dd><p>{item.note}</p><span className="b2-small">Earlier terminology: {item.was}</span></dd></div>)}</dl><Note glyph="■">The 2022 vocabulary sharpens the analytic distinctions. Older terminology does not by itself invalidate the analysis in an older paper.</Note></div></section>
    <section id="question" className="b2-section"><SectionLead n="04" title="The question chooses the method."><p>IPA asks about sense-making in a personally significant experience. It does not answer every question that can be put to an interview.</p></SectionLead><div className="b2-question-reading">{ipa.questionFit!.filter((_, i) => [0, 1, 5, 7].includes(i)).map(item => <details key={item.question}><summary><span>{item.question}</span><span className="b2-fit-label">{item.fits ? "An IPA question" : "A different methodological task"}</span></summary><p>{item.why}</p></details>)}</div><Note glyph="▲">Canonical teaching questions, not participant data or study findings. Open a question to inspect the methodological reasoning.</Note></section>
    <section id="quality" className="b2-section b2-quiet"><SectionLead n="05" title="Show the route from words to interpretation."><p>Methodological accountability asks how an interpretation earns its place in an account.</p></SectionLead><div className="b2-quality-intro"><h3>Four markers of quality</h3><p>Following Nizza, Farr & Smith (2021), the canonical record identifies these markers for analysing and writing. They are methodological criteria, not numerical reliability scores.</p></div><ol className="b2-quality-markers">{ipa.qualityMarkers!.map(item => <li key={item.n}><span>{item.n}</span><div><h3>{item.title}</h3><p>{item.body}</p></div></li>)}</ol><Note glyph="●">Source-grounded quality guidance. See the source contribution in the reading register below.</Note>
      <div className="b2-ipa-boundary"><div><h3>What the method is for</h3><p>Detailed, idiographic interpretation of personally significant experience in a bounded group, grounded in participants’ accounts.</p><h3>Where it stops</h3><p>Population prevalence, prediction across a population and representative generalisation are different research tasks. An interpretative account cannot travel freely away from the language that supports it.</p></div><div><h3>Qualifications</h3>{ipa.qualifications.map(item => <Note key={item} glyph="?"><Rich text={item} /></Note>)}</div></div><div className="b2-continuous-reading"><h3>Two ways to lose the relationship</h3><p><Rich text={ipa.misuses[1]} /></p><p><Rich text={ipa.misuses[2]} /></p><Note glyph="✦">The misuse framing is Concept Lab editorial guidance; it is not a finding about how frequently researchers make these errors.</Note></div>
    </section>
    <section id="sources" className="b2-section b2-quiet"><SectionLead n="06" title="A practice with an intellectual lineage."><p>Read the methodological argument, the procedural guidance and examples of analytic craft for their different contributions.</p></SectionLead><Sources minimum={ipa.coreReading.slice(0, 2).concat(ipa.coreReading[4], ipa.coreReading[7])} full={ipa.fullSources} /><ProvenanceRegister items={ipa.provenance} local="This B2 composition follows case-level practice, return to the account, a fresh start for the next case, and convergence with divergence retained. It contains no fabricated transcript, participant account, controlled comparison or A/B experiment. The questions and analytic prompts are inherited teaching material." /><IpaNeighbour /></section>
  </main>;
}
